### ISSUE TITLE
v0.8.9_10: Wrong entry is there in drop down box options 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1003]
**SEVERITY:**  Major

**MODULE:** Pop by age chart

**Platform:**  Windows 7 / Chrome 46.0

**RELEASE:** v0.8.9

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.9/preview/popbyage.html
2)  Pop by age chart will be loaded.
3)  Click “color” 
4)  Note that wrong entry is there in drop down box options

**ACTUAL RESULTS:**
Wrong entry is there in drop down box options 

**EXPECTED RESULTS:**
There should be ‘constant’ instead of ‘indicator/#ffb600’

**SCREENSHOT:**

![v0 8 9_10](https://cloud.githubusercontent.com/assets/9950837/11335776/3d964fa8-9201-11e5-810c-723e2baa595b.png)

**Comment by plward11** [comment]
It looks like `which` value defined here https://github.com/Gapminder/vizabi/blob/563806dd8a67bdc835f0680d7760ce7bcd157b0a/src/vizabi-gapminder.js#L572 as `"#ffb600"` is used as the translation key for the IndicatorPicker in https://github.com/Gapminder/vizabi/blob/563806dd8a67bdc835f0680d7760ce7bcd157b0a/src/components/indicatorpicker/indicatorpicker.js#L78.

The first time the PopByAge chart is loaded, `this.model.marker[this.markerID].which` evaluates to `"#ffb600"`, which is translated as `indicator/#ffb600`. Once "Constant" is picked in the color chart, `this.model.marker[this.markerID].which` evaluates to `_default`, which is translated as `Constant` and sets the color to `#fa5ed6`.

Couple of options that keep PopByAge's initial color the same as Constant color:

1) **Set color to** `#fa5ed6` - Change the `which` value for `marker` for the PopByAge chart in `src/vizabi-gapminder.js` to `_default`, which results in "Constant" correctly showing up in the IndicatorPicker and the color being set to `#fa5ed6`.
2) **Set color to** `#ffb600` -  Change the `which` value for `marker` for the PopByAge chart in `src/vizabi-gapminder.js` to `_default`, and also change the `_default` color in `.data/waffles/metadata.json` to `#ffb600`.

Do we want the PopByAge chart to first appear as `#ffb600`, but keep the Constant option set to `#fa5ed6`?
