### ISSUE TITLE
Hovering a trail bubble should hilight the bubble

### ISSUE THREAD

**Issue by olarosling** [vizabi/vizabi#1235]
I can't see what the cursor is hovering: 
![image](https://cloud.githubusercontent.com/assets/496398/12263978/9e48261a-b933-11e5-9c3e-8f2e33c5886a.png)

Please make it behave like this 
a. Put the trail bubble temporary in front
2. add corona around the hovered bubble ( same corona always when hovering a bubble.)
![image](https://cloud.githubusercontent.com/assets/496398/12264008/e39ed9fc-b933-11e5-932d-f49d2c2659db.png)

**Comment by angieskazka** [comment]
added in https://github.com/vizabi/vizabi/commit/2e6acaaed44b40baeee28fb975038436712ca000
