### ISSUE TITLE
Race-condition in base/model.js suppresses the "change" event under certain conditions

### ISSUE THREAD

**Issue by motin** [vizabi/vizabi#1321]
Found while debugging https://github.com/Gapminder/vizabi/issues/1274

I suggest splitting and cleaning up vizabi's 1659 lines long base/model.js code, adding unit tests where necessary and in general follow the advice in [Clean Code](http://www.amazon.com/Clean-Code-Handbook-Software-Craftsmanship/dp/0132350882). The race-condition might likely be refactored away during this process.

---

here are the relevant comments from #1274

I checked this just now. I can reproduce the bug as described. However, do note that changing the Y axis to wealth/inequality/gini a 2nd time results in the desired route change on the tools page. (yes, it should work the second time, because the data will be cached in vizabi and served from cache, which will change timings) -- That supports the race-condition-theory.

While I have not yet determined the exact cause, it seems to be due to a race condition within the vizabi's model set, trigger, freeze and unfreeze methods.

I would not blame the tools js for this, other than changing the timing of events, causing new vectors for this race condition to surface. The tools js is simply listening to the ‘persistentChange’ change event from vizabi (and will update the url hash when received), but it is not triggered. not even the ‘change’ event is triggered internally in vizabi.

From the limited debugging I did, it seemed like model set triggered a “change” event, which was frozen. Then when it was the unfrozen (thus released/triggered), the "change" event got frozen anew without being unfrozen.

**Comment by angieskazka** [comment]
@motin i'm already on it in #1320 and have some progress. model.js is currently down to 1200 lines

**Comment by angieskazka** [comment]
this issue wasn't seen for more than a year now
cleaning the code is an ongoing process
