### ISSUE TITLE
Inconsistent naming of options and model

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#1322]
The options passed into vizabi is actually a JSON representation of the model. So let's not call them options but model.

**Comment by angieskazka** [comment]
i guess it's a little more complicated. the options as JSON passed to vizabi is not an instnance of any vizabi model, so it's not. they are exactly 'representations' of it. we should call it some word that means 'representation'

draft, outline, wireframe, blueprint?

**Comment by jheeffer** [comment]
Yes, I thought of that too. And then I thought of how complicated all the different names are.

Within vizabi we have `model.getPlainObject` and `model.set()` accepts either one of them (plain objects and real models.

External page is now `.getModel()` and `.setModel()`.

At least it's model now and not options, but a bigger renaming everywhere could straighten it out even more. But that goes a lot deeper.

**Comment by jheeffer** [comment]
was completed with 5118bba6511fbe02f1f813b05e1bb71d47c938fd though discussion still ongoing

**Comment by angieskazka** [comment]
@jheeffer more renaming
model (json) --> state, 
state (json) --> chart

then UI and language and data go inside state JSON repressentation of model

within vizabi:
`model.getJSON()` returns JSON representation of model, 
`model.getModel()` returns MODEL, 
`model.set()` accepts either one

External page:
`Vizabi().getState()` return JSON -- former getOptions
`Vizabi().setState()` accepts JSON -- former setOptions

**Comment by jheeffer** [comment]
We can't rename things just in the JSON.

this would make 

JSON: state.chart
model: model.state

be the same thing, that would be inconsistent and thus confusing. If we rename things, we have to do it consistently.

**Comment by angieskazka** [comment]
Inconsistent naming of options and model was fixed

there is ongoing discussion about if we should have "state" inside model or not because "locale" and "data" are also, technically, parts of state

but this triggers bigger discussions about refactoring the entire model tree, something that we refer to as vizabi 2. it's a big refactoring and it's definitely out of scope for this issue
