### ISSUE TITLE
Option in UI model: Allow zoom out to 50% outside data area, just to fit tons of labels

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#1326]
this is very tricky, i don’t know how to approach it. we now have zoomed min/max expressed in data values and zooming out would require to step outside domain boundaries, which we can't do if we don't want negative life expectancy, etc

alternative would be to express and save zoom in ratio and shift, then we can put any ratio but we loose convenience of data values. Manual X and Y limits input becomes more complex, zoom on rectangle becomes more complex, retaining zoom on a certain fragment when switching between lin and log also becomes more complex

![image](https://cloud.githubusercontent.com/assets/3648190/12917223/7ecbbfde-cf38-11e5-8b74-6af3fd7d16fa.png)

**Comment by jheeffer** [comment]
Weird question: Why limit zooming out at all?

**Comment by angieskazka** [comment]
@jheeffer 
right now: because we can't get outside the domain
proposed zooming out by 50%: to not get absurdly looking chart with tiny something somewhere
