### ISSUE TITLE
URL flickers as if multiple state update events are triggered (likely zoom-set min-max loop is to blame)

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#1339]
After resize is done I drop the window corner, and the url flickers as if multiple state update events are triggered!

Also the history is populated with tons of entries

http://tools-dev.gapminderdev.org/tools/bubbles#_state_entities_select@_geo=rus&labelOffset@:0&:0;&trailStartTime=2015;;;&marker_axis%2F_y_which=life%2F_expectancy&domainMin:10&domainMax:83&zoomedMin:10&zoomedMax:83

Change to LEX on y axis

**Comment by jheeffer** [comment]
BubbleChart component force-sets zoom/min-max and sets size and label extent on resize. That's the url updates you see. No clue why. Part of the big forest of calls in charts. I'm scared of big forests :D

**Comment by angieskazka** [comment]
why wouldn't i see them on preview page, but only on tools page?

**Comment by jheeffer** [comment]
Alright, the events get fired in both preview and tools and I don't think they should be fired. 

However, angular on tools page also has a onhashchange event which for some reason encodes the hash. Why encoding? No idea. Why does it even care about hashchanges: I guess for navigation without reloading, using the hash.
As those 4 or 5 persistent change events from Vizabi reach tools page, it generates 8-10 hash changes. For every one of the Vizabi events the TP code changes hash, then Angular updates hash. TP changes hash back again, Angular updates hash again. etc.

So in essence: two bugs
1) (I think unnecessary) forced triggering of events on resizing in bubble chart
2) Angular onhashchange event runs on every hash change and interferes with url-state

By the way: it is significantly less annoying with developer toolbar closed. Seems dev toolbar open has big influence on speed of hash changes.

**Comment by angieskazka** [comment]
This seems to be resolved somehow. Likely i fixed it in fada1b6b841e0d47bb1ba1fca04e3f9f515f32a1

**Comment by jheeffer** [comment]
It was fixed on toolspage by same fix as toolspage back button fix. 
However, your fix might have fixed a deeper lying issue too which also caused the flickering. To check that, you should check how many events are fired when resizing the page.
