### ISSUE TITLE
Refactor sliders

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#1409]
`bubblesize` and `sizeslider` components are very similar. Make one base component. And add two decoration classes -- one for arcs and one for sizeslider

 `simpleslider` would also become a decoration class of that base component, a kind of decoration that would downgrade the base class and make it very primitive

**Comment by jheeffer** [comment]
Don't know all about it but wouldn't it be better to have simple slider as
base at enhance it for more complex sliders?

**Comment by angieskazka** [comment]
can be as well. in this case we would need to have `simple slider` as a base class. 
then `complex slider` as an extension
then `bubblesize slider` and `labelsize slider` as extensions of complex slider

i would leave it up to @dab2000 to find the optimal inheritance pattern
