### ISSUE TITLE
Popbyage: can make labels overlap when resizing the window

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1428]
**SEVERITY:**  Major

**MODULE:**  Pop by age chart

**Platform:**  Windows 7 / Chrome 48.0 

**RELEASE:** v0.12.8

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.8/preview/popbyage.html 
2)  Pop by age Chart will be loaded.
3)  Set the chart resolution as 960x300 
4)  Select all the bars.
5)  Note that text is overlapping

**ACTUAL RESULTS:**
Text is overlapping after selecting the bars

**EXPECTED RESULTS:**
Text should not overlap in any case

**SCREENSHOT:**

![v0 12 8_17](https://cloud.githubusercontent.com/assets/9950837/13626633/86207158-e5e5-11e5-8b10-01f711a8846b.png)

**Comment by angieskazka** [comment]
situation now: no labels, no cry :)
