### ISSUE TITLE
On full screen view, the tooltip line and values are not at the default position. 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1431]
**SEVERITY:**  Minor

**MODULE:**  line chart

**Platform:**  Windows 7 / Chrome 48.0 

**RELEASE:** v0.12.8

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.8/preview/linechart.html 
2)  Line Chart will be loaded.
3)  Click “Expand” and make sure that mouse is not moved after clicking “Expand”
4)  Note that on the full screen the tooltip line and values are pointing to no line.

**ACTUAL RESULTS:**
On the full screen the tooltip line and values are pointing to no line. It happens for a few seconds. After a few seconds the tooltip lines get its default position 

**EXPECTED RESULTS:**
Tooltip line and values should adopt default position immediately after clicking “Expand”

**SCREENSHOT:**

![v0 12 8_20](https://cloud.githubusercontent.com/assets/9950837/13628361/5891aac8-e5f3-11e5-87da-dc12a1def81f.png)

**Comment by kuguarpwnz** [comment]
Can't reproduce

**Comment by angieskazka** [comment]
yes. also it's too old to be relevant
