### ISSUE TITLE
Bubble is overlapping the year by increasing the bubble size

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1432]
**SEVERITY:**  Minor

**MODULE:**  Bubble Map chart

**Platform:**  Windows 7 / Chrome 48.0 

**RELEASE:** v0.12.8

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.12.8/preview/bubblemap.html 
2)  Bubble map Chart will be loaded.
3)  Click size icon
4)  Drag the minimum pointer to the maximum 
5)  Note that bubble is overlapping the year by increasing the bubble size

**ACTUAL RESULTS:**
Bubble is overlapping the year by increasing the bubble size 

**EXPECTED RESULTS:**
Any kind of overlapping should not be there

**SCREENSHOT:**

![v0 12 8_21](https://cloud.githubusercontent.com/assets/9950837/13631021/3cc99aec-e604-11e5-86ab-ea21f1e6e353.png)

**Comment by angieskazka** [comment]
Yes, we will return to this issue when we'll have other maps available and the year would be overlapping more frequently.

Maybe we'll have a different placement, like this one:

![image](https://cloud.githubusercontent.com/assets/3648190/13631504/52a30458-e5e5-11e5-98e9-f70e99aef4ac.png)

**Comment by k6Labz** [comment]
@angieskazka 
Another overlapping issue. The tooltip is overlapping the year. 

![comment2](https://cloud.githubusercontent.com/assets/9950837/13631799/4d554038-e608-11e5-9f93-a2ac30276da4.png)

**Comment by angieskazka** [comment]
screw that. this ovelapping is rare and insignificant
will reopen if the situation will change
