### ISSUE TITLE
Outliers break the axis // Trails are drawn beyond the defined limit

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1433]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:**  Windows 7 / Chrome 48.0 

**RELEASE:** Stage

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles 
2)  Bubble Chart will be loaded.
3)  Click find and select “Barbados”
4)  Click lock
5)  Drag the slider to the start and click play
6)  Let the slider reach the end
7)  Note that trails are drawn beyond the defined limit

**ACTUAL RESULTS:**
Trails are drawn beyond the defined limit from 1884 to 1907.

**EXPECTED RESULTS:**
All the trails should be available in the defined range

**SCREENSHOT:**

![v0 12 8_22](https://cloud.githubusercontent.com/assets/9950837/13633016/8c7b6494-e60e-11e5-8dfd-3bc7bfdae948.png)

**Comment by angieskazka** [comment]
you don't want them to cut away and you want them to cut away, because you want to use the space better. solution for now: we provide the full picture but zoom in to a fragment, using quantiles in metadata

**Comment by angieskazka** [comment]
solution for now: we provide the full picture but zoom in to a fragment, using zoom parameters in config. We can click 100% to zoom out. When switching to a new indicator it's always 100%
