### ISSUE TITLE
The year in the background of chart and over the slider is not same while slider is moving  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1544]
**SEVERITY:**  Major

**MODULE:**
*Bubble chart
*Mountain chart
*Bubble Map

**Release:** v0.13.3

**Platform:** IPhone 4 / Safari 9

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.13.3/preview/bubblechart.html 
2) Bubble Chart will be loaded.
3) Click on USA and china bubble 
4) Click on play and generate trials 
5) Observe the year on the slider

**ACTUAL RESULTS:**
The year appears over the slider is not the exact as the year appeared in the background 

**EXPECTED RESULTS:**
The year over the slider and in the background should be same while the slider is moving 

**SCREENSHOT:**

![photo](https://cloud.githubusercontent.com/assets/9950837/13950150/197a7bfa-f04b-11e5-9f3b-0d003f253597.PNG)

**Comment by sergey-filipenko** [comment]
https://github.com/Gapminder/vizabi/pull/1596

**Comment by angieskazka** [comment]
@sergey-filipenko  the bug persists on OSX + Chrome 49 (mountain chart and bubble map)

![vzqokbfxfu](https://cloud.githubusercontent.com/assets/3648190/14442303/4b344a2e-0039-11e6-998d-e555571e4bf7.gif)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2135

**Comment by angieskazka** [comment]
@sergey-filipenko please also fix it on bubble chart now and retest on bar rank chart

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2196

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2200
