### ISSUE TITLE
The slider ball blinks when user drag the slider ball left right in find menu   

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1584]
**SEVERITY:**  Major

**MODULE:**  Bubble chart

**Platform:** MAC (10.11.1) / Safari 9.0 

**RELEASE:** v0.13.5

**STEPS TO REPRODUCE:**
1) Navigate to the URL : http://tools-stage.gapminderdev.org/tools/bubbles
2) Bubble Map Chart will be loaded.
3) Click any country check box in find
4) Now drag slider right left under the name of countries 

**ACTUAL RESULTS:**
The slider ball blinks when user drag the slider right left 

**EXPECTED RESULTS:**
The slider ball should not blink when user drag the slider right left 

**SCREENSHOT:**

![29-3-4](https://cloud.githubusercontent.com/assets/9950837/14107888/eb40fd0c-f5d3-11e5-97f5-ee7b9d1f1408.png)

**Comment by sergey-filipenko** [comment]
Can not reproduce. Retest please.

**Comment by angieskazka** [comment]
can't reproduce (any longer)
