### ISSUE TITLE
Trails are taking too much time to be loaded in new tab 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1629]
**SEVERITY:**  Minor

**MODULE:**   Bubble chart

**Platform:**
*   Windows 7 / Firefox 44.0
*   Windows 7 / Chrome 49.0

**RELEASE:** v0.13.6

**STEPS TO REPRODUCE:** 
1)	Navigate to the URL : http://tools-stage.gapminderdev.org/tools/
2)	Bubble Map Chart will be loaded.
3)	Select USA and China
4)	Click play and drag the slider to the end(2015)
5)	Trails of selected bubbles will be available
6)	Copy URL and paste it in new tab
7)	Observe the behavior of trails for selected countries

**ACTUAL RESULTS:**
Trails are taking too much time to be loaded in new tab 

**EXPECTED RESULTS:**
Trails should be available instantly after loading the page 

**.gif file is attached for more details**
http://g.recordit.co/qSAs1u6WnS.gif

**Comment by angieskazka** [comment]
![8uact7uooc](https://cloud.githubusercontent.com/assets/3648190/14353482/8e0d905c-fcd9-11e5-845f-eafe8cecd76c.gif)

if this is what you mean, this behavior is expected. before that we would need to wait much longer time but trail would appear all at once in the end

**Comment by angieskazka** [comment]
Ola complains: Expecting a trail but see only start and end bubble. "I get two dots. Also after waiting"

I tried on my mobile, and can see what Ola is pointing to. Since the trail goes around the same point for a while it looks like it's only two bubbles. 

> How can we make it better? There is still a possible optimisation: process the data for selected bubbles first. This would visibly speed up the process

**Comment by angieskazka** [comment]
@olarosling 

I find the slow drawing of the trail to be very distracting. Especially if the purpose of the link is that the user should look at the final graph. And also,  there is no notion of the time playing when the little worm keeps moving. It's just a strange line. I'd prefer to wait for it one more second. Or if it could render 25 years at a time, and show the load symbol until it's done. Please.

 I just loose track of the story when I see an undefined thing moving, which I 't must wait to complete, and I forgot  why...
