### ISSUE TITLE
The X-axis line disappeared when user checks the presentation check box   

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1635]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Windows 7 / FireFox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools
2) Bubble chart will be loaded 
3) Click on present 
4) Click on present check box 
5) Observe the x-axis line 

**ACTUAL RESULTS:**
The X-axis line disappeared when user checks the presentation check box   

**EXPECTED RESULTS:**
The X-axis should not disappeared 

**SCREENSHOT:**

![8 apr axis line](https://cloud.githubusercontent.com/assets/9950837/14383221/0f602592-fdad-11e5-9473-c5768773b1a1.png)

**Comment by sergey-filipenko** [comment]
hi @k6Labz. Please specify what resolution of bubblechart  x-axis disappeared?
