### ISSUE TITLE
Zoom in/out cursor flickers to pointer/zoom couple of times and only then zooms on Windows

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#1693]
http://static.gapminderdev.org/vizabi/develop/preview/

On windows, select zoom in/out cursor and click anywhere in the chart.

You will see the mouse cursor flicker to pointer and back to zoom a couple of times before the chart actually zooms.

Expected: no flickering and direct zooming.

**Comment by angieskazka** [comment]
fixed with new angular tools page
