### ISSUE TITLE
When min x/y is changed tiny bit, can't zoom out to 100% with zoom out tool

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#1694]
1. Change x/y domain in options to a little bit more than actual domain
2. try to zoom out to original domain
3. notice zoom doesn't work

or
1. go here
   http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html#_width:976&height:711&fullscreen:false&bodyC:null&resp-sect:true&info-sect:true&butt-sect:true&model_state_marker_axis/_x_zoomedMin:179
2. Try to zoom out, notice zoom out doesn't work, 100% does.

Expected, zoom out always can zoom out to original domain (+ rangebump)

**Comment by angieskazka** [comment]
looks fixed to me (on stage and dev)
