### ISSUE TITLE
When user click on the X & Y and color icons are the respective options did not appear 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1707]
**SEVERITY:**  Major

**MODULE:** Bar Chart 

**PLATFORM:**
- Windows 7 / Firefox 44.0
- Windows 7 / Chrome 49.0
- Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/barchart.html
2) Bar Chart will be loaded 
3) Click on X and Y icon 
4) Click on color icon 

**ACTUAL RESULTS:**
When user clicks on X and Y or color icon the respective icons are not in working condition 

**EXPECTED RESULTS:**
When user clicks on icons the respective panels or options should appear

**SCREENSHOT**

![5 may bar chart](https://cloud.githubusercontent.com/assets/9950837/15043312/4b18097c-12e5-11e6-968b-c68e9d05b8d4.png)

**Comment by angieskazka** [comment]
@k6Labz we are not working on bar chart yet (and may start =)
