### ISSUE TITLE
The user is unable to select the indicator from X-axis options  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1708]
**SEVERITY:**  Major

**MODULE:** Bar Chart 

**PLATFORM:** 
- Windows 7 / Firefox 44.0
- Windows 7 / Chrome 49.0
- Windows 7 / Internet Explorer 11.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/barchart.html
2) Bar Chart will be loaded 
3) Click on X axis  
4) Click on indicator  

**ACTUAL RESULTS:**
When user clicks on the indicator the indicator did not get selected 

**EXPECTED RESULTS:**
The respective indicator should be selected 

**SCREENSHOT**

![5 may bar chart indicator](https://cloud.githubusercontent.com/assets/9950837/15043341/9f1abeac-12e5-11e6-9673-3730c8440271.png)

**Comment by angieskazka** [comment]
@k6Labz we are not working on bar chart yet (and may start =)
