### ISSUE TITLE
Label leashes need to be among the bubble z-layers

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#1714]
even after shifting the line layer in html 6b70a68e01d6b378584e4315678d36a8f2ad4c21 we have this:

select China, drag label, hover India

![image](https://cloud.githubusercontent.com/assets/3648190/15088100/d819d85e-13ef-11e6-8c67-251467cb2dd0.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2077

**Comment by angieskazka** [comment]
please also send the leash behind the owner bubble's trail

![image](https://cloud.githubusercontent.com/assets/3648190/19444337/5031dd20-9490-11e6-9e2b-72e696f8d183.png)

**Comment by angieskazka** [comment]
fixed in 718cdff73a961c3bc7f89d73588de53c0bb13768

thanks!
