### ISSUE TITLE
The bubble of countries hide behind the trails when user change the indicators from the size 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1761]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Firefox 44.0
* Windows 7 / Chrome 49.0
* Windows 7 / Internet Explorer 11

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview
2) Select x-axis indicator as Year Categorization 1950-
3) Select y-axis indicator as Year Categorization 1950-
4) Click on Pitcairn bubble 
5) Select y-axis indicator as Year Categorization 1950- from size dropdown 
6) Click on play to make trails 
7) Click china and united states check box from find countries list 
8) Observe the bubbles of other countries are behind the trails 
 
**NOTE:** The user is unable to generate the trails of other countries which are selected 

**ACTUAL RESULTS:**
The bubble of countries hide behind the trails when user change the indicators from the size 

**EXPECTED RESULTS:**
The bubble of countries should be visible in front of trails so user can select other countries bubbles too

**SCREENSHOT**

![17 may hiden bubles](https://cloud.githubusercontent.com/assets/9950837/15322232/ec5f9d5e-1c54-11e6-8762-88c4d69efa33.png)

**Comment by angieskazka** [comment]
@k6Labz can you reproduce it with anything else than year categorization? 
(which should be removed from the list)
