### ISSUE TITLE
Filtering the select list based on the alignment of entitites

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#1788]
We should be able to filter select list by telling the entities model to filter lists by a certain criteria.
For example: the click on the color category should instead filter the select list below. somehow. which has not yet been defined. but please think of it

**Comment by angieskazka** [comment]
Jasper did it in 986286af5fc81f28bd39fe24f478f3b1c25c2501

**Comment by jheeffer** [comment]
Hahaha, kind of.
