### ISSUE TITLE
Tooltip size should also increase after enabling “Present icon”

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1790]
**SEVERITY:**  Minor

**MODULE:**   Bubble chart

**Platform:**
- Windows 7 / Chrome 52.0
- Windows 7 / Firefox 42.0
- MAC 10 / Safari 9
- MAC 10 / Safari 9

**RELEASE:** v0.13.11

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL : http://178.62.135.203:8081/tools
2)  Bubble Chart will be loaded.
3)  Click on any bubble
4)  Tooltip is displayed of selected country
5)  Click on “Present icon”
6)  Note that tooltip has no effect after enabling “Present icon”

**ACTUAL RESULTS:**
Tooltip has no effect after enabling “Present icon”

**EXPECTED RESULTS:**
Tooltip size should also increase in bubble chart like in bubble map chart after enabling “Present icon” 

**SCREENSHOT:** 
![v0 13 11_ 08](https://cloud.githubusercontent.com/assets/9950837/15648812/5a09df64-2686-11e6-8153-22b90f7d26b8.png)

**Comment by kuguarpwnz** [comment]
@k6Labz tested on dev, tooltip size increases

**Comment by angieskazka** [comment]
@kuguarpwnz not for me (this issue is about hover tooltip, not the select label)

![wugvbqjww5](https://cloud.githubusercontent.com/assets/3648190/26540549/31d74c08-4452-11e7-81f2-591f4bf0c1f4.gif)
