### ISSUE TITLE
When user swipe up and down over the chart the values of axis overlapped 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1793]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Samsung S6

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Swipe the finger up and down over the chart area
3) Observe the axis values 

**ACTUAL RESULTS:**
The axis values overlaps when user swipe the finger up and down 

**EXPECTED RESULTS:**
The axis values should not overlaps the line 

**SCREENSHOT:**

![screenshot_20160531-113813](https://cloud.githubusercontent.com/assets/9950837/15672717/c173454e-274b-11e6-93b4-6e445aaafff9.png)

**Comment by angieskazka** [comment]
not relevant anymore
