### ISSUE TITLE
Zoom options should be disabled for the devices as there is no mouse wheel to scroll 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1794]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Samsung S6

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on options 
3) Click on zoom

**Comment by angieskazka** [comment]
1) zoom options are deep in settings so it doesn't matter much
2) i could perfectly use zoom-in, zoom-out and 100% on my Nexus 5 (along with touch as well)
