### ISSUE TITLE
hovering is not perfect in mountain chart

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#1802]
And in this chart, I can only hover US, Nigeria and China is unhoverable if I point in the chart directly (I can change hover them only if I point their lables on the left) 

http://www.gapminder.org/tools/mountain#_ui_chart_manualSortingEnabled:false;;&state_entities_select@_geo=usa;&_geo=chn;&_geo=nga;;&opacitySelectDim=0.00;&marker_stack_which=none

**Comment by jheeffer** [comment]
When I click that link, China is not hoverable at all and there's a ghost india which only pops up when I hover over it...

http://recordit.co/SltQBqc3xT
