### ISSUE TITLE
URL persistency: sorting of bubbles

### ISSUE THREAD

**Issue by TValeriy** [vizabi/vizabi#1820]
# Description 

**Summary:** URL persist ency issue as when user  done some clicks and load the URL in new tab the results are different

**SEVERITY:**  Major

**MODULE:**
* Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
*Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on color dropdown 
3) Select GDP / Capita
4) Click on size drop down
5) Select Economy -> Sector -> Services
6) Click Suriname country bubble 
7) Make trails 
8) Copy URL and paste in to new tab 

**ACTUAL RESULTS:**
The bubble positioning is different in both tabs 

**EXPECTED RESULTS:**
The bubble positioning should be same in both tabs as both tabs have same URL 

**SCREENSHOT:**

![part 1 url](https://cloud.githubusercontent.com/assets/9950837/15890847/0893f730-2d8b-11e6-9f22-d04209a73609.png)

![part 2](https://cloud.githubusercontent.com/assets/9950837/15890861/1dc7f9ee-2d8b-11e6-8ac3-6ea495d69212.png)

# Other information 
Reported by: Abid Ali 

Test configuration: Firefox, Desktop PC 

Test case number: TC34 

Test run: [https://valorsoftware.testlodge.com/projects/15827/runs/212511?tab=2&run_section_id=210469&executed_case_id=10043888#executed_case_10043888](https://valorsoftware.testlodge.com/projects/15827/runs/212511?tab=2&run_section_id=210469&executed_case_id=10043888#executed_case_10043888)

**Comment by k6Labz** [comment]
Still reproducible

**Comment by angieskazka** [comment]
likely fixed with 00e4b857dbaf334baf1713847279542607e608ec

**Comment by angieskazka** [comment]
@sergey-filipenko 
reopening this: when you start the app India is sometimes in front of smaller bubbles then it jumps back after the data is loaded. Should be behind from the start

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2085

**Comment by angieskazka** [comment]
it helped, thanks
