### ISSUE TITLE
Trail lines appear chaotically when changing the axis limits during play

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1833]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools/
2) Click on any bubbles 
3) Click play icon and let the trails generate 
4) Click on options 
5) Click on X and Y 
6) Change X axis minimum value and maximum value again and again
7) Don’t stop the trails while change the axis values 

**ACTUAL RESULTS:**
The dotted lines appear on the chart when user change the axis values during the making of trails 

**EXPECTED RESULTS:**
The dotted lines should not appear on the chart 

**SCREENSHOT:**

![14-jun dotted lines](https://cloud.githubusercontent.com/assets/9950837/16039263/31274cf4-3242-11e6-9ded-d9bcfdd65d11.png)

**Comment by angieskazka** [comment]
@sergey-filipenko i think the issue hides in trail redraw. please check and make trails protected from zoom, drag and changing axis limits while playing

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/1928
