### ISSUE TITLE
The label values gets overlapped when user tries to increase the label size

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1841]
**Summary:** The label values gets overlapped when user tries to increase the label size

**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** Windows 7 / Chrome 49.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://www.gapminder.org/tools/ 
2) Click on bubble so that label appear
3) Click on options 
4) Click on label 
5) Click label dropdown and Select Economy-> Debt Trade-> Trade Balance
6) Drag the slider towards the most right and observe the values 

**ACTUAL RESULTS:**
The label value over laps when user tries to increase the size of label 

**EXPECTED RESULTS:**
The values of the label size should not overlap each other 

**SCREENSHOT:**

![16 jun overlap](https://cloud.githubusercontent.com/assets/9950837/16106904/054acab8-33b2-11e6-90f1-242ee71f2c13.png)

**Comment by angieskazka** [comment]
this is a corner case with very little significance

if you want all fonts to be large you have constant and no overlap
if you want to diff font size by a variable you want to have one small and one large, so no overlap too

if you set it to variable and make both numbers big then you are just weird

don't want to fix this )
