### ISSUE TITLE
Vizabi data diagnostics and validation messages that would help to debug data

### ISSUE THREAD

**Issue by buchslava** [vizabi/vizabi#1865]
Understandable error information for Vizabi Framework is expected. Now this functionality is missing. I mean cases when we trying to integrate Gapminder Offline/Gapminder Tools with new Vizabi version or new Vizabi chart. In case of an error we can’t understand kind of the error: Vizabi internal error, Vizabi request error, data error… ‘Vizabi request error’ case is more important than two others because it kills a lot of time for error reason detecting.

**Comment by buchslava** [comment]
for example I have a valid (on the face of it) solution, but when I try to change axis I have an error.

![screenshot from 2016-06-22 16 46 45](https://cloud.githubusercontent.com/assets/6974213/16269048/77fedcd4-3899-11e6-8cba-db40d776837f.png)

**Comment by buchslava** [comment]
but in this case I don't understand when I'm wrong (or Vizabi options was changed, or something else) or is it Vizabi's bug?

![screenshot from 2016-06-22 16 46 53](https://cloud.githubusercontent.com/assets/6974213/16269111/ac372f92-3899-11e6-8007-f771470b3b1c.png)

**Comment by buchslava** [comment]
by the way, you can download new `gapminder offline` here:

https://s3-eu-west-1.amazonaws.com/gapminder-offline/0.15.0-20/GapminderOffline-win32.zip
https://s3-eu-west-1.amazonaws.com/gapminder-offline/0.15.0-20/GapminderOffline-darwin.zip
https://s3-eu-west-1.amazonaws.com/gapminder-offline/0.15.0-20/GapminderOffline-linux.zip

**Comment by angieskazka** [comment]
yes, this is important
@buchslava i've added a diagnostic message for this particular case:

`if(!indicatorsDB[pointer]) utils.error("Concept properties of " + pointer + " are missing from the set, or the set is empty. Put a breakpoint here and check what you have in indicatorsDB");`

please find more cases that are common and need diagnostic info

**Comment by angieskazka** [comment]
@kuguarpwnz made some progress on this
