### ISSUE TITLE
The color values overlap each other 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1871]
**SEVERITY:**  Minor

**MODULE:** Bubble Map

**PLATFORM:** Windows 7 / Chrome 49.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html
2) Click on color
3) Click on Child Mortality Rate
4) Click on color again and select linear option 

**ACTUAL RESULTS:**
The color values gets overlapped 

**EXPECTED RESULTS:**
Color values should not get overlapped

**SCREENSHOT:**

![29 june overlap](https://cloud.githubusercontent.com/assets/9950837/16448026/ca11641e-3e08-11e6-8ac1-68563bcecfe9.png)

**Comment by sergey-filipenko** [comment]
@k6Labz Can not reproduce now. Please retest

**Comment by angieskazka** [comment]
@k6Labz Can not reproduce. Please retest
