### ISSUE TITLE
The bubble gets disappeared when changing the indicator during play 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1887]
**SEVERITY:**  Major

**MODULE:**
* Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
*Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on play 
3) Click on size 
4) Select -> Environment -> Water ->Internal Renewable water

**ACTUAL RESULTS:**
The bubble gets disappeared 

**EXPECTED RESULTS:**
The bubble should not get disappeared 

**SCREENSHOT:**

![bubble disappear](https://cloud.githubusercontent.com/assets/9950837/17399822/d90da088-5a5d-11e6-8856-88a2ccc44f12.png)

**Comment by dab2000** [comment]
fixed with #1907
