### ISSUE TITLE
When user resize the window the content gets overlapped 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1888]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:**
 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0  
* Internet Explorer 11

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Resize the window 

**ACTUAL RESULTS:**
The content gets overlapped when user resize the window 

**EXPECTED RESULTS:**
The content should not get overlapped 

**SCREENSHOT:**

![8-4-2016 11-24-08 am](https://cloud.githubusercontent.com/assets/9950837/17400216/20684bde-5a60-11e6-9eb2-45f63c04ddfa.png)

**Comment by dab2000** [comment]
content.styl:101 replace:
margin-right 100px

header.styl: 28 add:
+for_breakpoint(medium)
bottom: 14px
font-size: 16px
