### ISSUE TITLE
The slider year value and y-axis value overlaps 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1889]
**SEVERITY:**  Major

**MODULE:**
* Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 49.0
* Windows 7 / Firefox 44.0  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on size 
3) Select health -> injuries and accidents -> poisoning and death 
4) Click on y axis value 
5) Select health-> HIV->  people live with HIV 
6) Click on zoom in button 
7) Click on 100% button 

**ACTUAL RESULTS:**
The y axis values overlaps and the value of year slider also overlaps 

**EXPECTED RESULTS:**
The axis values should not get disturb

**SCREENSHOT:**

![ui isssue](https://cloud.githubusercontent.com/assets/9950837/17401207/be7d53b4-5a65-11e6-9988-980f5b9c0815.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/1915

**Comment by angieskazka** [comment]
the Y values got fixed by the #1915. please ignore the minor slider year overlapping
