### ISSUE TITLE
When user hover the world map color the bubbles of those color did not get hovered

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1892]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Mac 10.11 / Safari 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Hover the world map regions individually  

**ACTUAL RESULTS:**
When user hover the world map color the bubbles of those color did not get hovered

**EXPECTED RESULTS:**
The bubbles should get hovered

**Comment by plward11** [comment]
I cannot reproduce on the same platform.

**Comment by angieskazka** [comment]
cannot either

**Comment by k6Labz** [comment]
Fixed
