### ISSUE TITLE
The opacity of bubble did not get decreased  or increased 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1893]
**SEVERITY:**  Major

**MODULE:**
* Bubble Chart 

**PLATFORM:** 
* Mac 10.11 / Safari 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on options 
3) Click on opacity 
4) Drag the slider to increase or decrease the opacity 

**ACTUAL RESULTS:**
The opacity of bubble did not get decreased or increased 

**EXPECTED RESULTS:**
The opacity should bubbles should increase or decrease according to the opacity bar

**Comment by plward11** [comment]
I cannot reproduce on the same platform and browser. Both opacity sliders work as expected.

**Comment by k6Labz** [comment]
Fixed
