### ISSUE TITLE
The selected bubble got unselected after changing the indicator 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1908]
**SEVERITY:**  Major

**MODULE:**
* Bubble Chart 
* Bubble Map

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click the bubbles to select it e.g. India
3) Click on x axis and select child mortality rate
4) Observe the bubble did not get unselected 
5) Click on x axis again
6) Now select Infrastructure -> Water -> Improved water source, urban 

**ACTUAL RESULTS:**
The bubble gets unselected during changing the indicators 

**EXPECTED RESULTS:**
The bubble should remain selected if it is still present in the chart 

**SCREENSHOT:**

![ok1](https://cloud.githubusercontent.com/assets/9950837/17548960/9eee2860-5f07-11e6-91f3-97401ba55452.png)

![ok2](https://cloud.githubusercontent.com/assets/9950837/17548965/a4a22e78-5f07-11e6-880a-a92736b57fe4.png)

**Comment by angieskazka** [comment]
Fixed in #1887
