### ISSUE TITLE
The charts gets loading and loading instead of successfully open the page

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1909]
**SEVERITY:**  Major

**MODULE:** Bubble Map

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Scroll down and Click on bubble map
3) Click on size drop down and select child mortality rate 
4) Click on color drop down and select child mortality rate 

**ACTUAL RESULTS:**
The page just gets loading and loading 

**EXPECTED RESULTS:**
The page should display appropriate results 

**SCREENSHOT:**
![loading](https://cloud.githubusercontent.com/assets/9950837/17554842/51e096a6-5f26-11e6-9a9d-7570a502e8da.png)

**Comment by angieskazka** [comment]
have different symptoms on this

![image](https://cloud.githubusercontent.com/assets/3648190/17839480/eed86956-67f1-11e6-9b76-d18033482e78.png)
