### ISSUE TITLE
When user increase the speed bar the speed of the slider becomes so fast that the years skipped  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1911]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on option
3) Click on speed 
4) Drag the slider to full right
5) Click the play slider 
6) Now load the mountain chart 
7) Click on speed 
8) Drag the slider to full right 
9) Click the play slider

**ACTUAL RESULTS:**
When user increase the speed bar the speed of the slider becomes so fast that the years skipped  

**EXPECTED RESULTS:**
The speed limit should be same for all charts 

**NOTE**
Speed limit should be same in all charts

**Comment by angieskazka** [comment]
this works as expected. when there is too much calculation the chart doesn't manage to act smoothly it stats skipping frames, first every second frame, then every 1,2,3 of 4 frames

i adjusted config a little in 52289e6d2627fc0f87c0c9bf06447f2ce24a43ba, but otherwise it's all good
