### ISSUE TITLE
Axis tick values shifted when in presentation mode

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#1918]
Likely the fix #1915 produced this new bug:

Open bubble chart. Enable presentation mode. Observe axis tick values displaced

![image](https://cloud.githubusercontent.com/assets/3648190/17773057/fd10294a-6554-11e6-93ea-0bffa6130767.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/1919

**Comment by angieskazka** [comment]
still an issue: X-axis values and hovered value in presentation mode
![image](https://cloud.githubusercontent.com/assets/3648190/17801369/5ceeac86-65f2-11e6-8887-d0f0f590e641.png)

bad spacing on y axis
![image](https://cloud.githubusercontent.com/assets/3648190/17801410/97d88290-65f2-11e6-80b5-5c842d54cda2.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/1926

**Comment by angieskazka** [comment]
yes
