### ISSUE TITLE
Blank chart for some indicator 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1920]
**SEVERITY:**  Major

**MODULE:** Bubble Chart

**PLATFORM:** 
- Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click on y-axis dropdown and select Health -> Maternal health -> Maternal death – lifetime risks 
3) Click on x axis dropdown and select Health -> cancer, female -> breast deaths total 

**ACTUAL RESULTS:**
Chart with no data available on selecting these two indicators 

**EXPECTED RESULTS:**
Chart with data should be available 

**SCREENSHOT:**

![8-19-2016 11-53-21 am](https://cloud.githubusercontent.com/assets/9950837/17808332/25f7287a-6629-11e6-9b47-689655fd4353.png)

**Comment by angieskazka** [comment]
this is an unlucky match, but it is correct. the two indicators don't have common time points
