### ISSUE TITLE
 When the page is idle for some time when the user tries to change indicator or want to perform operations he is unable to do  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1921]
**SEVERITY:**  Major

**MODULE:** Bubble Chart

**PLATFORM:** 
- Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Change some indicators
3) Leave the page idle for some minutes and switch to other tabs 
4) Now come to the old tab which is idle and perform some operation 

**ACTUAL RESULTS:**
When the page is idle for some time when the user tries to change indicator or want to perform operations he is unable to do  unless he refreshes the page 

**EXPECTED RESULTS:**
The page behavior should same even if the page is idle for some time 

**SCREENSHOT / GIF:**

http://g.recordit.co/U5brFfYRXy.gif

**Comment by kuguarpwnz** [comment]
Can't reproduce. How long should I wait?

**Comment by k6Labz** [comment]
For 10 mins

**Comment by kuguarpwnz** [comment]
@k6Labz still can't reproduce. is it happening all the time?

**Comment by angieskazka** [comment]
> abid [6:15 AM] 
> @angie
> https://github.com/vizabi/vizabi/issues/1921 is no more reproducible
