### ISSUE TITLE
The page starts loading and loading when user hover the color wheel  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1929]
**SEVERITY:**  Major

**MODULE:** Bubble Map

**PLATFORM:** 
* Windows 7 / Chrome 52.0
* Windows 7 / Firefox 45.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Scroll down and click on bubble map 
3) Click on color dropdown 
4) Select properties -> landlocked 
5) Click on coast line 
6) Hover on color wheel  

**ACTUAL RESULTS:**
The page starts loading when user hover the color wheel 

**EXPECTED RESULTS:**
On hovering the wheel the colors of bubbles should change to that color instead the page begins to start loading 

**SCREENSHOT:**

![8-23-2016 11-27-00 am](https://cloud.githubusercontent.com/assets/9950837/17882245/b0caf4ba-6924-11e6-9c38-42baf6294d55.png)

**Comment by angieskazka** [comment]
fixed on develop with this commit: https://github.com/Gapminder/gapminder-tools-vizabi/commit/29483a24b562c88dc14db15613c9eb322fe2f951

**Comment by k6Labz** [comment]
That issue was produced as the user hover the color wheel
