### ISSUE TITLE
The bubbles moved from their places 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1935]
**SEVERITY:**  Major

**MODULE:** Bubble Chart

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org
2) Click the x axis
3) Select Society -> War & peace -> Military expenditure
4) Click bubble then drag slider to the end to make trails 
5) Click on size 
6) Select health -> malaria -> malaria cases per 100000
7) Click on zoom in button 
8) Click 100% button
 

**ACTUAL RESULTS:**
The bubbles got moved from their actual positions 

**EXPECTED RESULTS:**
The bubble should not move from its actual positions

**Comment by angieskazka** [comment]
this is expected because the chart is zoomed by Y-axis (life expectancy)
the same will happen if you just start the page and click zoom 100%

please reopen if you mean something else @k6Labz
