### ISSUE TITLE
URL persistency

### ISSUE THREAD

**Issue by dab2000** [vizabi/vizabi#1944]
Load bubblechart on static.gapminderdev.org/vizabi/develop/preview/
select Macao
make trails 1826-1981.
http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html#_width:1166&height:623&fullscreen:false&bodyC=&resp-sect:true&info-sect:true&butt-sect:true&model_state_time_value=1981&endSelected=2004;&entities_select@_geo=mac&trailStartTime=1826;;;&marker_axis/_y_zoomedMin:16.17&zoomedMax:85;&axis/_x_zoomedMin:300&zoomedMax:150000

copy above url to new tab.

When new tab is loaded the new tab's url is:
http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html#_width:1166&height:623&fullscreen:false&bodyC:null&resp-sect:true&info-sect:true&butt-sect:true&model_state_entities_select@_geo=mac&trailStartTime=1826;;;&marker_axis/_y_zoomedMin:16.17&zoomedMax:85;&axis/_x_zoomedMin:300&zoomedMax:150000

copy url from new tab to another tab. When another tab is loaded then Macao is not selected.

**Comment by sergey-filipenko** [comment]
@k6Labz please check

**Comment by angieskazka** [comment]
i couldn't reproduce it on the current develop. it probably got fixed

**Comment by jheeffer** [comment]
When I click the last link I don't see Macao selected?

**Comment by k6Labz** [comment]
working fine on my side too
