### ISSUE TITLE
The mouse pointer automatically converted in to zoom in pointer when the page is idle 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1946]
**SEVERITY:**  Minor

**MODULE:** Bubble Chart

**PLATFORM:** 
* Windows 7 / Internet Explorer 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
2) Enlarge the chart to full screen 
3) Click on bubble and make trails
4) Leave the page idol and switch to other tab
5) Return to the page after some time 
6) Observe the pointer changed to zoom in icon 

**ACTUAL RESULTS:**
The mouse pointer automatically converted in to zoom in pointer when the page is idle 

**EXPECTED RESULTS:**
Nothing should change even the page remains idol 

**SCREENSHOT:**

![img_2995](https://cloud.githubusercontent.com/assets/9950837/18124608/5cccc8c0-6f8c-11e6-94cd-583325ecde96.JPG)

**Comment by angieskazka** [comment]
i tested in the following way: have two tabs
hold Ctrl on one tab, drag a rectangle over bubbles, page zooms successfully
keep holding ctrl, switch to another tab
release ctrl
switch to the first tab
zoom-in cursor is stuck there
