### ISSUE TITLE
The slider got stuck during play 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1948]
**SEVERITY:**  Minor

**MODULE:** 
* Bubble chart 
* Bubble map 
* Donut Chart

**PLATFORM:** 
* Windows 7 / Internet Explorer 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
2) Click on play 
3) Observe the slider

**ACTUAL RESULTS:**
The slider got stuck during play

**EXPECTED RESULTS:**
The slider should play smoothly

**Comment by angieskazka** [comment]
can't reproduce. looks like it was fixed
