### ISSUE TITLE
When user hover the bubble from find countries the label did not get appeared over the bubble

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1950]
**SEVERITY:**  Major

**MODULE:** Bubble Map 

**PLATFORM:** Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html 
2) Hover the country name / checkbox listed in the side panel 

**ACTUAL RESULTS:**
When user hover the bubble from find countries the label did not get appeared over the bubble

**EXPECTED RESULTS:**
The label of the hovered bubble should appear when user hover the check box or country name from side panel 

**SCREENSHOT:**

![9-1-2016 2-38-27 pm](https://cloud.githubusercontent.com/assets/9950837/18163217/51b9e022-7053-11e6-9f21-d929fc6a109f.jpg)

**Comment by angieskazka** [comment]
wait, @jheeffer should it even be the case? 
you hover china, you see one bubble highlighted. you know you hovered china. 
looks fine for me

**Comment by angieskazka** [comment]
alright, guys, let's not do it :-P
just adds complication to the code without actually improving the experience that much
