### ISSUE TITLE
When user hover the bubble label the size dropdown changes to value 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1985]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html 
2) Click on china bubble 
3) Hover the label or bubble
4) Observe the change in size drop down 

**ACTUAL RESULTS:**
When user hover the bubble label the size drop down changes to value 

**EXPECTED RESULTS:**
The size drop down should show the indicator instead of value 

**SCREENSHOT:**

![9-15-2016 5-43-30 pm](https://cloud.githubusercontent.com/assets/9950837/18550531/ca9eba42-7b6d-11e6-83ce-9bc4953e0bd0.jpg)

**Comment by angieskazka** [comment]
it's connected to hovering the bubble. you also get the exact X and Y values
all good =)

**Comment by k6Labz** [comment]
As it was not in the previous versions
ok =)
