### ISSUE TITLE
Trails lines are broken if chart resized during playing

### ISSUE THREAD

**Issue by dab2000** [vizabi/vizabi#1994]
load bubblechart
select full layout
select some bubbles and make trails
start playing
resize chart to small layout
![image](https://cloud.githubusercontent.com/assets/3511460/18630479/1d20590c-7e97-11e6-8083-055bcd8cfa5a.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2010
