### ISSUE TITLE
Page freezes after changing indicators

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#1996]
1. Put a conditional breakpoint in marker.js, line 127.
condition: `!_this.cachedFrames[cachePath][time].axis_x`
![image](https://cloud.githubusercontent.com/assets/3648190/18983252/f3447782-86eb-11e6-8d8f-ef99f2a05302.png)

2. Change x-axis to co2 emissions
3. Change x-axis back to income
...
(keep switching x-axis back and forth, as the bug is not stable. suspect a racing condition?)
...
4. The page becomes unresponsive

![image](https://cloud.githubusercontent.com/assets/3648190/18630945/91c1e96a-7e6f-11e6-9234-0df7068a7793.png)

If you had a breakpoint you will stop there before the page would crash
axis_x will be undefined in all timeframes

![image](https://cloud.githubusercontent.com/assets/3648190/18983342/62e28f70-86ec-11e6-9f1f-6a21897dbcb8.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2036
