### ISSUE TITLE
Chart got disappeared when user change the X and y max value to 0 and did not appear after changing the value 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#1999]
**SEVERITY:**  Major

**MODULE:** Mountain Chart

**PLATFORM:** 
- Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools
2) Click on options
3) Click on X and Y options 
4) Input max field value as 0

**ACTUAL RESULTS:**
Chart got disappeared when user change the X and y max value to 0 and did not appear after changing the value 

**EXPECTED RESULTS:**
The chart should disappeared but when user revert the values the chart should appear on the page again 

**Screenshot:**

![9-20-2016 5-15-24 pm](https://cloud.githubusercontent.com/assets/9950837/18669872/85721d8c-7f56-11e6-9907-3fa5695b1c9d.jpg)

**Comment by angieskazka** [comment]
there is more: min-max do not appear on load

![image](https://cloud.githubusercontent.com/assets/3648190/19437257/daefb534-9474-11e6-854d-d676961c96ea.png)
