### ISSUE TITLE
The color wheel does not appear when user click on color

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2000]
**SEVERITY:**  Major

**MODULE:** Bubble Chart

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click on color dropdown 
3) Click on categorization -> Main religion 2008
4) Click on region radio button from Merge Mountains
5) Hover on mountain and observe the regions name

**ACTUAL RESULTS:**
The color wheel does not appear when user click on color

**EXPECTED RESULTS:**
The color wheel should appear when user click on color so he can change the color accordingly 

**SCREENSHOT:**
![9-21-2016 9-26-11 am](https://cloud.githubusercontent.com/assets/9950837/18697924/65da7fbc-7fdf-11e6-81ca-c8376be7de45.jpg)

**Comment by angieskazka** [comment]
it's disabled for the religions (but not for income groups for example)
and we don't yet have a good display if it's possible or not

contiunuation of this issue is here #1787

**Comment by k6Labz** [comment]
the color wheel does not appear for just "religion in 2008" indicator other wise it appears for all indicators in "categorization" option =)
