### ISSUE TITLE
When user select country from show option the remaining countries did not hide 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2002]
**SEVERITY:**  Major

**MODULE:** Mountain Chart

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools
2) Click on mountain chart
3) Click on show
4) Select country e.g. Afghanistan

**ACTUAL RESULTS:**
When user select country from show option the remaining countries did not hide 

**EXPECTED RESULTS:**
Only the selected country should visible and the remaining should hide

**SCREENSHOT:**
![9-21-2016 12-46-31 pm](https://cloud.githubusercontent.com/assets/9950837/18702180/f53db1be-7ff9-11e6-8f8b-24624a5eaf9d.jpg)

**Comment by angieskazka** [comment]
fixed by 52c9b52d80a98eb55cb69a0a8f620af01e10adeb
