### ISSUE TITLE
User is unable to deselect the countries which he selected in show list 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2003]
**SEVERITY:**  Major

**MODULE:** Mountain Chart

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Click on mountain chart
3) Click on show
4) Select countries e.g. Afghanistan,  Albania, Algeria etc.
5) Click on deselect 

**ACTUAL RESULTS:**
User is unable to deselect the countries which he selected in show list

**EXPECTED RESULTS:**
All countries check box should deselected after user click the deselect button

**SCREENSHOT:**

![1](https://cloud.githubusercontent.com/assets/9950837/18708334/c65843d6-8013-11e6-9397-b298e1318987.jpg)

![2](https://cloud.githubusercontent.com/assets/9950837/18708340/cd52079e-8013-11e6-93d5-41a946acca62.jpg)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2018
