### ISSUE TITLE
Bar rank chart content overlaps

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2009]
![9-22-2016 2-56-05 pm](https://cloud.githubusercontent.com/assets/9950837/18748191/8f1b15ba-80ea-11e6-803f-a8d0c7bb70e6.jpg)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2021

**Comment by angieskazka** [comment]
merged manually in adab1a8d01e3ac5184f3c54fb93ce9152e4bad8e
