### ISSUE TITLE
The color wheel default color change to the selected color 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2017]
**SEVERITY:**  Major

**MODULE:** Bubble Map 

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/bubblemap.html
2) Click on color drop down 
4) Select Categorization-> G77 and OECD countries
5) Click on G77 or OECD or others 
6) Choose color from color wheel 

**ACTUAL RESULTS:**
The color wheel default color change to the selected color 

**EXPECTED RESULTS:**
When user select the color of the wheel the default color of the wheel should not get changed 

**SCREENSHOT:**
![9-26-2016 10-27-30 am](https://cloud.githubusercontent.com/assets/9950837/18826504/1feb7e78-83e7-11e6-90f5-ca3f8c145968.jpg)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2019
