### ISSUE TITLE
User is unable to scroll down the options  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2020]
**SEVERITY:**  Major

**MODULE:** Bubble Map 

**PLATFORM:** 
* Samsung S6 / Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Tap on options 
4) Scroll down the options

**ACTUAL RESULTS:**
User is unable to scroll down the options  

**EXPECTED RESULTS:**
User should be able to scroll down the options 

**SCREENSHOT:**

![51fd6d9a2e19ad1a49e7d5ea87135dc0a916cd1cb1da907023 pimgpsh_fullsize_distr](https://cloud.githubusercontent.com/assets/9950837/18834623/650f0ba4-8410-11e6-945a-2910ac8ddd59.png)

**Comment by angieskazka** [comment]
Scrolling in Google chrome on Android is a well-known problem and it's there already for a year or so
https://productforums.google.com/forum/#!msg/chrome/XwpAs9SPYWE/fdU5t8j5Bg4J

Scrolling doesn't work on many other websites, it's not just vizabi
Scrolling works if you connect the debugger (behavior depends on observer like in particle physics)
Scrolling works if you reinstall chrome on android =/

**Comment by jheeffer** [comment]
Worked for me on Chrome 53, Android Nougat, Nexus 5x

**Comment by dab2000** [comment]
d3 suppress 'touchmove','dragstart','selectstart' on window on each touchstart and mousedown in drag or zoom behaviors 
https://github.com/d3/d3/blob/v3.5.17/src/event/drag.js#L11
https://github.com/d3/d3/blob/v3.5.17/src/behavior/zoom.js#L225
https://github.com/d3/d3/blob/v3.5.17/src/behavior/drag.js#L32
and cancel suppress on touchend or mouseup only.

1. Chrome on android generate mousedown if finger on screen more then ~500ms, but don't generate mouseup so touchmove has stayed suppress on window and scroll is broken.
2. Sometimes Chrome generate touchcancel instead touchend and touchmove has stayed suppress on window too. Touchcancel is supported in d3 4.x.x but not in 3.5.17.
https://bugs.chromium.org/p/chromium/issues/detail?id=260732
