### ISSUE TITLE
Disabling splash leads to error in label size slider

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2022]
1. In your local vizabi, load vizabi without splash screen (`model.data.splash: false`).
e.g. in `toolscript.jade`:
![image](https://cloud.githubusercontent.com/assets/1596071/18841905/95132a1c-8413-11e6-92d9-79d99e431cea.png)

2. Load Vizabi preview page
3. Go to options -> label and see slider showing double handles instead of single
![image](https://cloud.githubusercontent.com/assets/1596071/18841978/cc40a76c-8413-11e6-84e3-49ed6af868de.png)

Expected behaviour: 
![image](https://cloud.githubusercontent.com/assets/1596071/18841988/d7d24ef0-8413-11e6-92f1-eb9042eeeab0.png)

I tracked down that:
1. the ready function on sizeslider model doesn't fire on load
2. this is because there are no events linked to the sizeslider model at all while there should be
3. initially the events do get registered but somewhere I think they get reset again.

**Comment by jheeffer** [comment]
Possibly linked to https://github.com/vizabi/vizabi/issues/2023

**Comment by angieskazka** [comment]
👍
