### ISSUE TITLE
No splash & no preset domain leads to zoom not working on load

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2023]
Reproduce issue:
1. Config bubblechart to not use splash screen (data.splash: false)
2. Config bubblechart to not have any domains preset (no domainMin/Max in axis_x/y)
3. Config bubblechart to have zoom domains (zoomedMin/Max in axis_x/y)
4. See how after load the bubblechart is not zoomed in
5. Drag the graph
6. See how the bubblechart jumps to the correct zoomed domain

Expected behaviour:
The graph shows the correct zoomed domain right away after load.

Loading vizabi with preset domains makes expected behaviour to appear.

**Comment by jheeffer** [comment]
Possibly linked to https://github.com/vizabi/vizabi/issues/2022

**Comment by angieskazka** [comment]
@jasper please don't stop at those things in moving the options from vizabi-gapminder. yes there are bugs, but this one shouldn't block you. give it the domain if it wants to have one

**Comment by angieskazka** [comment]
retested: this now works as expected 👍
