### ISSUE TITLE
When user deselect the selected countries the deselect button did not disappear 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2029]
**SEVERITY:**  Major

**MODULE:** Mountain Chart

**PLATFORM:** 
* Windows 7 / Chrome 52.0

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/
2) Click on mountain chart 
3) Click on show 
4) Click any country check box 
5) Click on deselect button 

**ACTUAL RESULTS:**
When user deselect the selected countries the deselect button did not disappear 

**EXPECTED RESULTS:**
The deselect button should be disappeared

**SCREENSHOT:**
![9-29-2016 4-29-19 pm](https://cloud.githubusercontent.com/assets/9950837/18980734/b86e22ac-86f0-11e6-937e-7ebbf5e81984.jpg)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2031

**Comment by jheeffer** [comment]
https://github.com/vizabi/vizabi/commit/408c6f209724292a4c1fbff340a2f42105ac7ad9

update on fix
