### ISSUE TITLE
Splash and no domain set leads to unability to pan/zoom to full data

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2034]
1. Configure Vizabi to load with splash screen and no domains (i.e. set by data)
2. Notice how Vizabi's domain is set to splash screen data and not final data.
3. Move time slider and try to pan/zoom to see all bubbles.
4. Notice you cannot pan/zoom because of domain set.

Expected behaviour:
Vizabi's domain is set to limits of full data load. Possibly while keeping zoom on splash data limits to prevent jumping when full data comes in (@angieskazka, what do you think is expected)?

**Comment by angieskazka** [comment]
Retested it now and it works. the picture jumps, of course, but that's what you would expect without domains in config
