### ISSUE TITLE
Label always shows name, regardless of config

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2035]
1.Config vizabi with `label` hook
```js
label: {
  use: 'property',
  which: 'world_4region'
}
```
2.Notice how Vizabi model still has `which: 'name'` and is still showing name on labels

**Expected behaviour**
Vizabi shows world_4region as label

**Comment by jheeffer** [comment]
Bubblechart or label model defaults do not have any mention of `name`.

**Comment by sergey-filipenko** [comment]
@jheeffer when I change `vizabi-gapminder.js` is works as expected, which config did you mean?

**Comment by jheeffer** [comment]
I see, I found out my gulp broke so didn't update my files correctly.
