### ISSUE TITLE
Mountain chart always grouping by world_4region but it should be sync with color

### ISSUE THREAD

**Issue by TValeriy** [vizabi/vizabi#2044]
As @angieskazka said:
>there are separate data hooks for color and for grouping and they are not in sync. so it still groups by world_4region

So countries from different regions (using 6 regions) aren't properly grouped.

![selection_002](https://cloud.githubusercontent.com/assets/16382915/19073562/4b596fb2-8a44-11e6-89ee-bdd7f4bedbfb.png)

And while playing or dragging the slider there are only 4 colors.

![selection_003](https://cloud.githubusercontent.com/assets/16382915/19073602/89beb8c0-8a44-11e6-9f98-d8171e3b05db.png)

**Comment by angieskazka** [comment]
#2100
