### ISSUE TITLE
Trails is broken

### ISSUE THREAD

**Issue by dab2000** [vizabi/vizabi#2057]
load bubblechart on develop
select China and India
make trails 1800-2015

some trails missed
in addition:
select a few another bubbles and look how trails is switching

![image](https://cloud.githubusercontent.com/assets/3648190/19218591/40d49e3c-8dfe-11e6-8bbe-0cf6ace87d95.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2059
