### ISSUE TITLE
The bubble did not disappear when user clicks on the bubble after reducing the opacity 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2062]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Google Chrome 52

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools
2) Click on bubble china and united states 
3) Reduce the opacity to zero 
4) Select India from the check box
5) Click on India bubble 

**ACTUAL RESULTS:**
The bubble did not disappear when user clicks on India bubble 

**EXPECTED RESULTS:**
The bubble should disappear when user clicks on India bubble 

**SCREENSHOT / GIF**
http://g.recordit.co/uUHcwCuSeY.gif

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2063
