### ISSUE TITLE
After reducing the opacity no bubbles gets hovered unless those which are first selected and then deselected 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2064]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Google Chrome 52

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools
2) Click on bubble china and united states
3) Reduce the opacity to zero
4) Click on china bubble 
5) Move mouse on the chart no bubbles get hover 
6) Move mouse to the place where china bubble is located on the chart

**ACTUAL RESULTS:**
After reducing the opacity no bubbles gets hovered unless those which are first selected and then deselected

**EXPECTED RESULTS:**
After deselecting the bubble, the bubble should not appear when user hover that place 

**SCREENSHOT/GIF:**

http://g.recordit.co/mA94WEqLle.gif

**Comment by sergey-filipenko** [comment]
related to #2062
