### ISSUE TITLE
 Color wheel appears when user click on color bar from option menu while color wheel does not appear when user clicks the color bar from color drop down

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2065]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Windows 7 / Google Chrome 52

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Click on color drop down 
3) Select society -> Murder Total Deaths 
4) Click on color bar 
5) Click on options 
6) Click on color
7) Click on color bar 

**ACTUAL RESULTS:**
Color wheel appears when user click on color bar from option menu while color wheel does not appear when user clicks the color bar from color drop down  

**EXPECTED RESULTS:**
Color wheel behavior should be same on all places 

**SCREENSHOT:**
![10-13-2016 5-41-20 pm](https://cloud.githubusercontent.com/assets/9950837/19349769/3e56d3d2-916e-11e6-89dd-5e65c0f7bab5.jpg)

**Comment by sergey-filipenko** [comment]
Hi @k6Labz please see #1878

**Comment by angieskazka** [comment]
correct @sergey-filipenko! this is not a bug, it's a feature (changing the color is a more advanced option)
