### ISSUE TITLE
User is able to drag the canvas from zoom out button 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2066]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
- Windows 7 / Google Chrome 52

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Click on zoom in button to zoom the chart 
3) Click on zoom out button 
4) Hold the mouse button and drag the canvas 

**ACTUAL RESULTS:**
User is able to drag the canvas from zoom out button

**EXPECTED RESULTS:**
User should be unable to drag the canvas unless the pointer is selected 

**Note:**
After selecting zoom in button when user hold and drag the mouse and then release the chart zoom in but when same thing done for zoom out button nothing happen

**SCREENSHOT:**
http://g.recordit.co/QIzbuOJdeM.gif

**Comment by angieskazka** [comment]
i don't see why not

**Comment by angieskazka** [comment]
fixed in #2452
