### ISSUE TITLE
User is unable to just  drag the label but the whole page gets dragged 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2083]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
- iPad Air 2 / Safari 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools
2) Click on bubble 
3) Drag the label and place anywhere in the chart

**ACTUAL RESULTS:**
When user drag the label whole page moves accordingly

**EXPECTED RESULTS:**
Only the chart area should move instead of the whole chart

**Comment by Legionivo** [comment]
unable to reproduce on my Ipad mini 4

**Comment by k6Labz** [comment]
Fixed
