### ISSUE TITLE
Duplicate entry of indicator " income per person"

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2089]
![10-19-2016 4-50-07 pm](https://cloud.githubusercontent.com/assets/9950837/19517740/61abe82e-961c-11e6-908a-45447947893c.jpg)

**Comment by angieskazka** [comment]
this is corrent. we want indicators to appear in multiple places. 
like cost of school can appear both under economy and school

**Comment by k6Labz** [comment]
the indicator appear out side was selected not the one which is inside the main folder
