### ISSUE TITLE
getMinModel() should return diff between current and initial models, not between current and default models

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2098]
URL problem 1: https://github.com/vizabi/vizabi/issues/1338

URL problem 2: consider the following situation:  
> default model would have a certain config: color is constant
> page would overwrite that config: color now be world regions
> user would change color to constant
> refresh page: color is world regions!  

why? because when user sets color=constant this is equal to model defaults and is not returned by getMinModel() 

for the discussion: 
let’s define operation “+" as deep-extend (leaves are replaced)
let’s define operation “–" as diff between two models

`model config + tool config = default model`
`default model + page config = initial model`
`initial model + user actions = current model`

now we have:
`page config – (current model – default model) = url model`

we should have:
`current model – initial model = url model`

i took this expression
`page config – (current model – default model) = url model`
inserted “initial model” instead “default model”
decoded all elements from definitions above
opened brackets like in math
and i got... `– user actions = url model`

**Comment by jheeffer** [comment]
@dab2000 

I moved the diff between current and default to inside Vizabi, and keep the page config diff outside vizabi.
 
1. So defaults are handled by vizabi. 
2. Because of some hack palette shows back up in url if you request defaults right after instantiating vizabi

**Comment by dab2000** [comment]
@jheeffer 

diffObject(diffObject(current_model, default_model), page_model)
not equal
diffObject(current_model, deepExtend(default_model, page_model))

and we have again:
> default model would have a certain config: color is constant
> page would overwrite that config: color now be world regions
> user would change color to constant
> refresh page: color is world regions!

**Comment by jheeffer** [comment]
in the case we have
page_model: world_4region
default_model: null
current_model: null
url_model: diff(diff(current_model, default_model), page_model)
diff(diff(null, null), world_4region))
diff

**Comment by jheeffer** [comment]
Now, we want it to be as easy as possible for an external programmer to update the URL, that's why I wanted to keep as much as possible inside Vizabi. But without breaking the rule that Vizabi doesn't know anything about an URL (e.g. `location` object). 

What would you propose to make the API easier @dab2000 ?

**Comment by dab2000** [comment]
we can add to Tool:
(sketch)
getPersistentChangesFromModel(model) {
minModel = getMinModel;
defModel = getDefaultModel;
return diffObject(minModel, deepExtend(defModel, model));
}

and external programmer call only one func to get URL model.
and may be no need send getMinModel then persistentChange is triggered

**Comment by jheeffer** [comment]
Okay, I added commit https://github.com/vizabi/vizabi/commit/fdfba2f4aa8a12f7896ba6cdcb1ed477b4c88345

This is now the code of external page needed for URL persistency. It could be even smaller, but I think then Vizabi would start to know what happens outside it.

```
var page_model = {
	...
}

var url_model = decodeURIComponent(location.hash)

var init_model = Vizabi.utils.deepExtend(config, url_model);

var viz = Vizabi('bubbleChart', init_model);

viz.on('persistentChange', function() {
	location.hash = encodeURIComponent(viz.getPersistentMinimalModel(page_model));
})
```

**Comment by jheeffer** [comment]
@angieskazka when merging make sure to update tools page
