### ISSUE TITLE
Mountain did not get hovered when user change the stack 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2100]
**SEVERITY:**  Major

**MODULE:** Mountain Chart 

**PLATFORM:** 
* Windows 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Click on mountain
3) Click on color drop down 
4) Select categories -> Main religion 2008 
5) Click on option and then stack 
6) Select region radio button from merge mountains
7) Hover the colors in color drop down 

**ACTUAL RESULTS:**
Mountain did not get hovered when user change the stack 

**EXPECTED RESULTS:**
Mountain should get hovered on selected color 

**SCREENSHOT:**
![10-24-2016 5-14-45 pm](https://cloud.githubusercontent.com/assets/9950837/19645340/a274aab8-9a0d-11e6-8e5a-0ce4d91e7a7e.jpg)

**Comment by angieskazka** [comment]
related to #2044

**Comment by angieskazka** [comment]
#2101
