### ISSUE TITLE
Try to build trails iteratively

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2104]
is it possible to change the default order of interpolating values?
Now this 1800, 1801, 1802 ... 2014, 2015
let's do this: 1800, 1900, 2000, 1850, 1950, 1825, 1875, 1925, 1975, 1812 ...

rounding out each time to a whole unit of time (we had only "year" so far)
and including back the worm
the point is that the worm does not crawl, and appeared once on the entire length and then was refined iteratively

**Comment by angieskazka** [comment]
load this state:
http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html#_width:891&height:739&fullscreen:false&bodyC:null&resp-sect:true&info-sect:true&butt-sect:true&model_state_entities_select@_geo=rus&trailStartTime=1837;&_geo=syr&trailStartTime=1864;;;&marker_axis/_y_zoomedMin:19.52&zoomedMax:86.11

see the trails not building completely until i move the time slider

![image](https://cloud.githubusercontent.com/assets/3648190/20096755/a54ba5d0-a5ab-11e6-9ecf-723dac21bad8.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2160
