### ISSUE TITLE
Treemenu doesn't expand folders in rare occasion

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2116]
A user on getsatisfaction shared an error he had

https://getsatisfaction.com/gapminder/topics/expand-data-figures-option

![image](https://cloud.githubusercontent.com/assets/3648190/19775699/8aa604ac-9c71-11e6-8706-94127a655a2c.png)

We had a hangouts talk and he showed the error to us and we can confirm it is there.

He uses 
windows 10 x64
chrome 54

Bug does not appear on his internet explorer so it seems chrome specific
No errors in console
When disabling extensions error persists

Possibly his hover events aren't fire because of exotic input device? Or something totally different.

We have his contact details for further questions, possibly debugging over shared hangouts screen.

**Comment by dab2000** [comment]
@jheeffer, menu does not expand folders on mouse hover only? Folders are expanded on mouse click?

**Comment by angieskazka** [comment]
@dab2000 neither on hover nor on click

**Comment by angieskazka** [comment]
Chromium issue: Touchscreen detection isn't reliable on Windows:
https://bugs.chromium.org/p/chromium/issues/detail?id=467934
https://bugs.chromium.org/p/chromium/issues/detail?id=557565

![image](https://cloud.githubusercontent.com/assets/3648190/19946773/97a814a0-a145-11e6-98b6-b00a7938336f.png)

**Comment by angieskazka** [comment]
fixed with 5448f2431ca4594da9e0691e914947381f2edd5b
