### ISSUE TITLE
nodeJS v 6.* support

### ISSUE THREAD

**Issue by sergey-filipenko** [vizabi/vizabi#2124]
nodeJs 6.7.0
BuilsJS Error when run gulp

**Comment by dab2000** [comment]
for remove:
(node:18319) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.

exec:
npm uninstall gulp
npm install gulp

**Comment by angieskazka** [comment]
thanks =)
