### ISSUE TITLE
URL issue still persist 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2129]
**SEVERITY:**  Major

**MODULE:** Bubble Chart 

**PLATFORM:** 
* Win 7/ Google Chrome  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Click on size drop down 
3) Select Environment -> Geography -> Surface area 
4) Copy the URL and paste it in new tab 
5) Compare the charts and bubbles positions 

**NOTE**
The small bubbles hide behind the big bubbles when user change the indicator

**ACTUAL RESULTS:**
URL issue still persist

**EXPECTED RESULTS:**
Same chart should be loaded in both tabs 

**SCREENSHOT / GIF:**

http://g.recordit.co/44rkkel7iN.gif

**Comment by angieskazka** [comment]
this is because of incorrect sorting of bubbles and will come together with #1820 soon
