### ISSUE TITLE
When X is showing time, and i switch Y to a less time-available indicator, then time start and end change accordingly but X scale doesn't

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2130]
usually we kill the scale and rebuild it when an indicator changes
but we assume this change is independent so we don't do it across indicators

**Comment by k6Labz** [comment]
Time indicator is not showing appropriate results for X and Y-axis

**Comment by angieskazka** [comment]
4f38cd486cd8764a9ecf06ed2575f4b5f38fa409
