### ISSUE TITLE
 After selecting time indicator from color when user refreshes the page the bubbles and mountains turned to black 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2131]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart 
•	Bubble Map
•	Mountain Chart

**PLATFORM:** 
* Windows 7 / Google Chrome  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click on color dropdown 
3) Click on time
4) Refresh the page now  

**ACTUAL RESULTS:**
Color of bubbles changed to black 

**EXPECTED RESULTS:**
The color of bubbles should same after refreshing the page 

**SCREENSHOT:**
![11-1-2016 3-19-57 pm](https://cloud.githubusercontent.com/assets/9950837/19886828/ee8347f4-a046-11e6-8efe-245e17b4aa64.jpg)

**Comment by sergey-filipenko** [comment]
@k6Labz can not reproduce on develop

**Comment by k6Labz** [comment]
@sergey-filipenko its reproducible on stage

**Comment by sergey-filipenko** [comment]
@k6Labz It was yesterday on stage, but not reproduce today

**Comment by k6Labz** [comment]
no its not reproducible any more
