### ISSUE TITLE
The radio button gets disabled when user change them

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2133]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain Chart

**PLATFORM:** 
* Windows 7 / Google Chrome  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click on mountain chart 
3) Click on by colors
4) Click on world (merge mountain)
5) Click on by colors (merge mountain )
6) Click on world 

**ACTUAL RESULTS:**
The radio button gets disabled when user change them

**EXPECTED RESULTS:**
The radio button should not get disabled 

**SCREENSHOT:**
![11-2-2016 3-44-34 pm](https://cloud.githubusercontent.com/assets/9950837/19929883/7720030a-a127-11e6-8dbf-8650ec40899a.jpg)

**Comment by k6Labz** [comment]
This issue was once raised before already

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2138
