### ISSUE TITLE
The trails appear and disappear when user clicks on the trails button 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2146]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart 

**PLATFORM:** 
* Windows 7 / Google Chrome  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/ 
2) Click on Y-axis
3) Select Economy -> Aid given -> Aid given
4) Click on X-axis 
5) Select Education -> Achievement -> Math Achievement 4th grade
6) Click on size 
7) Select Energy -> Pump price for gasoline 
8) Click on china bubble 
9) Drag the slider to make trails 
10) Click on trails button 
11) Now click on trails button again

**ACTUAL RESULTS:**
The trails appear and disappeared when user clicks on trails button 

**EXPECTED RESULTS:**
Behavior should be same for all indicators  

**SCREENSHOT:**

http://recordit.co/h8N7jNCxuz

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2162

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2163
