### ISSUE TITLE
 The user redirect to another chart when a delayed model change of a hidden chart happens

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2154]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain Chart
•	Bubble Map

**PLATFORM:** 
* Windows 7 / Google Chrome  

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/ 
2) Click mountain chart
3) Click on none radio button in stack  
4) Click on show button 
5) Click on Abkhazia check box 
6) Click Abkhazia check box from find countries list 
7) Click on play button 
8) Scroll down and click on bubble map 
9) Click on Abkhazia check box from find countries list

**ACTUAL RESULTS:**
The user redirect to mountain chart when user select the country from find country list 

**EXPECTED RESULTS:**
The user should stay on the bubble map

**Comment by angieskazka** [comment]
how to reproduce: 
scroll time to, like, half the slider, press play, switch to a different chart, wait 10 seconds. When playing on the first chart reaches the end we are redirected away

**Comment by vvpanchenko** [comment]
Fixed, check it on Dev
http://tools-dev.gapminderdev.org/tools/
