### ISSUE TITLE
Incorrect "Size" semicircle on Nexus 7

### ISSUE THREAD

**Issue by ghost** [vizabi/vizabi#2164]
This issue is hard to reproduce. It's unstable.
Was caught on real device.
I don't have steps to reproduce it.

![screenshot_20161115-163715](https://cloud.githubusercontent.com/assets/16382915/20309790/11dc6508-ab52-11e6-9ca4-46395032c829.png)

**Comment by angieskazka** [comment]
@kuguarpwnz 
the expected behavior is to have two arcs without any fill: 

![zp0mniigax](https://cloud.githubusercontent.com/assets/3648190/26504189/d217909e-4243-11e7-804e-c0172d9367d9.gif)

**Comment by angieskazka** [comment]
`stroke-linejoin: round;` was the problem :)

https://stackoverflow.com/questions/4234176/svg-polyline-with-stroke-linejoinround-not-showing-a-rounded-corner
