### ISSUE TITLE
Trail won't draw properly when switching indicators

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2165]
observing strange effects when switching indicators: 
select a bubble, make a trail, switch Y axis to CO2 or babies per woman or something else
the trail is building for a previous bubbles positioning while all the other bubbles moved to the new domain and zoom

![image](https://cloud.githubusercontent.com/assets/3648190/20320098/f00ab03c-ab70-11e6-9023-31860507067b.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2169
