### ISSUE TITLE
Win10/Edge: Fullscreen mode isn't working.

### ISSUE THREAD

**Issue by TValeriy** [vizabi/vizabi#2170]
http://tools-stage.gapminderdev.org/tools/

**STR:**
1. Load Bubble chart.
2. Click [options] button and click it again so that "options" dialog disappear.
3. Click to [expand] button.

![screenshot 2016-11-17 12 00 59](https://cloud.githubusercontent.com/assets/16382915/20384789/b56c18aa-acbd-11e6-9039-3f50783147fd.png)

**Comment by angieskazka** [comment]
possible source of problem:

buttonlist.js: 580 `this.root.layout.resizeHandler();`
Cannot read property 'resizeHandler' of undefined(…)

**Comment by jheeffer** [comment]
Working for me. 

Seems dab fixed this? https://github.com/vizabi/vizabi/blame/develop/src/components/buttonlist/buttonlist.js#L582

**Comment by angieskazka** [comment]
fixed in https://github.com/Gapminder/gapminder-tools-vizabi/commit/c162a3ec3d9c3011008e274932f72ca2ae33d9e6
