### ISSUE TITLE
The charts bubbles gets broken when user make the trails and drag the bubbles 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2180]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Map

**PLATFORM:** 
* Windows 7 / Firefox

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://178.62.135.203:3001/tools 
2) Hover bubble and observe the value overlap on y-axis
3) Click on bubble and play trails   

**ACTUAL RESULTS:**
The charts bubbles gets broken when user make the trails and drag the bubbles 

**EXPECTED RESULTS:**
The bubbles should not get broken while dragging 

![11-7-2016 6-16-55 pm](https://cloud.githubusercontent.com/assets/9950837/20473195/c6cab02c-afe0-11e6-8080-e179c94ee822.jpg)

**Comment by dab2000** [comment]
#2179
