### ISSUE TITLE
Tools page: switch language, time slider greys out (still works though)

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2186]
Expected: time slider should not grey out 

![iizv6tfku9](https://cloud.githubusercontent.com/assets/3648190/20494109/c3853992-b01b-11e6-9a5a-79cb29cd644e.gif)

**Comment by jheeffer** [comment]
Hmm, that could be some loading/ready thing

**Comment by k6Labz** [comment]
@angieskazka  the grey slider caused of other factors too like zoom in with scrolling as well

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2203

**Comment by angieskazka** [comment]
time.startSelected, endSelected are never persistent
we only store them in state because need to listen to them in time slider

external page may set them to null, which is incorrect
on tools page controller.js: 395

Vizabi.utils.deepExtend(updatedModel, $scope.vizabiModel[chartType], urlVizabiModel, langModel);

$scope.vizabiModel
has null's (probably keeps them from the defaults) which doesn't make sense
