### ISSUE TITLE
Bar rank chart breaks

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2199]
jasper
found the solution for barrankchart, it was what I thought it would be. We're just very lucky that every single time entities models are initialized before hooks in building the model tree. If they're not: you get the problem as it was in barrankchart.
We need some after model-init phase where models can connect listeners to each other. Probably your color syncmodels could fit in there too.
same is needed for making hooks listen to changes in locale.id (for updating translated data)

**Comment by jheeffer** [comment]
Fixed by https://github.com/vizabi/vizabi/commit/560f1817a0f01818eb49e5424eb87e98dc5e11ff
