### ISSUE TITLE
After changing the speed the slider gets stuck 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2208]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain Chart 

**PLATFORM:** 
* Windows 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools/ 
2) Click on bubble map 
3) Click on option and then speed 
4) Drag the speed and minimize the speed
5) Click play 

**ACTUAL RESULTS:**
The slider is stuck when user reduces the speed bar

**EXPECTED RESULTS:**
The play slider should not get stuck when user reduces the speed bar

**SCREENSHOT:**

![11-28-2016 2-19-49 pm](https://cloud.githubusercontent.com/assets/9950837/20662826/f2445604-b576-11e6-8e18-a28f84d64d76.jpg)

**Comment by angieskazka** [comment]
likely connected to #2186
