### ISSUE TITLE
Different behavior of bubble Map

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2209]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Map

**PLATFORM:** 
* Windows 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Click on bubble map 
3) Click on Chanel Island from the find country list 

**ACTUAL RESULT:**
Label appear but bubble did not appear 

4) Refresh the page 
5) Select Christmas Island 
6) Drag the slider to 1950
7) Refresh the page again 
8) Play the slider 

**ACTUAL RESULT:** The slider stuck after a while 

9) Refresh the page again 

**ACTUAL RESULT:** The bubbles disappear 

**For Reference view the shared video on slack **

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2233
