### ISSUE TITLE
Make line chart ready for production

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2216]
✅ let “Time” bottom-align with all axis-x labels
✅ add presentation mode button and style changes
✅ add data doubts component (top-right, there is space)
✅ reduce whitespace between time slider and the chart
  
click around and see that everything works:
* ✅ adding more countries? 
* ✅ changing X and Y axis limits in more options?
* ✅ changing Y to `life expectancy: male`? (restricted time domain)

✅ i set time slider to 1950 and press play. at 1969 it breaks --> seems to be fixed by 595a1f298353fc034a1f7b02384d295f42c21351 but please retest

✅ try removing temporary fix for change scaletype, it should work now
![image](https://cloud.githubusercontent.com/assets/3648190/20735920/97bf60ba-b6a3-11e6-9372-c865a1f4359e.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2234

**Comment by angieskazka** [comment]
❌ let “Time” bottom-align with all axis-x labels: 
still not properly aligned. see if you can make use of a different [Dominant Baseline Style](http://bl.ocks.org/eweitnauer/7325338)
❌ changing Y to life expectancy: male (restricted time domain): 
errors in console
🆕 add range bump on top and bottom, not very large, profile dependent

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2256

**Comment by angieskazka** [comment]
❌ if i'm fast enough to move time slider before the data is interpolated i get errors in console. updating the view needs a protection from a nonsense data, probably
