### ISSUE TITLE
The whole text gets overlapped and becomes more visible when user clicks the present button 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2218]
**SEVERITY:**  Major

**MODULE:** 
•	Line chart

**PLATFORM:** 
* Windows 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/linechart.html 
2) Click on present button 

**ACTUAL RESULTS:**
The whole text gets bold and more visible instead the text inside the chart 

**EXPECTED RESULTS:**
Only the text inside the chart should be visible bold when user clicks the presentation button 

**SCREENSHOT:**

![11-30-2016 9-54-07 am](https://cloud.githubusercontent.com/assets/9950837/20740537/ac09da72-b6e5-11e6-9a79-a70f858c2bd4.jpg)

**Comment by angieskazka** [comment]
probably needs a resize event to trigger axis redraw/recalculation

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2230
