### ISSUE TITLE
The user is unable to switch the X axis indicator 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2220]
**SEVERITY:**  Major

**MODULE:** 
•	Line chart

**PLATFORM:** 
* Windows 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/linechart.html 
2) Click on time adjacent to X-axis 

**ACTUAL RESULTS:**
The tree menu did not appear 

**EXPECTED RESULTS:**
The tree menu should appear although X-axis does not contain any indicator but the menu should appear on clicking with time indicator 

**SCREENSHOT:**

![11-30-2016 11-09-02 am](https://cloud.githubusercontent.com/assets/9950837/20741874/c5b67c4c-b6ee-11e6-9297-6b15bdbc135a.jpg)

**Comment by angieskazka** [comment]
that's by design. we only show functions of time
