### ISSUE TITLE
The find country list does not appear on the right side of the chart instead show countries list is given  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2221]
**SEVERITY:**  Major

**MODULE:** 
•	Line chart

**PLATFORM:** 
* Windows 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://static.gapminderdev.org/vizabi/develop/preview/linechart.html 
2) Observe the list of countries on right side 

**ACTUAL RESULTS:**
The show country list is displayed on the right side of the chart 

**EXPECTED RESULTS:**
The find country list should be given on the right side of the chart 

**SCREENSHOT:**

![11-30-2016 11-29-58 am](https://cloud.githubusercontent.com/assets/9950837/20742184/a74ec6ae-b6f0-11e6-93c0-9ad4769fc311.jpg)

**Comment by angieskazka** [comment]
this is correct for now, we want a show list instead of "find", but it has to be improved in the future because it's confusing. find and show lists will merge somehow
