### ISSUE TITLE
No deselect button appear on selecting some countries from show country list

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2222]
![11-30-2016 11-29-06 am](https://cloud.githubusercontent.com/assets/9950837/20742223/ca552918-b6f0-11e6-99bf-b327b1099cbd.jpg)

**Comment by angieskazka** [comment]
agree, it is a bug but it would be dangerous to have deselect so much visible. when pressed, it loads all lines and creates a mess =)
