### ISSUE TITLE
The slider stops to 2014 instead of 2015

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2226]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble chart

**PLATFORM:** 
* Windows 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools 
2) Click on play button 
3) Observe the year where the slider stops 

**ACTUAL RESULTS:**
The slider pause on 2014

**EXPECTED RESULTS:**
The slider should pause on 2015

**SCREENSHOT:**

![11-30-2016 4-03-40 pm](https://cloud.githubusercontent.com/assets/9950837/20750214/81fcea8a-b717-11e6-85f8-68f1eba1f332.jpg)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2232
