### ISSUE TITLE
marker.getFrame caching returns wrong value when dataId's don't change.

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2235]
1. Go to bubble chart.
2. Select GDP for y-axis

See that some bubbles are drawn very low.

Expected:
Bubbles are drawn in the correct location on axis.

Probable cause:
marker.getFrame has a cache. The cache-key uses hook._dataId. However, when changing y-axis to GDP, the dataId for axis_y doesn't change. Therefore, the cache kicks in, which returns old life expectancy data for axis_y. This happens because marker.getCachePath doesn't take into account `hook.which`.

**Comment by angieskazka** [comment]
🐾
