### ISSUE TITLE
Slider hides under the screen when user expand the chart in Arabic language 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2243]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart 

**PLATFORM:** 
* iPAD Air 2  / Safari 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Tap on menu and select Arabic language 
3) Click on expand button 

**ACTUAL RESULTS:**
Slider hides under the screen when user expand the chart in Arabic language  

**EXPECTED RESULTS:**
Slider should remain properly visible

**SCREENSHOT:**
![img_0714](https://cloud.githubusercontent.com/assets/9950837/20882303/0fe95ca0-bb02-11e6-8121-c4309aa5cb49.PNG)

**Comment by dab2000** [comment]
Cann't reproduce on Xcode simulator ipadair2 ios10.2 ios9.3. Looks like fixed

**Comment by k6Labz** [comment]
Fixed
