### ISSUE TITLE
RTL layout isn't always completely reset

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2249]
1. Visit http://www.gapminder.org/tools/
2. Switch to arabic
3. Click browser back button

**Result**
English language in partly RTL layout

**Expected result**
Complete reset to LTR layout

**Comment by k6Labz** [comment]
Browser Back button is not providing the proper results 
The user does not redirect to proper page when back button is clicked when chart is loaded in Arabic language
