### ISSUE TITLE
Entered zoom domain is not followed for small values

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2252]
1. Open any bubble chart (http://static.gapminderdev.org/vizabi/develop/preview/bubblechart.html)
2. Choose `central bank discount rate` on axis y (also works for other indicators though, this one has bubbles on low values)
3. Go to options -> x and y
4. Enter 200 for max axis y

See how axis doesn't respond

Or: 

4. Enter 100 for max axis y

See how axis resizes to 500 or 600.

![image](https://cloud.githubusercontent.com/assets/1596071/20934734/749047b0-bbdc-11e6-9f30-b8999af21f81.png)

Found this through this bug report:
https://getsatisfaction.com/gapminder/topics/adjusting-axis-limits-doesnt-work

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2257

**Comment by angieskazka** [comment]
#2352

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2403
