### ISSUE TITLE
Preview page: MS Edge has no dragging cursor

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2253]
In Microsoft Edge, the preview page doesn't have a dragging cursor when you hover on the bottom right corner of vizabi.

**Comment by jheeffer** [comment]
The .vzb-viewer:after constructed from `preview/assets/css/_viewer.scss`, line 10 is for some weird reason disabled in MS Edge.

![image](https://cloud.githubusercontent.com/assets/1596071/21051971/f68b2f12-be22-11e6-9430-97e02b681149.png)

Haven't found a way on how to enable it.

**Comment by angieskazka** [comment]
ie/edge cannot set cursor on ::after and ::before
http://stackoverflow.com/questions/26426734/cursorpointer-on-pseudo-element-ie

we decided to not fix it
