### ISSUE TITLE
The color wheel does not appear 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2265]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart 

**PLATFORM:** 
* Windows 7  / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-dev.gapminderdev.org/tools  
2) Click on color dropdown 
3) Select Life expectancy  
4) Click on option 
5) Click color 
6) Click on color bar to appear color wheel 

**ACTUAL RESULTS:**
The color wheel does not appear on the chart 

**EXPECTED RESULTS:**
The color wheel should appear so user can change the color

**SCREENSHOT:**

![12-13-2016 3-54-45 pm](https://cloud.githubusercontent.com/assets/9950837/21137937/a35b3250-c14d-11e6-818b-c155f78b3635.jpg)

**Comment by dab2000** [comment]
#2281
