### ISSUE TITLE
Scrolling fails and there is no vertical space between the chart thumbnails

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2266]
**SEVERITY:**  High

**MODULE:** 
•	Bubble Chart 

**PLATFORM:** 
* iPad Air 2 / Safari 
* Mac / Chrome

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-dev.gapminderdev.org/tools  

**ACTUAL RESULTS:**
The content is truncated. Page doesn't scroll
There is no vertical space between the chart thumbnails

**EXPECTED RESULTS:**
The page should scroll to cover the content

**SCREENSHOT:**

![img_6685](https://cloud.githubusercontent.com/assets/9950837/21139858/c3e8aea4-c156-11e6-917a-1787f2d1ed6a.PNG)

**Comment by vvpanchenko** [comment]
Fix available on Dev
