### ISSUE TITLE
Firefox shows warning about unresponsive script

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2268]
Issue is related to Bubbles chart.

Steps to reproduce:
1. Load Bubble chart in Firefox browser(50.0.2).

Actual result: 
Browser shows warning:
 
```
A script on this page may be busy, or it may have stopped responding. You can stop the script now, open the script in the debugger, or let the script continue.
Script: https://www.gapminder.org/components/vizabi-tools-53d602.js:38
```

Expected result: 
Page loaded without warnings.

**Comment by angieskazka** [comment]
@Legionivo thanks! where are you seeing this? http://www.gapminder.org/tools/ here?

**Comment by Legionivo** [comment]
@angieskazka yes

**Comment by kuguarpwnz** [comment]
@angieskazka just tried it with `51.0.1 (64-bit)` ff, no errors

**Comment by Legionivo** [comment]
@kuguarpwnz it's old issue, I haven't seen it for a long time.
