### ISSUE TITLE
Support "folder" in DataModel

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2270]
TreeMenu should read `folder` property in DataModel and use it to decide where indicators from a datasource will be located in the treemenu.

When folder is present, the indicators from the datasource are shown in a folder on root level.

```  
  "data": {
    "reader": "csv",
    "path": "foo.csv",
    "folder": "Foo folder"
  }
```

When folder is absent, the indicators from the datasource are shown loaded on root level (and possibly merged with other indicators from other datasources on root level).

```
  "data": {
    "reader": "csv",
    "path": "foo.csv"
  }
```

When there is a conflict between two datasources (they both define the same folders), indicators are merged, regardless of if one datasource starts on root and the other has its own folder.

```  
  "data": {
    "reader": "csv",
    "path": "foo.csv",
    "folder": "Foo folder"
  }
  "data_2": {
    "reader": "csv",
    "path": "foo.csv"
  }
And data_2 contains "Foo folder" in tags.
```

**Comment by angieskazka** [comment]
@jheeffer i took a slightly different approach

when there is no tag information, the concepts from a data source end up in a folder on root level
the name of that folder is not set by the user (to have it less complicated), but is requested from reader

reader should be able to return the name of the dataset and version (we also need this for the "about" section under more options, to see what data we are currently running with

ddf and ws readers don't have it implemented yet, but one has datapackage.json to read it from, and another one has WS, which returns name of the dataset and version in every response

i implemented getting a name of the dataset from csv reader, it's just a file name

![image](https://cloud.githubusercontent.com/assets/3648190/21306607/275918c8-c5d2-11e6-9d57-c78f20cd7be8.png)

**Comment by jheeffer** [comment]
Ok, how could you do what you did for Liav? Merge csv on root?

**Comment by angieskazka** [comment]
@jheeffer this was a single ddf dataset, some indicators from SG plus one about migrants. The added indicator was featured in concepts with tag "_root", a description, etc

**Comment by jheeffer** [comment]
ok, so same question without "what you did for Liav"? 

How would you merge csv on root?

**Comment by angieskazka** [comment]
i wouldn't, because, first, it's not bad to have them in a folder
second, csv comes with its own geo and time concepts that i wouldn't want to have in the root

i'd suggest we leave it like it is for now and revisit later. there is certainly room for improvement with merging
