### ISSUE TITLE
The mountain sifted below the axis line 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2271]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain Chart 

**PLATFORM:** 
* Windows 7  / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click on mountain chart  
3) Click on play to move slider to 1803
4) Click on show
5) Click on Afghanistan 

**ACTUAL RESULTS:**
The mountain sifted below the axis line 

**EXPECTED RESULTS:**
The mountain should remain on the axis line 

**SCREENSHOT:**

![12-15-2016 10-54-33 am](https://cloud.githubusercontent.com/assets/9950837/21214760/9e5b5786-c2be-11e6-9150-0e637c08b44e.jpg)

**Comment by kuguarpwnz** [comment]
I'm not sure why it happens. Bug appears randomly when you refresh page. Also it seems like this bug depends on `yScale.range()` and `yScale.domain()` (not sure). So when we have `[0, ...]` domain on last change chart is correct.
![screenshot from 2016-12-27 14-15-36](https://cloud.githubusercontent.com/assets/6388788/21501725/fc1db27c-cc52-11e6-96ff-fdf8aadf692c.png)
![screenshot from 2016-12-27 14-15-14](https://cloud.githubusercontent.com/assets/6388788/21501733/081a572e-cc53-11e6-9c4e-1505200220b4.png)
