### ISSUE TITLE
Add property (name) to color legend indicator picker on marker hover.

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2274]
Current situation:

![image](https://cloud.githubusercontent.com/assets/1596071/21232500/1dfb09a0-c2ec-11e6-81a2-1c95dc800ab9.png)

Proposal: Instead of "No data" show "Europe" in indicator picker button.

**Comment by angieskazka** [comment]
@jheeffer it's a bug, but how did you produce it? for me the selector keeps saying "color", not the "new data"

**Comment by jheeffer** [comment]
Uwh... maybe it's my changes in selection/highlight that caused this. I didn't expect it to be so assumed it was standard behaviour. Can't reproduce on `develop`. 
Nonetheless, would this be interesting?

**Comment by angieskazka** [comment]
At first i thought no, because we have minimap... But sometimes we have large lists of properties, so you may be right

**Comment by jheeffer** [comment]
Plus on minimap the name of the geo area is not given (only on hover over minimap with a cursor-title, not on hover over bubble for example).

**Comment by angieskazka** [comment]
4c775b2f9d9c6f1981a86da2275cb2ea19d077ec
