### ISSUE TITLE
line chart: Ending dot is missing for china and Angola lines

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2293]
**SEVERITY:**  Major

**MODULE:** 
•	Line Chart

**PLATFORM:** 
* Windows 7  / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click on line chart 
3) Click on Angola 
4) Click on y axis 
5) Select Education -> Schooling cost -> Expenditure per student, territory

**ACTUAL RESULTS:**
No knot for Angola and china line trail

**EXPECTED RESULTS:**
Th Angola and china trials should be proper instead of a line

**SCREENSHOT:**

![12-19-2016 3-21-36 pm](https://cloud.githubusercontent.com/assets/9950837/21309585/b4cdba78-c600-11e6-97a7-4e93db578401.jpg)

**Comment by angieskazka** [comment]
this is kind of correct judging by the bubble chart showing the same indicator
but it looks strange, yes

![image](https://cloud.githubusercontent.com/assets/3648190/21309893/5e8b2abc-c5e0-11e6-809c-8965d488a2e1.png)

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2311
