### ISSUE TITLE
Mountainchart: sometimes mountain starts below x-axis

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2294]
1. Visit http://static.gapminderdev.org/vizabi/develop/preview/mountainchart.html#_width:623&height:724&fullscreen:false&bodyC:null&resp-sect:true&butt-sect:true&info-sect:true&model_state_time_value=1992;&entities_show_geo_$in@=afg&=alb;;;;&marker_group_manualSorting@=asia&=africa&=americas&=europe

2. See how mountain starts below x-axis

![image](https://cloud.githubusercontent.com/assets/1596071/21309795/fc14beb6-c5df-11e6-8f1f-b24b21ed51bc.png)

Expected:
Mountains always starts on x-axis.

Doesn't always happen. Haven't found out the exact logic when this happens, I have up until now only seen it on medium size profile and with some countries shown.

**Comment by angieskazka** [comment]
@jheeffer duplicate of #2271?

**Comment by jheeffer** [comment]
Most likely, sorry, don't keep track of all issues :D
