### ISSUE TITLE
Large profile with no sidebar: size/color indicator text absent

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2300]
With a minimal config, without any sidebar.

Medium profile:
![image](https://cloud.githubusercontent.com/assets/1596071/21332593/c51c6ee4-c649-11e6-8dc5-c3edf5123832.png)

Large profile:
![image](https://cloud.githubusercontent.com/assets/1596071/21332609/e16f2406-c649-11e6-93eb-3588218e99ae.png)

Result: In large profile the size and color indicator texts on the right are absent.
Expected: In large profile, when no sidebar is available, size and color indicator texts are shown on the right as in medium and small profile.

Tools:
Bubble Chart (size & color)
Bubble Map (color)
Line Chart (color is missing in all profiles (!))
Bar Rank (color is missing in all profiles (!))

**Comment by angieskazka** [comment]
@jheeffer this is correct. you didn't supply configuration about buttons and dialogs. See you have no buttons either. You ended up in a minimalistic embed-into-blogpost case

**Comment by jheeffer** [comment]
@angieskazka I'm talking about the text, not the dialogues.

![image](https://cloud.githubusercontent.com/assets/1596071/21345257/c4d217da-c69f-11e6-9cd0-1315d079b54d.png)

**Comment by jheeffer** [comment]
@angieskazka 

Pictures were for bubble chart, but same problem is on other charts too:

Tools:
Bubble Chart (size & color)
Bubble Map (color)
Line Chart (color is missing in all profiles (!))
Bar Rank (color is missing in all profiles (!))

**Comment by angieskazka** [comment]
i don't think it's really that important for any chart. can even be removed from bubble chart =)
