### ISSUE TITLE
Mountain chart play animates slower when "stack" is set to none

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2305]
**Steps to reproduce:**

1. Navigate to URL : http://178.62.135.203:3001/tools/
2. Click on mountain chart 
3. Click on none from stack 
4. Select speed to maximum 
3. Click on play slider 

**Actual Result:** 
The slider speed on changing stack is different 
On none its slower on world its faster

**Comment by kuguarpwnz** [comment]
@angieskazka we update each mountain here https://github.com/vizabi/vizabi/blob/develop/src/tools/mountainchart/mountainchart-component.js#L1035-L1039 do you have idea how we can optimize this?

**Comment by angieskazka** [comment]
this is an issue about performance of the mountain chart

@kuguarpwnz and me were searching ways to optimise it but we haven't found any. there are just too many shapes that want to be redrawn
