### ISSUE TITLE
The Nigeria shifted to mountain top 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2306]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain Chart

**PLATFORM:** 
* Windows 7  / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click on mountain chart 
3) Click on color dropdown
4) Select Categorization-> Main religion 2008
5) Select Life expectancy from color drop down 

**ACTUAL RESULTS:**
The Nigeria shifted to top on mountain top

**EXPECTED RESULTS:**
The Nigeria should remain on its actual position 

**SCREENSHOT:**

![12-21-2016 3-16-44 pm](https://cloud.githubusercontent.com/assets/9950837/21386453/aeb79772-c794-11e6-9fc3-3831cd12319f.jpg)

**Comment by kuguarpwnz** [comment]
@k6Labz can't reproduce

**Comment by angieskazka** [comment]
i think this was solved by now
