### ISSUE TITLE
Line chart: X and Y axis values are missing 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2308]
![12-22-2016 2-29-09 pm](https://cloud.githubusercontent.com/assets/9950837/21421491/10fb3f2c-c855-11e6-8cf8-4c38a072e686.jpg)

**Comment by jheeffer** [comment]
These are normally filled with domain/zoom min/max. But these are null now since user hasn't set them... Is this a bad thing?

**Comment by angieskazka** [comment]
@jheeffer yes, they should be filled with something, having empty fields doesn't make sense

**Comment by angieskazka** [comment]
if looking into domain and domain in state is null, then display domain from hook.scale.domain()
if looking into zoom and zoom in state is null, then display domain from hook.scale.domain()
