### ISSUE TITLE
The doted lines on chart got contracted 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2309]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart

**PLATFORM:** 
* Windows 7  / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click on options and select speed to maximum  
3) Click on play 
4) Click on y axis select any indicator (during play) 

**ACTUAL RESULTS:**
The doted lines on chart got contracted

**EXPECTED RESULTS:**
The line on charts should not contract 

![12-22-2016 5-36-01 pm](https://cloud.githubusercontent.com/assets/9950837/21426838/f2279366-c872-11e6-9515-715056d4a164.jpg)

**Comment by angieskazka** [comment]
@k6Labz [this is expected](https://www.google.se/search?q=log+scale&tbm=isch&tbo=u&source=univ&sa=X&ved=0ahUKEwiC-ZXen4jRAhXHkiwKHSflAe0QsAQIRw&biw=1440&bih=826)
