### ISSUE TITLE
The arabic translation of extreme poverty is overlapped

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2315]
The arabic translation of extreme poverty also overlapped

![12-26-2016 10-05-13 am](https://cloud.githubusercontent.com/assets/9950837/21475928/0742f162-cb54-11e6-8721-6df440c46672.jpg)

**Comment by angieskazka** [comment]
Mountain Chart is not visible on tools page - fixed

**Comment by angieskazka** [comment]
Mountain Chart is not visible on tools page - fixed
