### ISSUE TITLE
Long text doesn't fit select list

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2322]
![12-28-2016 2-38-33 pm](https://cloud.githubusercontent.com/assets/9950837/21519149/d4aff492-cd0c-11e6-9449-c8aaf4b38e3f.jpg)

**Comment by angieskazka** [comment]
Tooltip is a nice solution. It works in Safari, but not in Chrome, IE, Edge

![image](https://cloud.githubusercontent.com/assets/3648190/26462637/e131a05a-4181-11e7-8f0f-432f8dd8de94.png)

![image](https://cloud.githubusercontent.com/assets/3648190/26462648/ea9952fa-4181-11e7-9e2c-66ad64ca4275.png)
