### ISSUE TITLE
User is unable to load URL in new tab 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2325]
**MODULE:**
Bubble Chart

**STEPS TO REPRODUCE:**

1. Navigate to URL: http://tools-stage.gapminderdev.org/tools/
2. Select Co2 per capita from X and Y axis 
3. Select Co2 per capita from color drop down 
4. Select Co2 per capita from size 
5. Copy URL and paste in new tab and press enter

http://tools-stage.gapminderdev.org/tools/#_state_time_value=1925;&marker_select@_geo=usa&trailStartTime=1800&labelOffset@:0.667&:-0.278;;&_geo=bgr&trailStartTime=1925;;&opacitySelectDim=0.43&opacityRegular=0.67&axis_slash__x_which=co2_slash__emissions_slash__tonnes_slash__per_slash__person&domainMin:null&domainMax:null&zoomedMin:null&zoomedMax:null&scaleType=linear&dataSource_reader=waffle&path=https_slash_:_slash__slash__slash__slash_waffle-server-stage.gapminderdev.org_slash__slash_api_slash__slash_ddf_slash__slash_&splash:true;;&axis_slash__y_which=co2_slash__emissions_slash__tonnes_slash__per_slash__person&domainMin:null&domainMax:null&zoomedMin:null&zoomedMax:null&scaleType=genericLog&dataSource_reader=waffle&path=https_slash_:_slash__slash__slash__slash_waffle-server-stage.gapminderdev.org_slash__slash_api_slash__slash_ddf_slash__slash_&splash:true;;&size_which=co2_slash__emissions_slash__tonnes_slash__per_slash__person&domainMin:null&domainMax:null&scaleType=genericLog&dataSource_reader=waffle&path=https_slash_:_slash__slash__slash__slash_waffle-server-stage.gapminderdev.org_slash__slash_api_slash__slash_ddf_slash__slash_&splash:true;;&color_which=co2_slash__emissions_slash__tonnes_slash__per_slash__person&use=indicator&scaleType=genericLog&dataSource_reader=waffle&path=https_slash_:_slash__slash__slash__slash_waffle-server-stage.gapminderdev.org_slash__slash_api_slash__slash_ddf_slash__slash_&splash:true;;;;&chart-type=bubbles

**Comment by angieskazka** [comment]
the issue can be reproduced if CO2 is just in color

http://tools-stage.gapminderdev.org/tools/#_state_marker_color_which=co2/_emissions/_tonnes/_per/_person&use=indicator;;;&chart-type=bubbles
