### ISSUE TITLE
The chart did not come to its original position when user select and deselect the countries from show list 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2327]
**Steps to Reproduce:**
1. Navigate to the link http://tools-stage.gapminderdev.org/tools
2. Click on show button 
3. Click on Afghanistan 
4. Click on Show All button 

**Actual Result:**
The countries on the find list get disabled and the mountain did not return to its original shape

![12-29-2016 12-07-04 pm](https://cloud.githubusercontent.com/assets/9950837/21538714/89a89976-cdc1-11e6-93c3-e330a6f7fd43.jpg)

**Comment by kuguarpwnz** [comment]
Can't reproduce
