### ISSUE TITLE
The application crashes  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2332]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Map

**PLATFORM:** 
* Windows 7  / Google Chrome 

**STEPS TO REPRODUCE:**
1) Navigate to the URL: http://tools-stage.gapminderdev.org/tools  
2) Click x axis 
3) Select Environment-> Forestry-> Biomass stock in forest  
4) Click on options 
5) Click on zoom and click on zoom with mouse wheel check box 
6) Now scroll the wheel up and down until the slider appears on the chart 
7) Click on play button 

**ACTUAL RESULTS:**
The bubbles on the chart disappeared 

**EXPECTED RESULTS:**
The bubble on the chart should not disappeared and the slider should also be disabled 

**SCREENSHOT:**

![12-30-2016 2-48-03 pm](https://cloud.githubusercontent.com/assets/9950837/21563007/3f3ec23c-ce9f-11e6-96a0-ec836c3867fb.jpg)

**Comment by angieskazka** [comment]
abid [12:59 PM] 
its ok on stage now


not sure what has fixed it. reopen if persists
