### ISSUE TITLE
When user switch the chart after the page remains idle he encountered problem in loading page 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2333]
![12-30-2016 3-52-31 pm](https://cloud.githubusercontent.com/assets/9950837/21563850/1d0c5ebe-cea8-11e6-9a4d-f7cd78fc3b35.jpg)

**Comment by kuguarpwnz** [comment]
@k6Labz i was waiting about 30+ min and then successfully switched to another chart. @angieskazka maybe it's related to data loading problems?
