### ISSUE TITLE
Mountain chart sorting issue

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2341]
**Steps To Reproduce:**
1. Navigate to link : http://tools-stage.gapminderdev.org/tools/
2. Click on mountain chart 
3. Click on Egypt
4. Move time slider to 1995
5. Copy link and paste in new tab

Egypt is sorted differently in the mountain stack

![1-2-2017 3-29-30 pm](https://cloud.githubusercontent.com/assets/9950837/21642073/c252f084-d2a1-11e6-8d8e-1d398ca4f344.png)
![1-2-2017 3-29-44 pm](https://cloud.githubusercontent.com/assets/9950837/21642074/c280fad8-d2a1-11e6-9489-83c2e6acc106.png)

**Comment by angieskazka** [comment]
fixed in https://github.com/vizabi/vizabi-mountainchart/commit/eed691c06e2479361d554ed19b80ac2a51a75125
