### ISSUE TITLE
On using time unit type as quarter, it throws formats.year is not a function error in the console.

### ISSUE THREAD

**Issue by vikash20186** [vizabi/vizabi#2344]
On using time unit type as quarter, it throws formats.year is not a function error in the console.

`var viz = Vizabi('BubbleChart', document.getElementById('bubbles-placeholder'), { 
	state: {
    time: {
      unit: "quarter",
    }
  },
  data: {
    reader: 'csv', 
    path: 'data.csv'
  }
});`

## data.csv file
"type","time","total_exp","total_income"
"Type1",2016q4,29311,1431,,
"Type2",2016q4,29311,1431,,
"Type11",2017q1,29311,1431,,
"Type21",2017q1,29211,1421,,

Any help to make it work would be highly appreciated. 
Thanks in advance

**Comment by jheeffer** [comment]
Hi vikash! Thanks for your message. We will look at this in a week or two probably!

**Comment by vikash20186** [comment]
@jheeffer I am able to resolve this by updating the quarterFormat function. replacing the commented line

`function quarterFormat() {

  var format = function format(d) {
    return d.getFullYear() + 'Q' + formatQuarter(d)
	
	//return formats['year'](d) + 'q' + formatQuarter(d);
  };

  format.parse = function (dateString) {
    var matchedDate = dateString.match(/^(\d{4})q(\d)$/);
    return matchedDate ? getDateFromQuarter(matchedDate[1], matchedDate[2]) : null;
  };

  var formatQuarter = function formatQuarter(d) {
    return (d.getUTCMonth() / 3 | 0) + 1;
  };

  var getDateFromQuarter = function getDateFromQuarter(p1, p2) {
    var quarter = parseInt(p2);
    var month = 3 * quarter - 2; // first month in quarter
    var year = p1;
    return new Date(year,month);
	//return formats['month'].parse([year, (month < 9 ? '0' : '') + month].join(''));
  };

  return format;
}`

Thanks,
Vikash

**Comment by angieskazka** [comment]
@vikash20186 thanks for your help! can you please retest it on develop and reopen this if it's still a problem? 
keep small letter "q" in values
