### ISSUE TITLE
The year behind the chart moving continuously when user play the slider 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2348]
![1-11-2017 2-41-27 pm](https://cloud.githubusercontent.com/assets/9950837/21843327/6bbcc374-d80c-11e6-99a2-5dfdd3efa84e.jpg)

**Comment by jheeffer** [comment]
Year still jumps at first movement, e.g. visit:

http://tools-dev.gapminderdev.org/tools/#_state_time_value=1873;;&chart-type=bubbles

and drag the timeslider, see how it jumps only once.

**Comment by jheeffer** [comment]
Also, with letters, faked monospace breaks typography:

![image](https://cloud.githubusercontent.com/assets/1596071/21925522/27537de0-d97e-11e6-974f-48d82aae580c.png)

**Comment by kuguarpwnz** [comment]
@jheeffer Agree. `BubbleChart-csv-month` looks really bad

**Comment by angieskazka** [comment]
agree, let's use a different font. anything similar to Bariol and available on every platform? 🤔

**Comment by kuguarpwnz** [comment]
https://www.myfonts.com/fonts/hgo/charifa-sans/

**Comment by angieskazka** [comment]
@kuguarpwnz there is a test-drive function on the page. this font is not monospace to digits either
![image](https://cloud.githubusercontent.com/assets/3648190/22409341/a13823ce-e688-11e6-85e4-58185f2a11bb.png)

let's include arial rounded MT bold in vizabi maybe, ignore font styling on year label and remove the artificial monospacing?

**Comment by kuguarpwnz** [comment]
@angieskazka **arial rounded MT bold** is not free

**Comment by angieskazka** [comment]
some websites offer it for free, some don't
we probably want a webfont or something
http://www.ampsoft.net/webdesign-l/WindowsMacFonts.html

and let's remove artificial monospacing functionality from dynamic-background
