### ISSUE TITLE
The bars are bolder on bar chart / year display is missing

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2356]
![1-13-2017 11-43-40 am](https://cloud.githubusercontent.com/assets/9950837/21920930/1f1ddd16-d986-11e6-817a-b6f506c1ac3f.jpg)

**Comment by kuguarpwnz** [comment]
@k6Labz what do you mean?

**Comment by k6Labz** [comment]
Compare the bar chart on live(production) and on stage 
There is no year appear on the chart on stage as well

**Comment by angieskazka** [comment]
we did actually make them bolder on large layout
fixing the year display now (forgot to add it in config)
