### ISSUE TITLE
Box zoom does not always go to defined box

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2359]
This is a hard one to catch, but I've seen a few times when using box zoom (drag) the zoom go to a wrong place... Haven't found a consistent way to replicate yet.

**Comment by angieskazka** [comment]
@jheeffer the zoom logic on the current DEV was massively updated with https://github.com/vizabi/vizabi/pull/2403
and we can hope that it solves this too

i can not reproduce now, please reopen this if you will encounter it again
