### ISSUE TITLE
LineChart: no data for line, shows line head on top

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2370]
1. Go to http://www.gapminder.org/tools/#_state_time_value=1886;&marker_axis_slash__y_which=co2_slash__emissions_slash__tonnes_slash__per_slash__person;;;&chart-type=linechart
2. See how two bubbles are on the top of the chart because there is no data for them

![image](https://cloud.githubusercontent.com/assets/1596071/22043118/d6090de6-dd16-11e6-834c-5e2b17d373c4.png)

**Comment by angieskazka** [comment]
seems like this has been fixed
