### ISSUE TITLE
The user is unable to hover the mountain as the other countries overlaps them 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2372]
**Steps To Reproduce:**
1. Navigate to URL: http://tools-stage.gapminderdev.org/tools/ 
2. Click on mountain chart 
3. Click on Afghanistan from find country 
4. Click on By colors radio button 
5. Hover the Afghanistan from mountain

**Actual Result:**
User is unable to hover Afghanistan 

**Expected Result:**
User should be able to hover the selected country 

![1-19-2017 2-27-30 pm](https://cloud.githubusercontent.com/assets/9950837/22101288/a57c6e22-de54-11e6-8b87-c81bbe514928.jpg)

**SCREENSHOT:**

**Comment by angieskazka** [comment]
this is not possible by design and no plans to fix it
