### ISSUE TITLE
The bars countries name did not get translated when user convert the chart to Arabic language 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2374]
![1-20-2017 4-48-54 pm](https://cloud.githubusercontent.com/assets/9950837/22148696/6cb4009a-df31-11e6-980a-4e415e9fe667.jpg)

**Comment by angieskazka** [comment]
after merge of #2438
switching to arabic on preview page made a long waiting time and then this picture

on tools page dev github.com/gapminder/ng2-tools-page still no arabic countries when switching language:
http://tools-dev.gapminderdev.org/tools/

if you start with arabic in state (switch and refresh), country names will be correct!
