### ISSUE TITLE
Inline Reader Example

### ISSUE THREAD

**Issue by vikash20186** [vizabi/vizabi#2376]
Hi All,

Sorry for asking question here. 
Is there any example on how to use inline reader? All the examples shows only CSV Reader only. 
there is no information on how to load static data using inline reader.

Any help would be deeply appreciated.

Thanks,
Vikash

**Comment by kuguarpwnz** [comment]
@vikash20186 Hi! You can use inline reader by specifying it in config. Also you need to provide data.

Example:
```
data: {
  reader: "inline",
  data: [
    {
      "geo": "world",
      "time": "1990",
      "GDP": "8780.9",
      "LEX": "65.76",
      "POP": "5858793283",
      "world_region": "world",
      "category": "global"
    },
   // ...
  ]
}
```

**Comment by angieskazka** [comment]
@vikash20186 please test if it works with the latest vizabi on develop and reopen the issue if it doesn't
