### ISSUE TITLE
The trails of the bubbles did not generated 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2383]
**Steps To Reproduce:**
1.Navigate to URL: http://tools-stage.gapminderdev.org/tools/
2. Single Click on mini map region 
3. Now click on same mini map region again
4. Click on any bubble and click play button 

**Actual Result:**
The trails of the bubbles did not generate on selecting bubble, User has to manually click the trail button 

**Expected Result:**
The trails icon should be selected on selected the bubble

**SCREENSHOT:**

![1-30-2017 2-28-09 pm](https://cloud.githubusercontent.com/assets/9950837/22418107/4c8212a6-e6f9-11e6-9e38-6476ba922b27.jpg)

**Comment by angieskazka** [comment]
yes, it disables trails to save performance slowdowns. it's not thought well through but let it stay until users complain
