### ISSUE TITLE
Query is changed after a call to reader 

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2385]
Guys! I've discovered one important issue with vizabi that violated gapminder offline 0.70.16. Angie do yop remember empty screen for bubble chart on mac?

Reason is next: reader get query before it constructed. I see next in ng2-vizabi:

```Reader for data source 'data' returned empty array for query: {
  "language": "en",
  "from": "datapoints",
  "animatable": "time",
  "select": {
    "key": [
      "geo",
      "time"
    ],
    "value": [
      "_default"
    ]
  },
  "where": {
    "$and": [
      {
        "geo": "$geo"
      }
    ]
  },
  "join": {
    "$geo": {
      "key": "geo",
      "where": {
        "is--country": true
      }
    }
  },
  "order_by": [
    "time"
  ]
}
```

but value was changed after call to reader

one attempt to fix it (unsuccessful) : 3c7a6578f067d3035fe398d2503b40ee07273880

**Comment by jheeffer** [comment]
I'm still waiting for a way to reproduce, does anyone know a (kind of) reliable way? @kuguarpwnz @buchslava @angieskazka ?

**Comment by angieskazka** [comment]
let's close it and reopen when we will be able to reproduce =)
