### ISSUE TITLE
Years get missed when user generate trails of bubbles 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2389]
**Platform:**
Win7 / Fire Fox

**Steps To Reproduce:**
1. Navigate to URL: http://tools-stage.gapminderdev.org/tools/
2. Click on bubbles China and United States
3. Click on play button 
4. Observe the years 

**SCRENSHOT:**
http://g.recordit.co/WFSTmFwX16.gif

**Comment by kuguarpwnz** [comment]
@k6Labz could you please check it here http://static.gapminderdev.org/preview/master/bubblechart.html?vizabi=fix/firefox-years-skipping ?

**Comment by Legionivo** [comment]
verified - fixed
