### ISSUE TITLE
The countries remain selected when user load the other chart 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2390]
**Platform:**
Win 7 / Google Chrome 

**Module:**
* Bubble Chart
* Bubble Map 
* Mountain Chart
* Line Chart
* Bar Chart

**Steps To Reproduce:**
1. Navigate to URL: http://tools-stage.gapminderdev.org/tools/
2. Click on China and USA bubble
3. Scroll down and click on Mountain Chart or Bubble Map 

**Actual Result:**
The countries remain highlighted which are selected from other chart 

**Expected Result:**
The chart should load from the beginning as a new chart

**Comment by angieskazka** [comment]
this is a new feature
