### ISSUE TITLE
Deselected geo doesn't disappear from url

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2398]
**MODULE:**
•	Bubble Map

**STEPS TO REPRODUCE:**

Navigate to the URL: https://www.gapminder.org/tools/#_chart-type=map
1. Select few countries by clicking them one by one.
2. Deselect countries in the same order. 

**ACTUAL RESULT:**
First selected country remains in URL( _geo=xxx).

**EXPECTED RESULT:**
All countries should disappear from URL

**Comment by kuguarpwnz** [comment]
#2378 duplication
