### ISSUE TITLE
No side options available on mountain chart 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2400]
![2-14-2017 3-03-51 pm](https://cloud.githubusercontent.com/assets/9950837/22924940/dabf58aa-f2c8-11e6-931f-3e134b057fba.jpg)

**Comment by angieskazka** [comment]
this was stage, lagging behind on vizabi version with the new config pattern, fixed now 
http://tools-stage.gapminderdev.org/tools/
