### ISSUE TITLE
Unwanted button on bubble chart 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2401]
![2-14-2017 3-22-54 pm](https://cloud.githubusercontent.com/assets/9950837/22925180/91c14734-f2c9-11e6-9f6a-a65fc58077ed.jpg)

**Comment by angieskazka** [comment]
this is wanted! Ola wants this

**Comment by k6Labz** [comment]
Fine as it controls the speed but the button looks very messy So could we make it more good and organised
