### ISSUE TITLE
When user tries to open the chart in new tab the chart reloads on the current page and also open in the new tab too

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2402]
**Steps To Reproduce:**

1. Navigate to the URL http://tools-stage.gapminderdev.org/tools/
2. Scroll down the chart 
3. Click on the chart by holding ctrl + left click

**Comment by rychkog** [comment]
This is fixed on http://tools-dev.gapminderdev.org/tools, please check

**Comment by Legionivo** [comment]
IE 11 - nok
Chrome - ok
Edge 14 - ok
Firefox - ok

**Comment by Legionivo** [comment]
IE 11 - ok
