### ISSUE TITLE
When user expands the chart the chart background turned into black 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2408]
Win7 / chrome
Mac / chrome

![black](https://cloud.githubusercontent.com/assets/9950837/22964760/0bb37ad2-f37c-11e6-95f9-441767b82193.jpg)

**Comment by Legionivo** [comment]
Linux / Chrome affected too

**Comment by dab2000** [comment]
need avoid to use css classes prefixed by 'vzb-' (internal vizabi prefix)  on outer html tags
https://github.com/Gapminder/ng2-tools-page/blob/master/src/app/home/home.component.html#L4
https://github.com/vizabi/ng2-vizabi/blob/master/demo/src/app/components/vizabi/bubble-chart-demo.html#L3
