### ISSUE TITLE
Make color legend click select and show features more user-friendly

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2413]
When user double click the mini map and again double click the mini map the chart did not get back to its default state

What happens is: 
double click 1: on the first click we _select_ America, on the second click we _show_ America
double click 2: we somehow _unshow_ America, but we don't _unselect_ it

![2-15-2017 4-01-50 pm](https://cloud.githubusercontent.com/assets/9950837/22971647/342537fa-f398-11e6-8cc9-7315f29c8e50.jpg)

**Comment by kuguarpwnz** [comment]
Can't reproduce

**Comment by angieskazka** [comment]
Solution: 
We need to make those clicks and double clicks more organised. Let's add a menu on click

Regular color pannel:
![image](https://cloud.githubusercontent.com/assets/3648190/26465007/febda0b2-4189-11e7-8d78-1a42fd764a8e.png)

On hover (that white thing is cursor:pointer, i know, sorry):
![image](https://cloud.githubusercontent.com/assets/3648190/26465031/0d3ebcd4-418a-11e7-8b2e-50e8f55fb77d.png)

On click
![image](https://cloud.githubusercontent.com/assets/3648190/26465067/27348ace-418a-11e7-8030-8eb635cde72c.png)

On click when the dialog is inside "more options" 
![image](https://cloud.githubusercontent.com/assets/3648190/26465083/3954716a-418a-11e7-8b61-109f9529e560.png)

(using css you can show/hide things depending if it's in more options or not)

The same should work for color categories without map (both the circle and the label):
![image](https://cloud.githubusercontent.com/assets/3648190/26465168/85462e38-418a-11e7-8b6d-1645f95748d0.png)
