### ISSUE TITLE
in landscape mode when user scroll down the bar chart, All countries did not show on chart 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2434]
**Platform:**
iPad Air 2

![img_0806](https://cloud.githubusercontent.com/assets/9950837/23151640/64527cdc-f81e-11e6-9772-c760f703aec4.PNG)

**Comment by angieskazka** [comment]
@kuguarpwnz let's introduce the minimum length of a bar
- bar size can not be shorter than 1-2-3 px (adjustable, depends on layout)
- please test on different indicators, where some bars go backwards or where all bars go backwards

**Comment by kuguarpwnz** [comment]
@angieskazka i think this issue is about cut countries that are below "Guam"

**Comment by angieskazka** [comment]
oh! this is strange... looks like similar resizing issue
