### ISSUE TITLE
Color option available on bubble map on devices but not available on desktop browsers 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2437]
**Platform:** iPad Air 2

![img_0810](https://cloud.githubusercontent.com/assets/9950837/23163040/b04ed4d0-f852-11e6-95c5-5c198065efab.PNG)

**Comment by angieskazka** [comment]
This is correct. Desktop browsers allow for a larger screen, thus we can put a proper color legend into the side bar
