### ISSUE TITLE
Keep language when switching between charts on tools page

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2445]
**Platform:** Win7 / Google Chrome

**Steps To Reproduce:**
1. Navigate to URL: http://tools-stage.gapminderdev.org/tools/
2. Click on language and select Arabic 
3. Scroll down and Click on Chart 

**Actual Result:**
The chart loaded in English language although user already selected the Arabic Language 

**Expected Result:**
The chart should load in the already selected language

**Comment by rychkog** [comment]
@k6Labz Please, check on http://tools-stage.gapminderdev.org/tools/

**Comment by Legionivo** [comment]
verified - fixed

**Comment by angieskazka** [comment]
yes! now i like it better
