### ISSUE TITLE
Tooltip for .data-tooltip is displaying under other buttons (making it unreadable).

### ISSUE THREAD

**Issue by nicu-chiciuc** [vizabi/vizabi#2448]
As can be seen in the image, when hovering over any button, the tooltip will be displayed under the button bellow. In the `assets/css/_utils.scss` and attempt was made to use a bigger `z-index` for the tooltip but it seems that it didn't help. 

The screenshot is from Chrome yet the same problem persists on Firefox.
<img width="240" alt="screen shot 2017-02-23 at 13 34 54" src="https://cloud.githubusercontent.com/assets/4076804/23257584/904d77ac-f9d5-11e6-8907-0b167fdfda72.png">

**Comment by angieskazka** [comment]
@nicu-chiciuc this is because tooltip is :after element, not a proper element where we can change the z-index. please send a PR if you feel like fixing it =) 
thanks in advance

**Comment by nicu-chiciuc** [comment]
I'm not very well-versed in css yet I've been exploring this bug for the past hour I found a solution that left me dumbfounded. Basically by removing `z-index: 2;` on the 3rd line in `/preview/assets/css/_utils.scss` everything works as expected.

<img width="185" alt="screen shot 2017-02-23 at 15 33 57" src="https://cloud.githubusercontent.com/assets/4076804/23261110/ec8e12fa-f9e5-11e6-9687-42feca28a284.png">

Here's the new [branch](https://github.com/vizabi/vizabi/compare/develop...nicu-chiciuc:nicu-chiciuc/tooltip-bug). I'm not sure to which branch should I open the pull request.

**Comment by angieskazka** [comment]
@nicu-chiciuc you did it! thanks so much

issue fixed in https://github.com/vizabi/vizabi/pull/2449/commits/acaf361a992da77981801dafb7d612f783144ee9
