### ISSUE TITLE
"..." Is displayed instead of selected language on tools page

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2460]
**Platform:**
Ipad, Ipad Mini 4, Ipad mini. All browsers 
Iphone 5,6. All browsers 
windows 10/Edge 14
Mac OS + Safari

**Steps to Reproduce:**
Navigate to URL : http://tools-stage.gapminderdev.org/tools (dev is affected too)

**Actual Result:**
"..." displayed Instead of language. 

**Expected result:**
Correct language should be displayed.

**Screenshot**
![img_0005](https://cloud.githubusercontent.com/assets/12167296/23363339/dd64aef4-fd02-11e6-8fbf-611ae22b4b31.PNG)

**Comment by k6Labz** [comment]
same issue occurs on windows 10/Edge 14

**Comment by rychkog** [comment]
@k6Labz This is fixed on http://tools-dev.gapminderdev.org/tools/, please have a look

**Comment by Legionivo** [comment]
verified. fixed

**Comment by angieskazka** [comment]
verified
