### ISSUE TITLE
Data doubts on linechart eats a lot of space

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2463]
**Steps to reproduce:**
1. go to http://tools-dev.gapminderdev.org/tools
2. Open `Linechart`

**Actual result:** 
data doubts title eats a lot of useful space.

**Expected result:**
Data doubts has better position and doesn't eat useful space. 

**Screenshot:** 

![selection_004](https://cloud.githubusercontent.com/assets/12167296/23368166/8ff5607e-fd15-11e6-9741-252e374d3c11.png)

**Comment by angieskazka** [comment]
it's not data doubts, these are the labels taking the space
