### ISSUE TITLE
When user loads the chart after switching the language the Application crashed

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2467]
**Severity:**
Major 

**Module:**
. Mountain chart
. Bubble map
.  Bar rank.

**Platform:**
. Mac 10.11  / Google Chrome
. Win 7 / Google Chrome 

**STEPS TO REPRODUCE:**
1.	Open the URL  http://tools-dev.gapminderdev.org/tools/
2.	Switch language from English to Arabic.
3.	Click on Mountain chart or Bar Rank.

**ACTUAL RESULTS:**
Application crashed.

**Expected Result:**
Application shouldn’t crash.

**SCREENSHOT:**

![bug2](https://cloud.githubusercontent.com/assets/9950837/23404404/a74744b4-fd69-11e6-91c0-9966c9b807eb.jpg)

**Comment by angieskazka** [comment]
closing this but #2461 still persists
