### ISSUE TITLE
Dropdown menu for language change and text overlap.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2470]
**SEVERITY:**  Major

**MODULE:** 
. All charts.

**PLATFORM:** 
. Win 7 / Google Chrome  

**STEPS TO REPRODUCE:**
1. Navigate the URL http://tools-stage.gapminderdev.org/tools/

**ACTUAL RESULTS:**
Text overlap with dropdown menu for language change.

**EXPECTED RESULTS:**
Text and dropdown menu shouldn’t overlap.

**SCREENSHOT:**

![v2](https://cloud.githubusercontent.com/assets/9950837/23450921/6b8fa396-fe7f-11e6-9b62-358a809031d1.jpg)

**Comment by angieskazka** [comment]
this is because fonts were broken. Georgii fixed it now
