### ISSUE TITLE
Vizabi website: Mountain chart is not animating / changing with time

### ISSUE THREAD

**Issue by motin** [vizabi/vizabi#2472]
Visited http://vizabi.org/examples/mountain-chart.html and found the following: 
![mar-01-2017 22-32-28](https://cloud.githubusercontent.com/assets/793037/23479984/fd92099c-fece-11e6-9535-8e547c10b128.gif)

**Comment by motin** [comment]
Sometimes the mountains change to show continent-only mountains (with same overall shape) and if I select year 2015 (the most recent) the mountain changes to show that year's data (for all years, ie it is stuck on that state)

Console:

vizabi.js:881 mountain chart failed to generate shapes. check the incoming data
warn @ vizabi.js:881
vizabi.js:1702 Uncaught Error: Illegal call. TypeError: Cannot read property 'KEY' of undefined
    at Promise.reject (vizabi.js:1702)
    at Promise.then (vizabi.js:1672)
    at Class.getFrame (vizabi.js:5062)
    at Class._adjustMaxY (vizabi.js:21033)
    at vizabi.js:20372
    at Promise.<anonymous> (vizabi.js:5068)
    at fireQ (vizabi.js:1849)
    at Promise.resolve (vizabi.js:1697)
    at Promise.<anonymous> (vizabi.js:5236)
    at fireQ (vizabi.js:1849)

**Comment by motin** [comment]
This is on the latest Chrome (56.0.2924.87 (64-bit)) on OSX Sierra

**Comment by angieskazka** [comment]
fixed with https://github.com/Gapminder/vizabi-website/pull/34
