### ISSUE TITLE
Application crashed whenever user loads Bar rank.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2474]
**SEVERITY:**  Major
**MODULE:**  
•	Bar Rank. 

**PLATFORM:** 
       • Win 7 / Google Chrome 
       •S6 /Google Chrome
 
**STEPS TO REPRODUCE:**
    1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
    2.Click on Bar rank.

**ACTUAL RESULTS:**
      Application Crash when user clicks on Bar rank.

**EXPECTED RESULTS:**
    Application shouldn’t crash.

**SCREENSHOT:**
  
![bug2](https://cloud.githubusercontent.com/assets/9950837/23495745/49ada462-fecf-11e6-83a1-52214e719e84.jpg)

**Comment by angieskazka** [comment]
retested on 
win10/Chrome
mac/chrome
mac/safari
android/chrome
win10/IE11
win10/edge

can not reproduce anymore
