### ISSUE TITLE
Countries name and Bars color turn black

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2475]
**SEVERITY:**  Major

**MODULE:** 
    •Bar Rank.

**PLATFORM:** 
    •Win 7 / Google Chrome  
    •S6 / Google Chrome  
    •Win10/Edge 14

**STEPS TO REPRODUCE:**
     1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
     2.click on Bar rank.
     3.Expand Bar graph.

**ACTUAL RESULTS:**
List of countries name and bars color turn black.

**EXPECTED RESULTS:**
Countries name and bars color shouldn’t turn black.

**SCREENSHOT:**
![3-1-2017 5-12-53 pm](https://cloud.githubusercontent.com/assets/9950837/23496815/f9ef9f2e-fed4-11e6-85f6-1b1fa734e53c.jpg)

**Comment by angieskazka** [comment]
Win7 and MacOS /Chrome - confirmed fixed on dev, broken on stage
