### ISSUE TITLE
Mail logo used with social media links redirect user to blank page.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2481]
**SEVERITY:**  Major

**MODULE:** 
•	All charts.

**PLATFORM:** 
•	 Windows10 / Google Chrome  

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Click on “Mail” logo at top right.

**ACTUAL RESULTS:**
User is redirected to blank page.

**EXPECTED RESULTS:**
User shouldn’t be redirected to blank page.

**SCREENSHOT:**

![issue1](https://cloud.githubusercontent.com/assets/9950837/23552073/ce866e90-003b-11e7-99bb-69924b010525.jpg)

**Comment by rychkog** [comment]
@k6Labz This is fixed on http://tools-dev.gapminderdev.org/, please check
