### ISSUE TITLE
Alignment issue of text in dropdown for language change.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2483]
**SEVERITY:**  Minor

**MODULE:** 
•	All charts

**PLATFORM:** 
•	 Windows10 / Edge14

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Click on drop down menu for language change.

**ACTUAL RESULTS:**
Text “English” isn’t properly aligned.

**EXPECTED RESULTS:**
Text should be aligned.

**SCREENSHOT:**
![isuue3](https://cloud.githubusercontent.com/assets/9950837/23552352/35f1bcaa-003d-11e7-8292-bf580ac7cd44.jpg)

**Comment by rychkog** [comment]
@k6Labz This is fixed on http://tools-dev.gapminderdev.org/tools/, please check

**Comment by angieskazka** [comment]
this is fixed together with #2460
