### ISSUE TITLE
Mail logo used with social media links redirect user to Google home page.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2484]
**SEVERITY:**  Major

**MODULE:** 
•	All charts.

**PLATFORM:** 
•	 Windows10 / Edge 14
•	Windows 7 + IE11

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Click on “Mail” logo at top right.

**ACTUAL RESULTS:**
User is redirected to Google Homepage.

**EXPECTED RESULTS:**
User shouldn’t be redirected to Google Homepage.

**SCREENSHOT:**

![issue4 a](https://cloud.githubusercontent.com/assets/9950837/23552393/70e6970e-003d-11e7-90ae-8053d1cb69f6.jpg)
![issue4 b](https://cloud.githubusercontent.com/assets/9950837/23552394/70ebc22e-003d-11e7-9355-012092458e6e.jpg)

**Comment by rychkog** [comment]
@k6Labz This is because you have chrome as default mail client on Windows - Please, read article on [how to change default mail client] (http://www.officetooltips.com/office/tips/how_to_modify_default_mail_client_in_windows_10.html) and verify this.

**Comment by angieskazka** [comment]
it looks like a normal awkward behavior on windows

**Comment by k6Labz** [comment]
@rychkog @angieskazka  Yes right !! As georgi said
