### ISSUE TITLE
Presentation icon presents only 4 countries on line chart(United states, China, Russia and Nigeria)

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2485]
**SEVERITY:**  Major

**MODULE:** 
	•Line chart.

**PLATFORM:** 
	• Windows7 / Google Chrome  
	•Nexus9 /Chrome
	•Windows10 / Edge14

**STEPS TO REPRODUCE:**
1.	Navigate the URL http://tools-dev.gapminderdev.org/tools/
2.	Click on Line chart.
3.	Click on “SHOW ALL”.
4.	Click on presentation icon.

**ACTUAL RESULTS:**
Only 4 countries are presented on line chart.

**EXPECTED RESULTS:**
All countries should be displayed after user clicks  on “SHOW ALL” and presentation icon.

**SCREENSHOT:**
![issue1](https://cloud.githubusercontent.com/assets/9950837/23600572/10c1a02e-01fc-11e7-88f3-945f0a60567b.jpg)

**Comment by angieskazka** [comment]
the act of show doesn't modify URL: non persistent change when it should be persistent?

**Comment by angieskazka** [comment]
fixed in this commit https://github.com/vizabi/vizabi/pull/2551/commits/a77604251ea453b353973e4f2264e564f27b96f4
