### ISSUE TITLE
The selected chart still appears in the related charts section

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2486]
**SEVERITY:** Major

**MODULE:** 
	• Line chart.
	• Bubble map
	• Mountain chart
	• Bar rank.

**PLATFORM:** 
	• Windows7 / Google Chrome  
	• Nexus9 /Chrome
	• Windows10 / Edge14

**STEPS TO REPRODUCE:**
5.	Navigate the URL http://tools-dev.gapminderdev.org/tools/
6.	Click on any chart from Related chart section.
7.	Reload the page.

**ACTUAL RESULTS:**
The selected chart  also appears in the related charts section. 

**EXPECTED RESULTS:**
The selected chart shouldn’t    appears in the related charts section. 

**SCREENSHOT:**
![issue2](https://cloud.githubusercontent.com/assets/9950837/23600841/642ac064-01fd-11e7-91c6-85f384121483.jpg)

**Comment by rychkog** [comment]
@k6Labz Issue is available for testing on http://tools-dev.gapminderdev.org
