### ISSUE TITLE
Color legend ordinal doesn't show up or is not visible

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2493]
See this page:

http://jasperheeffer.nl/gapminder/demo/gdl-tanzania2/

This is the latest Vizabi release (https://github.com/vizabi/vizabi/releases/tag/v0.19.1)
Data: http://jasperheeffer.nl/gapminder/demo/gdl-tanzania2/data/tanzania2.csv
Config: http://jasperheeffer.nl/gapminder/demo/gdl-tanzania2/config.js
Environment: Win 10 Chrome 56.0.2924.87

Steps:
1. Look at website linked above

Error:
Note how the color is set to an ordinal concept (`type`) and the color legend doesn't show under the indicator picker.
![image](https://cloud.githubusercontent.com/assets/1596071/23702438/859bb2a8-03fb-11e7-939d-73b85c368552.png)

Expected:
Colorlegend shows up like normal

Steps (continued):
1. Click color indicator picker
2. Choose single color
3. Click color indicator picker
4. Choose "type" again

Error:
Color legend is not visible (though it takes up space and you can hover it).
![image](https://cloud.githubusercontent.com/assets/1596071/23702424/79049f64-03fb-11e7-9da3-2ec6796f48e0.png)

Expected:
Color legend is visible.

**Comment by angieskazka** [comment]
@jheeffer 
this is fixed in the new release https://github.com/vizabi/vizabi/releases/tag/v0.20.1
Retest with tanzania data here: http://angieskazka.github.io/vizabi-tanzania/index.html

![image](https://cloud.githubusercontent.com/assets/3648190/23874409/fbe0a660-084e-11e7-916f-60e749592741.png)
