### ISSUE TITLE
On indicator picker open focus should be on text field

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2494]
Reproduce:
1. Open indicator picker

Current:
Focus is not on text field in indicator picker (you cannot directly start typing in filter box)

expected
Focus is on text field in indicator picker (you can directly start typing in filter box)

**Comment by angieskazka** [comment]
yes!

except touch devices because then a keyboard pops up and blocks the view

**Comment by angieskazka** [comment]
@kuguarpwnz that didn't work on Mac + Chrome. where can i test it (tried locally, on http://static.gapminderdev.org/preview/master/bubblemap.html and on tools-dev)
