### ISSUE TITLE
When user changes the size of bubbles, values still remain unchanged.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2495]
**SEVERITY:**  Minor

**MODULE:** 
     • Bubble Map
     • Bubble chart

**PLATFORM:** 
	• Windows 10 / Google Chrome  
	• Windows 10 / Edge

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Click on “Options”
3.Click on “Size”
4.Move the handle to change the size.

**ACTUAL RESULTS:**
The values remain same as user moves the handle.

**EXPECTED RESULTS:**
The values should change when user moves the handle on size slider.

**SCREENSHOT:**
![th1](https://cloud.githubusercontent.com/assets/9950837/23739906/f1f42d0e-0455-11e7-8bb0-7647c2a39ea5.jpg)

**Comment by angieskazka** [comment]
these values shouldn't change: you make 1.4B bubble bigger or smaller but it's not getting less or more people in that bubble
