### ISSUE TITLE
Blank screen displayed instead of charts in IE 11

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2498]
**Steps to reproduce:**
1. Open http://tools-stage.gapminderdev.org in IE 11
2. Wait for bubble chart loaded.
3. Try to switch to any other chart.

**Actual result:**
blank screen displayed. 

**Expected result:**
selected chart should be displayed.

![03_09_11 20 50_01](https://cloud.githubusercontent.com/assets/12167296/23744076/9a1d59be-04bb-11e7-8ee0-7fda11942e13.png)

**Comment by angieskazka** [comment]
to me it looked like it was working just now but broke while i was testing other issues

![image](https://cloud.githubusercontent.com/assets/3648190/23744268/dec36002-04b3-11e7-9c38-7b0b7f39ac26.png)

**Comment by rychkog** [comment]
WIll be fixed in scope of https://github.com/vizabi/ng2-vizabi/issues/6

**Comment by Legionivo** [comment]
verified - fixed
