### ISSUE TITLE
Page url doesn't change after switching to another chart

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2503]
Win 7/ Chrome 
Win 7/ IE 11
Win 10/ Edge 14

**Steps to reproduce:**
1. Open tools-dev.gapminderdev.org
2. Wait for bubblechart loaded.
3. Switch to line chart(or bar rank).

**Actual result:**
Page url didn't change. 

**Expected result:**
page url should change and contain selected chart address.

**Comment by angieskazka** [comment]
could reproduce on IE10/Edge! Only bar rank and line chart, MC and bubble map are ok!

**Comment by rychkog** [comment]
@Legionivo @angieskazka It is on dev and ready for testing

**Comment by Legionivo** [comment]
verified - fixed
