### ISSUE TITLE
When user clicks on any control application loads and display content in Arabic.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2506]
**SEVERITY:**  Major

**MODULE:** 
      • All charts

**PLATFORM:** 
	• Windows10 / Google Chrome  

**STEPS TO REPRODUCE:**
1.	Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.	Switch from English to Arabic.
3.	Switch back to English.
4.	Change the opacity (or click on any control)

**ACTUAL RESULTS:**
Application is translated to Arabic.

**EXPECTED RESULTS:**
Application should display the content in selected language

**SCREENSHOT:**
![f2](https://cloud.githubusercontent.com/assets/9950837/23791305/47571946-0537-11e7-9853-db2423f0a6c1.jpg)

**Comment by angieskazka** [comment]
good catch. arabic is stuck in the url and didn't get removed when switching back to english

**Comment by rychkog** [comment]
@angieskazka Is this issue valid for dev?

**Comment by rychkog** [comment]
@angieskazka, @k6Labz Please, verify on dev - http://tools-dev.gapminderdev.org/tools
