### ISSUE TITLE
Slider stucks and Play/Pause button isn’t functional. 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2507]
**SEVERITY:**  Major

**MODULE:** 
•	Line chart

**PLATFORM:** 
•	 Windows 7/ IE
•	Windows 10/ Edge

**STEPS TO REPRODUCE:**
1.	Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.	Click on line chart
3.	Click on “Show All”
4.	Click on Play button.

**ACTUAL RESULTS:**
Play and Pause button isn’t functional. 

**EXPECTED RESULTS:**
Play and Pause button should be functional. 

**SCREENSHOT:**

![f3](https://cloud.githubusercontent.com/assets/9950837/23795921/e6a4cd3a-054c-11e7-8d55-69dc56a90f6f.jpg)

**Comment by angieskazka** [comment]
this is just a performance issue on a slow device. too many lines
