### ISSUE TITLE
Line chart shows all lines and country names in Green color only

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2512]
**SEVERITY:**  Major

**MODULE:** 
	• Line chart

**PLATFORM:** 
•	 Windows10 / Google Chrome  
•	Windows 10 / Edge
•	Windows 7 / IE

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-dev.gapminderdev.org/tools/
2.Click on line chart.

**ACTUAL RESULTS:**
All the lines and country names are in green color.

**EXPECTED RESULTS:**
Country names and lines should be in different colors.

**SCREENSHOT:**
![m1](https://cloud.githubusercontent.com/assets/9950837/23844736/5c9cbd6e-0781-11e7-9f89-9b5a879facf6.jpg)

**Comment by angieskazka** [comment]
this was incorrect data in WS dev, fixed now
