### ISSUE TITLE
Number of people living in extreme poverty in 2015 is "830" Millions

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2522]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain chart.

**PLATFORM:** 
	• Windows10 / Google Chrome ,Edge
        • Windows7 / Chrome,Firefox,IE

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Mountain chart

**ACTUAL RESULTS:**
Number of people living in extreme poverty  is "830" Millions in 2015

**EXPECTED RESULTS:**
Number of people living in extreme poverty  should be "827" Millions in 2015

**Comment by angieskazka** [comment]
we've updated the datasets, values might have gotten more precise now
