### ISSUE TITLE
'CSS.escape' is undefined on Mac/safari: user can't perform any other operation after selecting Bubble 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2523]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart

**PLATFORM:** 
•	Mac / Safari

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Bubble Map
3.Select any bubble.

**ACTUAL RESULTS:**
User is unable to perform any other operation after selecting Bubble.

**EXPECTED RESULTS:**
User should be able to perform other operations after selecting bubble.

**Comment by angieskazka** [comment]
'CSS.escape' is undefined

**Comment by Legionivo** [comment]
verified - fixed
