### ISSUE TITLE
 'CSS.escape' is undefined on Mac/safari: user can't select/deselect countries using the button "Find" to the right.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2524]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble chart
•       Bubble Map

**PLATFORM:** 
•	 Mac / Safari

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Select any country using the button "Find" to the right

**ACTUAL RESULTS:**
Countries don't get selected

**EXPECTED RESULTS:**
Countries should get selected.

**Comment by Legionivo** [comment]
verified - fixed
