### ISSUE TITLE
'CSS.escape' is undefined on Mac/safari: User can neither select bubbles nor the bubbles react to hovering

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2525]
**SEVERITY:** Major

**MODULE:**
•	Bubble Map

**PLATFORM:**
•	Mac / Safari

**STEPS TO REPRODUCE:**
1.Navigate the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Bubble Map
3.Hover/Click on bubbles

**ACTUAL RESULTS:**
User can't select Bubbles and bubbles don't react to hover.

**EXPECTED RESULTS:**
User should be able to select Bubbles and bubbles should  react hovering.

**SCREENSHOT:**

![abc](https://cloud.githubusercontent.com/assets/9950837/23902013/c814d9fe-087c-11e7-9445-339cbe5e33f9.png)

**Comment by Legionivo** [comment]
verified - fixed
