### ISSUE TITLE
Log scale breaks bar rank

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2526]

**Comment by kuguarpwnz** [comment]
https://github.com/vizabi/vizabi-barrankchart/commit/d86c716740e6c2c9f6234dc46563bce299de82b0

**Comment by angieskazka** [comment]
https://github.com/vizabi/vizabi-barrankchart/commit/04d2f01030ab1214edffdd3287a11333ece4f104

**Comment by angieskazka** [comment]
verified on stage: fixed
