### ISSUE TITLE
Tools page sets vizabi model on every url update

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2529]
>now ng2-tool-page calls Tool.setModel on any url change(for example if Presentation mode is selected inside the chart then Tool.setModel is called from outside)

> on prod old version is called Tool.setModel only if url is changed by outer action (edited)

it should only update the model if the change comes from anywhere but vizabi
the updates vizabi poops out shouldn't be fed back =)

**Comment by rychkog** [comment]
@angieskazka Fixed and could be verified on http://tools-dev.gapminderdev.org/tools

**Comment by angieskazka** [comment]
yiess!
