### ISSUE TITLE
User can't drag  the slider ball forward after reloading page.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2532]
**SEVERITY:**  Major

**MODULE:** 
•	All charts

**PLATFORM:** 
•	 Samsung S6  / Google Chrome  
•       Windows10 / Chrome /Edge /IE

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Open line chart.
2.Drag the slider ball backward.
3.Reload the page
4.Drag  the ball to the end of slider  (2015).
5.Resize window and try again

**ACTUAL RESULTS:**
User can't drag the slider ball to end of slider (2015)
After resizing the slider bar becomes shorter

**EXPECTED RESULTS:**
Ball should be Drag able to end point on slider(2015).
Resizing should keep update the length of the bar correctly

![mahgq5hkui](https://cloud.githubusercontent.com/assets/3648190/23950483/8cce87d6-09a4-11e7-8c8b-2c50e5f17fac.gif)

![j6vdizsurb](https://cloud.githubusercontent.com/assets/3648190/23950485/8eb50f70-09a4-11e7-92c9-4f5d8be7915d.gif)

**Comment by angieskazka** [comment]
@kuguarpwnz tiny improvement request: that margin on the left shifts the slider so it's slightly off
please check on all profiles

on smallest profile there might be too little space, but we can at least get the 2015 point aligned

![image](https://cloud.githubusercontent.com/assets/3648190/23967197/6a68c566-09d7-11e7-808b-ac3298efccca.png)
