### ISSUE TITLE
Switching between charts brings up an unstable crash: domain() of undefined

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2543]
tools stage
mac chrome

![image](https://cloud.githubusercontent.com/assets/3648190/24037325/d991ca9c-0b16-11e7-8d65-575d81f276ae.png)

**Comment by kuguarpwnz** [comment]
Happens here
https://github.com/vizabi/vizabi/blob/develop/src/helpers/d3.axisWithLabelPicker.js#L22
