### ISSUE TITLE
User can’t select/Deselect countries after clicking slider Play/Pause button.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2552]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain chart

**PLATFORM:** 
    • Win 10  / Google Chrome  
    •Win 10 / Edge

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Mountain chart.
3.Play the slider.
4.Click on mountain to select/deselect countries.

**ACTUAL RESULTS:**
User isn’t able to select/deselect countries.

**EXPECTED RESULTS:**
User should be able to select/deselect countries.

**SCREENSHOT:**
http://g.recordit.co/f8G41xpG1W.gif

**Comment by k6Labz** [comment]
@kuguarpwnz  Allow selecting countries during play.User can now deselect  countries during play but can't select them during play.
http://g.recordit.co/ImM18rMdWC.gif

**Comment by kuguarpwnz** [comment]
@k6Labz 

> Angie [12:35 PM] 
Maybe need to allow only deselect, but not select on shape click during play

Vladislav Baranchuk [12:37 PM] 
why?

Angie [12:44 PM] 
While the shapes are playing they merge together. Selection attempt on China might lead to selection of Asia

**Comment by angieskazka** [comment]
@k6Labz yes, we shouldn't be able to select mountains during play
