### ISSUE TITLE
When user switch to Arabic language,Countries name don't get translated.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2553]
**SEVERITY:**  Major

**MODULE:** 
•	Bar rank

**PLATFORM:** 
•	 Win 10  / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Bar rank
3.Switch to Arabic language.

**ACTUAL RESULTS:**
Countries name don't translate into Arabic.

**EXPECTED RESULTS:**
Countries name should be translated to Arabic.

**SCREENSHOT:**
![m1](https://cloud.githubusercontent.com/assets/9950837/24091737/23b410a2-0d07-11e7-8dc5-d8762baae1a7.jpg)

**Comment by kuguarpwnz** [comment]
fixed on dev
