### ISSUE TITLE
When user click on slider during play slider ball stuck.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2572]
**SEVERITY:**  Major

**MODULE:** 
•	All charts.

**PLATFORM:** 
•	 Win 10  / Edge

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Play the slider.
3.Click on slider during play.
4.Play slider again.

**ACTUAL RESULTS:**
Slider ball stuck.

**EXPECTED RESULTS:**
slider ball should not stuck.

**SCREENSHOT:**

![t1](https://cloud.githubusercontent.com/assets/9950837/24244919/ac226136-0fe2-11e7-9e7b-936edb075091.jpg)

**Comment by kuguarpwnz** [comment]
Should be fixed on dev

**Comment by k6Labz** [comment]
Fixed on dev.
