### ISSUE TITLE
Country names not displayed after Show button used

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2575]
**Browser:**
Chrome on Windows/Linux

**Steps:**
1. Open tools page on stage.
2. Open Rankings chart.
3. Click Show button.
4. Select any country(e.g. China).
5. Deselect previously selected country.

**Actual result:** 
Only selected country name displayed in the list. 

**Expected result:**
All countries names are displayed.

![03_24_12 09 07_01](https://cloud.githubusercontent.com/assets/12167296/24289662/eab35fba-108a-11e7-8bee-e65e192232b0.png)

**Comment by kuguarpwnz** [comment]
Fixed on dev

**Comment by Legionivo** [comment]
Verified on dev - fixed
