### ISSUE TITLE
Countries list not displayed after Show button used

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2576]
**Browsers:**
Firefox Windows/Linux.

**Steps:**
1. Open tools page on stage.
2. Open Rankings chart.
3. Click Show button.
4. Select any country(e.g. China).
5. Deselect previously selected country.

**Actual result:**
Only selected **country** displayed in the list.

**Expected result:**
All countries are displayed.

![03_24_12 25 58_01](https://cloud.githubusercontent.com/assets/12167296/24290273/11000130-108d-11e7-88ef-fdfe3222ad52.png)

**Comment by kuguarpwnz** [comment]
Fixed on dev

**Comment by Legionivo** [comment]
Verified on dev - fixed
