### ISSUE TITLE
The page http://static.gapminderdev.org/ doesn't show anything.

### ISSUE THREAD

**Issue by nicu-chiciuc** [vizabi/vizabi#2578]
Probably it's a problem with the new release but the http://static.gapminderdev.org/ page doesn't display any graphics, just the layout.

**Comment by nicu-chiciuc** [comment]
<img width="1075" alt="screen shot 2017-03-24 at 3 55 34 pm" src="https://cloud.githubusercontent.com/assets/4076804/24297305/f839ff7a-10aa-11e7-8b20-8f0a64778652.png">

**Comment by angieskazka** [comment]
hi @nicu-chiciuc!
the page http://static.gapminderdev.org/ was never showing anything 
what was under vizabi/develop/preview now moved to http://static.gapminderdev.org/preview/master/

:) please tell me where did you get your link previously so i can fix it there too

**Comment by nicu-chiciuc** [comment]
It's in README.md, /preview/develop/ should be changed to /preview/master/
<img width="739" alt="screen shot 2017-03-25 at 9 12 30 am" src="https://cloud.githubusercontent.com/assets/4076804/24320314/9fa0c326-113b-11e7-9fda-9cfb55171e6f.png">

**Comment by angieskazka** [comment]
thanks @nicu-chiciuc! i've changed the link now
(if you find broken things in the future you can also fix them, it's open source)
