### ISSUE TITLE
Examples are not working, preview/ is gone, LineChart tool is not available

### ISSUE THREAD

**Issue by thaibui** [vizabi/vizabi#2579]
For the latest version v0.20.2
* Contribution guide is outdated https://github.com/vizabi/vizabi/blob/v0.20.2/CONTRIBUTING.md
* The preview/ was there in the previous version, but not on the latest one. How do I see examples locally?
* No LineChart and other charts under tools? https://github.com/vizabi/vizabi/tree/v0.20.2/src/tools

Most importantly, I was trying to setup some simple examples and was unable to do anything :(. I would love to use this library for visualizing some of my company production data and possibly contribute to the project.

Thanks!

**Comment by thaibui** [comment]
It looks like you guys are actively working this. I see that the project is split into multiple smaller components such as vizabi-preview, vizabi-linechart, etc. Some simple instructions on how to use these would be nice, or maybe I should just wait :)

**Comment by angieskazka** [comment]
yes, thank you for bringing this up @thaibui ! 
i have now updated the document here
https://github.com/vizabi/vizabi/blob/develop/CONTRIBUTING.md

let me know if you have any problems, or fix them if you feel you can :)

**Comment by thaibui** [comment]
Thanks, @angieskazka! I will give it a try.
