### ISSUE TITLE
Preview page doesn't work on Safari

### ISSUE THREAD

**Issue by angieskazka** [vizabi/vizabi#2580]
Open Safari
Open this link: http://static.gapminderdev.org/preview/master/popbyage.html

`var url = new URLSearchParams(window.location.search);`
URLSearchParams is not defined

**Comment by angieskazka** [comment]
@dab2000 
polyfill fix attempt is here https://github.com/vizabi/vizabi-preview/pull/5/commits/3090b036c7775cb540fdd3fe0307a7a4c055c548

this didn't work though. now getting this:

[Error] SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.
	(anonymous function) (preview.js:3823)

[Error] ReferenceError: Can't find variable: URLSearchParams
	global code (popbyage.html:124)

**Comment by kuguarpwnz** [comment]
@angieskazka it's better to add this script name here https://github.com/vizabi/vizabi-preview/blob/master/webpack.config.js#L60 and load it as separate file
