### ISSUE TITLE
Question about embedding your bubblechart to my web page

### ISSUE THREAD

**Issue by qiongcheng5** [vizabi/vizabi#2610]
This may not be an issue. The vizabi is new to me. I download vizabi.js and vizabi.css and tried to embed the bubblechart to my web page, but failed. It just return undefined data type for Vizabi function call.
Here is the code:
<!DOCTYPE HTML>
<html>
    <head>
        <title>Data Lab | Topic Editor</title>
         
        <link rel="stylesheet" type="text/css" href="vizabi/vizabi.css">
        <script src="vizabi/vizabi.js"></script>
            <script src="dist/polyfills.js"></script>
    <script src="vizabi/libs/d3.min.js"></script>
    <script src="vizabi/libs/vizabi.js"></script>
    <script src="vizabi/libs/bubblechart.js"></script>
    <script src="vizabi/libs/bubblemap.js"></script>
    <script src="vizabi/libs/mountainchart.js"></script>
    <script src="vizabi/dist/app.js"></script>

        
        

        
        
        
        
     
    </head>
    <body>
        
        
        <div id='placeholder' style='position: absolute; top: 0; bottom: 0; left: 0; right: 0;'>
            <button onclick="document.write('\n\n\n5 + 6')">Try it</button>
        </div>
        
        <script defer="">
            Vzb('TestBubbleChart', document.getElementById('placeholder'), {
                state: {
                  time: {
                    value: '1900',
                    start: '1800',
                    end: '2015'
                  },
                  entities: {
                    dim: "geo",
                    show: {
                      _defs_: {
                        "geo": ["*"],
                        "geo.category": ["country"]
                      }
                    },
                    opacitySelectDim: .3,
                    opacityRegular: 1,
                    },
                    marker: {
                      space: ["entities", "time"],
                      type: "geometry",
                      label: {
                        use: "property",
                        which: "geo.name"
                      },
                      axis_y: {
                          use: 'indicator',
                          which: 'sg_child_mortality_rate_per1000',
                          scaleType: 'linear'
                      },
                      axis_x: {
                          use: 'indicator',
                          which: 'sg_gdp_p_cap_const_ppp2011_dollar',
                          scaleType: 'log'
                      },
                      color: {
                        use: "property",
                        which: "geo.world_4region"
                      },
                      size: {
                        use: "indicator",
                        which: "sg_population"
                      }
                    }
                  },
                  data: {
                    reader: "csv",
                    path: "vizabi/dont-panic-poverty.csv"
                  },
                  ui: {
                    buttons: [],
                    dialogs: {
                      popup: []
                    }
                  }
            });
            </script>
            
        
    </body>
</html>

Do I need to launch node.js?

**Comment by angieskazka** [comment]
hi @qiongcheng5!
sorry that it took me so long to answer you. Please see this article, it offers two ways of embedding: one is very-very simple and another one has a code example =)

https://vizabi.org/tutorials/2017/04/01/embed-a-gapminder-chart/

see also other tutorials on that website and feel free to ask more questions here
reopen if still having trouble =)

Angie
