### ISSUE TITLE
Indicator color doesn't return to initial state after returning to tools page initial state

### ISSUE THREAD

**Issue by Legionivo** [vizabi/vizabi#2619]
Environments: dev, stage, prod

**Steps:**
1. Open bubbles chart on tools page.
2. Change indicator color to some other(for example Society -> War&Peace -> Military expediture). 
3. Change url to start page(http://tools-stage.gapminderdev.org/tools/#_locale_id=en;&chart-type=bubbles)

**Actual result:** 
Bubbles color doesn't correspond to select indicator color.

**Expected result:** 
Bubbles has color corresponding to selected indicator color.

**Comment by Legionivo** [comment]
It looks as duplicate of https://github.com/vizabi/vizabi/issues/2600 , but behavior differs.

**Comment by kuguarpwnz** [comment]
Pr with fix is not merged yet
