### ISSUE TITLE
Chart Zoom Event

### ISSUE THREAD

**Issue by vikash20186** [vizabi/vizabi#2623]
Hello Everyone,

Is there any zoom event which can be used to do some action whenever user zooms in/out chart? I need to do some custom update to chart once user zooms charting area. I see there a change event but its not trigged in case of zoom. 

Sorry for asking question here as I could not find any other place to ask this question. Docs also doesn't say anything on zoom in, zoom out event.

Any help will be highly appreciated. 

Thanks,
Vikash

**Comment by kuguarpwnz** [comment]
Hi @vikash20186!
Sorry for the late answer.
You can use these change events to to recognize zoom events
```
"change:marker.axis_x.zoomedMax"
"change:marker.axis_x.zoomedMin"
"change:marker.axis_y.zoomedMax"
"change:marker.axis_y.zoomedMin"
```

**Comment by angieskazka** [comment]
@vikash20186 this is a proper place to ask such questions! sorry that we were so slow with a reply. A bit more details follow below. Please reopen if still in trouble :)

if you have added your chart to the page like this

```
var chart = Vizabi("BubbleChart", document.getElementById("placeholder"), config); 
```

You should be able to listen to the event like this

```
config.bind['change:marker.axis_y.zoomedMin'] = function(evt, path) {
  console.log(path, evt.source);
};
```
