### ISSUE TITLE
Countries don't get deselected when user click on cross  icon. 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2626]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Map

**PLATFORM:** 
•	 Win 10 / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Select "China" and "India"
3.Click on options.
4.Change color indicator to "Child mortality rate".
5.Deselect the bubbles.

**ACTUAL RESULTS:**
Selected bubble doesn't get deselected.

**EXPECTED RESULTS:**
Selected bubble should get deselected,when user click on cross icon.

**SCREENSHOT:**
http://g.recordit.co/OuHlHmUEJu.gif

**Comment by kuguarpwnz** [comment]
@k6Labz can't reproduce. what is your testing environment?

**Comment by k6Labz** [comment]
i am testing it on
Windows 10/Google Chrome Version 58.0.3029.110 (64-bit)

**Comment by kuguarpwnz** [comment]
@k6Labz tested with same env. still not reproducible. maybe i need to make some additional steps?

**Comment by k6Labz** [comment]
Its not reproducible now.

**Comment by kuguarpwnz** [comment]
@k6Labz why this issue is opened again?

**Comment by k6Labz** [comment]
it reproducible.Kindly check http://g.recordit.co/OuHlHmUEJu.gif

**Comment by kuguarpwnz** [comment]
![demo](https://cloud.githubusercontent.com/assets/6388788/26341030/46d58a14-3f9a-11e7-8d02-565a3db1d276.gif)
@k6Labz Still can't reproduce 😞
