### ISSUE TITLE
When user change the scale on X axis,Slider disappeared. 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2627]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble chart

**PLATFORM:** 
•	 Win 10 / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-dev.gapminderdev.org/tools/
2.Change X axis to "Forest Products removal.

**ACTUAL RESULTS:**
Slider disappeared.

**EXPECTED RESULTS:**
Slider should be visible to user and should be functional.

**SCREENSHOT:**

![n3](https://cloud.githubusercontent.com/assets/9950837/26056837/6802766c-3990-11e7-9216-5d4f00e8df30.png)

**Comment by dab2000** [comment]
Forest Products removal, per ha have data for '2005' only.
So slider dissappeared and play button disabled

**Comment by angieskazka** [comment]
Dab is right, this works as expected. 
@k6Labz
