### ISSUE TITLE
When user select color on color panel, Panel isl still visible to user.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2629]
**SEVERITY:**  Medium

**MODULE:** 
• Bar Chart

**PLATFORM:** 
•	 Win 10 / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/ 
2.Open Bar chart.
3.Click on "Options" at bottom right.
4.Change "Color"scale to "CO2 per capita"
5.Click on Color indicator.
6.Select any color from color panel.

**ACTUAL RESULTS:**
When user select color on color panel, Panel isl still visible to user..

**EXPECTED RESULTS:**
Panel should disappear after selecting color.

**SCREENSHOT:**

http://g.recordit.co/4ymIQLjjuh.gif

**Comment by angieskazka** [comment]
panel should disappear on click, not on hover. did you click the colors?

**Comment by k6Labz** [comment]
@angieskazka  yes i clicked but the panel was still appearing on screen

**Comment by angieskazka** [comment]
@kuguarpwnz the bug by the steps above is fixed. 
please also test the click on default color in color picker and on background of color picker (should cancel action)

![image](https://cloud.githubusercontent.com/assets/3648190/26467193/d73763cc-4191-11e7-8c97-14787cab96a2.png)

**Comment by angieskazka** [comment]
after the fix above this happened:

![image](https://cloud.githubusercontent.com/assets/3648190/26492670/9bd3409c-4215-11e7-820c-7ada4d632ba3.png)
