### ISSUE TITLE
When user click on ? symbol on y axis,404  Page not found error occurred.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2633]
**SEVERITY:**  Major

**MODULE:** 
•Bar rank

**PLATFORM:** 
•	 Win 10 / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Bar rank
3.Click on Question mark (?) on y-axis.
4.Click on "More info and source"

**ACTUAL RESULTS:**
404  Page not found error occurred.

**EXPECTED RESULTS:**
404  Page not found error should not occur.
Description should be visible to user on hovering Question Mark.

**SCREENSHOT:**
![m1](https://cloud.githubusercontent.com/assets/9950837/26308915/94a1089e-3f14-11e7-8808-503694e970b7.png)
![m2](https://cloud.githubusercontent.com/assets/9950837/26308921/9a1ed7a6-3f14-11e7-94f2-7135e4e2f4fa.png)

**Comment by angieskazka** [comment]
Fixed in the dataset. On develop. Pushing further as soon as WS is ready
