### ISSUE TITLE
On selecting Abkhazia, Malawi populate on the chart 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2637]
**Steps to reproduce:**

1. Navigate ti URL: http://tools-stage.gapminderdev.org/tools/# or navigate to http://www.gapminder.org/tools/#
2. Click on line chart 
3. Click on Abkhazia from the country list 
4. Observe the line chart 

**SCREENSHOT:**
![malawi](https://cloud.githubusercontent.com/assets/9950837/26402443/d3a924a0-40a3-11e7-81e1-701bf8d4cdbc.png)

**Comment by angieskazka** [comment]
@k6Labz can not reproduce, can you please 1) record a gif 2) retest on stage, it might be gone now

**Comment by k6Labz** [comment]
fixed in the new build
