### ISSUE TITLE
The user is able to select the bubble while selecting the pan pointer 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2639]
**Steps to reproduce:**

1. Navigate ti URL: http://tools-stage.gapminderdev.org/tools/# or navigate to http://www.gapminder.org/tools/#
2. Click on pan pointer
3. Click on bubble 

**Expected Result:**
The user should only be able to drag the canvas by pan pointer instead of selecting the bubble as user cant drag the canvas by simple pointer and just select the bubble 

**SCREENSHOT:**

![pan](https://cloud.githubusercontent.com/assets/9950837/26437091/73dacf10-4134-11e7-8094-bd85fa441895.png)

**Comment by angieskazka** [comment]
@k6Labz but then the hover remains, and if we remove hover the chart becomes dead
maybe let's keep both, i reverted the change

let dragging hand select bubbles too
