### ISSUE TITLE
Fix hack which makes marker_tags required

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2682]
https://github.com/vizabi/vizabi/blob/15ed53df31f5df23fdaabf23319d2201cfa8d881/src/components/treemenu/treemenu.js#L626-L627

This hack makes it impossible to have a tool without `marker_tags` in the model. This should be possible, it should just resolve to a default hiearchy.

**Comment by sergey-filipenko** [comment]
https://github.com/vizabi/vizabi/pull/2684
