### ISSUE TITLE
When user switch to Arabic/English,website does not get translated completely

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2699]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Chart

**PLATFORM:** 
•	 Win 10  / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/#_locale_id=ar-SA;&chart-type=bubbles
2.Switch to Arabic/English by clicking on drop down at top.

**ACTUAL RESULTS:**
When user switch to Arabic/English,website does not get translated completely

**EXPECTED RESULTS:**
When user switch to Arabic/English,website should be translated completely.

**SCREENSHOT:**
![v1](https://user-images.githubusercontent.com/9950837/28208108-9dc9d3aa-68a5-11e7-9381-0129a2a4ea37.png)

**Comment by angieskazka** [comment]
2eacadf278a6e5041e2c2d670339e62a73ca0fb2

**Comment by k6Labz** [comment]
@angieskazka issue still exist.
