### ISSUE TITLE
When user change the URL,Error occurred. 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2701]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain Chart

**PLATFORM:** 
•	 Win 10  / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/#_locale_id=en;&chart-type=bubbles
2.Replace bubbles with mountain in URL
3.Press Enter button.

**ACTUAL RESULTS:**
When user change the URL,Error occurred. 

**EXPECTED RESULTS:**
When user change the URL,Error should not occur but respective chart should be displayed. 

**SCREENSHOT:**
![v6](https://user-images.githubusercontent.com/9950837/28211847-30e05012-68b8-11e7-8d01-cd8e97e92f6a.png)

**Comment by angieskazka** [comment]
@rychkog should have fixed it in the refactored tools page
