### ISSUE TITLE
Mountain Chart | Edge | When user hover on mountain,Blank white box appears. 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2704]
**SEVERITY:**  Major

**MODULE:** 
•	Mountain Chart

**PLATFORM:** 
•	Edge

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Click on mountain chart
3.Switch to Arabic
4.Hover on mountains

**ACTUAL RESULTS:**
When user hover on mountain,Blank white box appears. 

**EXPECTED RESULTS:**
When user hover on mountain,Blank white box should not  appear. 

**SCREENSHOT:**
![v10](https://user-images.githubusercontent.com/9950837/28267906-9b65fd60-6b15-11e7-873c-81e71300654d.png)

**Comment by dab2000** [comment]
connected with #2699

**Comment by kuguarpwnz** [comment]
is not reproducible on dev

**Comment by k6Labz** [comment]
verified,not reproducible on dev.
