### ISSUE TITLE
Bubble Chart + Bubble Map | When user select color from color panel,Bubbles color doesn't change.  

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2707]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble chart
•	Bubble Map

**PLATFORM:** 
•	Safari/ iPad Air 2
•	Chrome / Nexus 9

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Tap on "Options" at left.
3.Tap on "COLOR"
4.Change Color scale to Income per person.
5.Tap on color indicator.
6.Select any color from color panel.

**ACTUAL RESULTS:**
When user select color from color panel,Bubbles color doesn't change.

**EXPECTED RESULTS:**
When user select color from color panel,Bubbles color should change.

**SCREENSHOT:**
![v12](https://user-images.githubusercontent.com/9950837/28302448-ce72ec18-6ba6-11e7-8339-40a576623599.png)

**Comment by kuguarpwnz** [comment]
Can't reproduce.
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/6388788/28305636-098ef60e-6ba5-11e7-9075-36eca2613adf.gif)

**Comment by k6Labz** [comment]
@kuguarpwnz  Did you test it on iPad air 2?

**Comment by kuguarpwnz** [comment]
@k6Labz missed that, sorry
