### ISSUE TITLE
Bubble Map | Chrome | When user click on Bubble map, Website keeps loading.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2714]
**SEVERITY:**  Major

**MODULE:** 
•	Bubble Map

**PLATFORM:** 
•	 Win 10  / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Bubble Map

**ACTUAL RESULTS:**
When user click on Bubble map,Website keeps loading.

**EXPECTED RESULTS:**
When user click on Bubble map,Bubble Map should appear.

**SCREENSHOT:**

![v17](https://user-images.githubusercontent.com/9950837/28561241-0675b51a-7137-11e7-8450-9b009bb2a8ca.png)

**Comment by angieskazka** [comment]
this is because of asset path and it's fixed on dev
