### ISSUE TITLE
Ranking | When user change Y-axis scale , Bars disappeared. 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2720]
**SEVERITY:**  Minor

**MODULE:** 
• Ranking

**PLATFORM:** 
•	 Win 10  / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Ranking.
3.Change the  y-axis scale to "Males aged 25-54 labour force participation rate,%"

**ACTUAL RESULTS:**
When user change scale on y-axis,Bar disappeared. 

**EXPECTED RESULTS:**
When user change scale on y-axis,Bars should not disappear. 

**SCREENSHOT:**
![v20](https://user-images.githubusercontent.com/9950837/28655715-104b7242-72b7-11e7-95c4-eb38b39385d3.png)

**Comment by kuguarpwnz** [comment]
should be fixed on dev

**Comment by angieskazka** [comment]
it is
