### ISSUE TITLE
Population By Age | irrelevant text is displayed.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2726]
**SEVERITY:**  Minor

**MODULE:** 
• Population By age

**PLATFORM:** 
•	 Win 10  / Google Chrome  

**STEPS TO REPRODUCE:**
1.Open the URL http://tools-stage.gapminderdev.org/tools/
2.Click on Population By Age
3.Change Color indicator to Gender.
4.Click on "Male" and remove everything else.

**ACTUAL RESULTS:**
 irrelevant text is displayed.

**EXPECTED RESULTS:**
irrelevant text should not be displayed.

**SCREENSHOT:**
![vizabi2](https://user-images.githubusercontent.com/9950837/29400264-1670e09a-8346-11e7-8631-34051c86da5d.png)

**Comment by angieskazka** [comment]
looks fixed on develop
