### ISSUE TITLE
Bar Rank | When User switch to Arabic,website doesn't get translated completely.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2735]
SEVERITY: Major

MODULE:
• Bar rank

PLATFORM:
•Win 10 / Google Chrome

STEPS TO REPRODUCE:
1.Open the URL https://tools-dev.gapminderdev.org/tools/#
2.Click on Bar rank
3.Switch to Arabic language.

ACTUAL RESULTS:
Website doesn't get translated completely.

EXPECTED RESULTS:
Website should be completely translated to Arabic.

SCREENSHOT:
![v29](https://user-images.githubusercontent.com/9950837/29519282-3d433fb2-8696-11e7-9ea6-c4ef4cb66c83.png)

**Comment by angieskazka** [comment]
issue still persists

**Comment by angieskazka** [comment]
probably caching, because now it's gone. can't reproduce
