### ISSUE TITLE
Population By Age | When user click on chart, Presentation box got selected.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2738]
SEVERITY: Minor

MODULE:
• Population By Age

PLATFORM:
•Win 10 / Google Chrome

STEPS TO REPRODUCE:
1.Open the URL https://tools-dev.gapminderdev.org/tools/#
2.Click on Population by age.
3.Select checkbox for presentation.
4.Deselect checkbox for presentation.
5.Click on chart.

ACTUAL RESULTS:
When user click on chart, Presentation box automatically got selected .

EXPECTED RESULTS:
Presentation icon shouldn't get selected.

SCREENSHOT:
![v31](https://user-images.githubusercontent.com/9950837/29553942-c61f3be2-8736-11e7-9e58-62d9a1afc6e0.png)

**Comment by angieskazka** [comment]
`&ui_presentation:true` gets stuck in the URL and then applied on the next model update. this happens after the tools page refactor
