### ISSUE TITLE
Internet Explorer | Page is not static as horizontal scroll bar is present

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2761]
**SEVERITY**: Minor

**MODULE:**
• All Charts (Internet Explorer)

**STEPS TO REPRODUCE:**
1. Hit URL http://tools-stage.gapminderdev.org
2. Swipe down to observe the issue

**ACTUAL RESULTS:**
Page is not static as horizontal scroll bar is present

**EXPECTED RESULTS:**
Page should be static  

**SCREENSHOT:**
![10](https://user-images.githubusercontent.com/9950837/30807312-bee0ae3c-a212-11e7-956d-bad0432ac851.png)

**Comment by angieskazka** [comment]
fixed
