### ISSUE TITLE
Once the user selects the region, Website App continuously show the data/result for that specific regions even upon selecting the new field in x axis and y axis 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#2763]
**SEVERITY: Major**

**MODULE:**
• All charts

**STEPS TO REPRODUCE:**
1. Hit URL http://tools-stage.gapminderdev.org
2. Move your mouse pointer to the mini map
3. Select ‘remove everything else’ for specific region by right click on it
4. Now change the field in x axis.

**Note:** 
You will observe that data for the same region will be shown instead of all the region

**ACTUAL RESULTS:**
Once the user selects the region, Website App continuously show the data/result for that specific regions even upon selecting the new field in x axis and y axis

**EXPECTED RESULTS:**
Website App should show the data for all regions upon selecting the new field in x axis and y axis

**Screenshot**
![8](https://user-images.githubusercontent.com/9950837/30806230-65a0cb9e-a20e-11e7-8024-03e3906c9963.png)

**Comment by angieskazka** [comment]
This is correct, except filtering should not be applied in color menu but elsewhere, like in a different form of a select list
