### ISSUE TITLE
Gapminder Tools Offline - Use vizabi with non-country data

### ISSUE THREAD

**Issue by indusbull** [vizabi/vizabi#2772]
Hi

I am trying to plot bubble chart with Gapminder Tools Offline - vizabi for my custom data which is not based on country.  I want to use different custom attribute like group (instead of country) to plot the chart. I have read all the tutorials and all of them show an example on how to plot chart with country based data. 

Any help or pointers in direction would be appreciated! Thanks!

**Comment by angieskazka** [comment]
@indusbull i answered here. 
http://vizabi.org/tutorials/2017/04/20/files-that-are-different/ 

Let me know if it helps :)

**Comment by angieskazka** [comment]
@indusbull 
basically, you can have anything else than countries and it should still work
if it doesn't send me an example of your data to angie@gapminder.org and i will help you there
