### ISSUE TITLE
Feed daily or monthly data

### ISSUE THREAD

**Issue by josegranjo** [vizabi/vizabi#2847]
In what way can we tell the Vizabi object that we're feeding daily or monthly data? 

The default in a Time Model seems to be `year` and it only expects data in that format.

**Comment by angiehjort** [comment]
@josegranjo impressive you found your way to the framework with little or no documentation!
try to init vizabi chart with `time.unit = "day"` in config, and supply values like 20180206
for months: `time.unit = "months"` and values like 2018-02

let me know if it helped

**Comment by josegranjo** [comment]
@angieskazka thanks! Maybe I'm missing the how to init properly, my code below:

```
const config = {
  data: {
    reader: 'csv',
    path: path
  },
  time: {
    unit: "month" // Same with "months"
  }
}
window.Vizabi("BubbleChart", container, config)
```
gives
![screen shot 2018-02-07 at 18 28 52](https://user-images.githubusercontent.com/3820296/35931405-da0705d0-0c34-11e8-9597-1f3146ab8deb.png)

**Comment by angiehjort** [comment]
oh, sorry @josegranjo!
```
const config = {
  data: {
    reader: 'csv',
    path: path
  },
  state: {
    time: {
      unit: "month"
    }
  }
}
window.Vizabi("BubbleChart", container, config)
```
