### ISSUE TITLE
terribly slow data loading with csv-time_in_columns.js comparing to the regular csv

### ISSUE THREAD

**Issue by angiehjort** [vizabi/vizabi#2876]
Anna Kollberg's data case

**Comment by jheeffer** [comment]
![image](https://user-images.githubusercontent.com/1596071/42382900-ebc1a688-8135-11e8-9a61-75505667b26e.png)

**Comment by jheeffer** [comment]
[per_week_gapminder.xlsx](https://github.com/vizabi/vizabi/files/2170771/per_week_gapminder.xlsx)

(github doesn't support csv file upload)

**Comment by angiehjort** [comment]
looks like the refactoring done in d535d99 didn't help much

 state: {
   time: {
     unit: "week"
   }
 },

reader: 'csv',
timeformat-week--greblok-slow-loading.csv
path: "data/csv/timeformat-week--greblok-slow-loading.csv",

![image](https://user-images.githubusercontent.com/3648190/43275558-70758986-9102-11e8-9a9f-de31ff060df7.png)

reader: 'csv-time_in_columns',
path: "data/csv/timeright--timeformat-week--greblok-slow-loading.csv",

![image](https://user-images.githubusercontent.com/3648190/43275932-7f1d49f0-9103-11e8-9ace-faa4741709b3.png)

**Comment by angiehjort** [comment]
update: the timings very much depend on if the devtools are open or closed

chrome 67/mac

csv-time-in-columns
dev tools open: 48 sec splash load, 59 total
dev tools closed: 8 sec splash load, 19 total

csv 
dev tools open: 43 sec splash load, 54 total
dev tools closed: 6.5 sec splash load, 16.5 total
