### ISSUE TITLE
Colerlegend doesn't update after switch to single color 

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2886]
Change color to some categorical property
Then change to single color
See colorlegend not changing.

![image](https://user-images.githubusercontent.com/1596071/47301082-5c421e00-d61e-11e8-9cfc-5de5329f63df.png)

**Comment by jheeffer** [comment]
Also, the change is not persisted to the url

**Comment by abid71** [comment]
This is fixed & verified against tools-stage & blue.
