### ISSUE TITLE
Color legend hover on entity datapoint highlights too many markers

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#2893]
Take color as an entity datapoint (e.g. government_type by country year, with germany changing from `dictatorship` to `democracy` over the years).

When hovering over the entities in legend, highlighted bubbles are bubbles that at any point in time have that entity as value. So in 2010 hovering dictatorship, would still highlight germany.

See example from GAVI (eligibility by country and year):

http://recordit.co/RIQsArvVKL

![image](http://g.recordit.co/RIQsArvVKL.gif)

**Comment by abid71** [comment]
This is fixed & verified against tools-stage & blue.
