### ISSUE TITLE
Manual sorting of bars should be allowed

### ISSUE THREAD

**Issue by arthurcamara1** [vizabi/vizabi#391]
Similar to how it's done on mountain chart: https://github.com/Gapminder/vizabi/blob/feature/svgexport/src/vizabi_custom/gapminder.js#L282

**Comment by arthurcamara1** [comment]
*POSSIBLE SOLUTION:*

We could even have a model for sorting, under `models/sorting.js`. This model might even hold data. In the state, it would be represented by something like:

```javascript
marker: {
    space: ["entities", "time"],
    label: {
        use: "property",
        which: "geo.name"
    },
    sorting: {
        use: "indicator",
        which: "pop",
        order: "asc"
    }
}
```

This model could provide a comparator function that maps ids to order. Something like:

`models/sorting.js`
```javascript
getComparator: function() {
    return function(a , b) {
        //compare a and b keys based on the sorting model's indicator
    }
}
```

Then the view (component) could use the sorting model to apply the order to the datapoints. Example:

`component-whatever.js`
```javascript
var items = this.model.marker.getKeys();
var comparator = this.model.marker.sorting.getComparator();
//sort items
items.sort(comparator);
```

This way, we could have items sorted even by any indicator we want. Example: _Bar chart showing Population of all countries, sorted by Life Expectancy in ascending order_

Comments?

**Comment by angieskazka** [comment]
screw that )
