### ISSUE TITLE
PopByAge: Lock button that would fix the outline and allow comparing values of current time against that outline

### ISSUE THREAD

**Issue by arthurcamara1** [vizabi/vizabi#393]
~~We must allow a secondary timeslider to be used for comparison, with overlay bars.~~

**Comment by angieskazka** [comment]
Add a lock button in popbyage (like we have in bubble chart)
When lock is pressed: draw an outline around the bars at the current year
Press play, bars start to move, but outline should stay on the same place 
This would allow to compare the shapes "before-after"
