### ISSUE TITLE
v0.7.0_09: Chart is disturbed by selecting Region option in x-axis

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#413]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**PLATFORM:**
- Windows 7 / Chrome 45.0
- MAC / Safari 8.0
- iPad Air 2 iOS(8.3) / Safari 8.0
- Android Nexus-5 (5.1.1) / Chrome 44.0
- Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)  Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)  Bubble chart page will be loaded
3)  Click on the full screen button under RESPONSIVENESS
4)  Click the Options button
5)  Select “Region” from first dropdown box under X-axis 
6)  Note that chart is disturbed

**ACTUAL RESULTS:**
Chart is disturbed by selecting Region option from x-axis 

**EXPECTED RESULTS:** 
Chart should not disturbed in any case 

**SCREENSHOT:** 
![vizabi_bubble_chart_09](https://cloud.githubusercontent.com/assets/9950837/9492972/b403eaa6-4c15-11e5-9bcb-4c66efab754a.png)

**Comment by angieskazka** [comment]
we are not doing properties on bubble chart axes. let's look at it fresh when we will

**Comment by angieskazka** [comment]
also, duplicate of #365
