### ISSUE TITLE
v0.7.0_10: X-axis description is disturbed by selecting “Geo Code” option in x-axis

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#414]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**PLATFORM:**
- Windows 7 / Chrome 45.0
- MAC / Safari 8.0
- iPad Air 2 iOS(8.3) / Safari 8.0
- Android Nexus-5 (5.1.1) / Chrome 44.0
- Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)  Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)  Bubble chart page will be loaded
3)  Click on the full screen button under RESPONSIVENESS
4)  Click the Options button
5)  Select “Geo Code” option from first dropdown box under X-axis 
6)  Note that X-axis description is disturbed by selecting “Geo Code” option in x-axis

**ACTUAL RESULTS:**
X-axis description is disturbed by selecting “Geo Code” option in x-axis 

**EXPECTED RESULTS:** 
X-axis description should not be disturbed 

**SCREENSHOT:** 
![vizabi_bubble_chart_10 1](https://cloud.githubusercontent.com/assets/9950837/9493021/0f1b92f4-4c16-11e5-8e71-ec9d5e9e86ef.png)

![vizabi_bubble_chart_10 2](https://cloud.githubusercontent.com/assets/9950837/9493022/0f1f2f5e-4c16-11e5-981b-f5e437c481bd.png)

**Comment by angieskazka** [comment]
stuff moved to #389
