### ISSUE TITLE
v0.7.0_12: Y-axis description is disturbed 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#416]
**SEVERITY:** Major

**MODULE:** Bubble Chart

**PLATFORM:**
- Windows 7 / Chrome 45.0
- MAC / Safari 8.0
- iPad Air 2 iOS(8.3) / Safari 8.0
- Android Nexus-5 (5.1.1) / Chrome 44.0
- Nexus 9 (5.0.1) / Chrome 45.0

**RELEASE:** v0.7.0

**STEPS TO REPRODUCE:**
1)  Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.0/preview/bubblechart.html 
2)  Bubble chart page will be loaded
3)  Click on the full screen button under RESPONSIVENESS
4)  Click the Options button
5)  Select “Constant” option from first dropdown box under X-axis 
6)  Select “Region” option from first dropdown box under Y-axis 
7)  Note that Y-axis description is disturbed

**ACTUAL RESULTS:**
Y-axis description is disturbed 

**EXPECTED RESULTS:** 
Y-axis description should not be disturbed 

**SCREENSHOT:** 
![vizabi_bubble_chart_12](https://cloud.githubusercontent.com/assets/9950837/9493075/927cd52c-4c16-11e5-8c2f-7b0d257d6d35.png)

**Comment by angieskazka** [comment]
moved to #389
