### ISSUE TITLE
Combo Data Reader, needs multiple readers and paths

### ISSUE THREAD

**Issue by olarosling** [vizabi/vizabi#45]
Some data readers need more props than just "path" in the options. Which could be supported if instead of path, the options.data allows other props than just path. Does it?
For example:
options.data: { reader: 'combo',  list:[ { reader:'local-json', path: './path1' }, reader:'reader2', path: '/path2' }, ] }
The combo-reader could then work as switch or that looks at the query and pick which reader to use.

**Comment by jheeffer** [comment]
Closed by https://github.com/vizabi/vizabi/commit/dd614d06e4a8fd6ad153615070044f7215c1c621
