### ISSUE TITLE
v0.7.1_09: Poverty line values are truncated at right most and at left most position.

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#514]
**SEVERITY:** Minor

**MODULE:** Mountain Chart

**Platform:**
- Windows 7 / Chrome 45.0
- Windows 7 / Firefox 41.0
- MAC / Safari 8.0
- Nexus 9 (5.0.1) / Chrome 45.0
- iPad Air 2 iOS(8.3) / Safari 8.0
- Nexus-5 (5.1.1) / Chrome 44.0

**RELEASE:** v0.7.1

**STEPS TO REPRODUCE:**
1)  Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.7.1/preview/mountainchart.html 
2)  Mountain chart page will be loaded
3)  Move the cursor to the poverty line
4)  Move the poverty line to the right most or left most side
5)  Note that some data is truncated from the poverty line

**ACTUAL RESULTS:**
Poverty line values are truncated at right most and at left most position.

**EXPECTED RESULTS:** 
Data on the poverty line should not be truncated whether we move the line to right side or left side

**SCREENSHOT:** 

![vizabi_mountain_chart_02 1](https://cloud.githubusercontent.com/assets/9950837/9849203/fffa4c02-5b01-11e5-8ba8-7f4638722f29.png)

![vizabi_mountain_chart_02 2](https://cloud.githubusercontent.com/assets/9950837/9849204/00031df0-5b02-11e5-95f6-78971f24db1c.png)

**Comment by arthurcamara1** [comment]
@angieskazka and I were discussing about this but haven't come to solution yet. We need to figure out how to best solve this

**Comment by angieskazka** [comment]
@k6Labz the margins on the chart now are quite ok to make this issue insignificant: you have 0 values or almost 0 on either side
