### ISSUE TITLE
Stack dialog UI

### ISSUE THREAD

**Issue by arthurcamara1** [vizabi/vizabi#742]
Stack dialog looks bad at the moment:

![image](https://cloud.githubusercontent.com/assets/3584238/10638389/09bd4714-780b-11e5-8bce-88de0160b9e2.png)

We should use this thread to discuss improvements.

Examples:
- Usage of images/icons or better wording in the radio buttons and check boxes
- Better styling (more Vizabish looking)
- Manual sorting should be easier
- Manual sorting groups could show the group color (e.g.: yellow circle next to europe) similar to 
  ![image](https://cloud.githubusercontent.com/assets/3584238/10638462/55a1fe72-780b-11e5-8b2f-75b77ff27c84.png)

**Comment by angieskazka** [comment]
Update: let's add color dots to the left of the sorted lines

![image](https://user-images.githubusercontent.com/3648190/28054879-02aab032-6617-11e7-8e71-96c5ff9b41c3.png)
