### ISSUE TITLE
Age domain in meta-data and bigger age-show-values collide

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#781]
Set age domain in meta-data to 0-80
Set show in age-entity to 0-150

See how chart goes outside boundaries

Should the metadata limit the where of the query?

**Comment by angieskazka** [comment]
@arthurcamara1 need your comment on this.
it feels right to show 0-150, as requested, and ignore the age domain in metadata, similar to how we do in line chart (overriding metadata with min and max in the state)

**Comment by arthurcamara1** [comment]
**Short answer**
Pick one, but not both.

This is what I see now
![image](https://cloud.githubusercontent.com/assets/3584238/11036401/a95979fe-86f8-11e5-999f-779519c4bf54.png)

Y Axis is trimming to limits in metadata, but bars are not. The result looks buggy.

**Long answer with discussion:**
If data is unavailable for a certain range, Vizabi is usually opinionated and trims the limits. Example: if user requests data from 1800-2300 but we only have 1900-2000 available, we fix years and display 1900-2000. Also, when unexisting entities (let's say countries) are requested, we "fix" the state and remove them.

With axes it's a bit different, though, as most of times we would like to get some visual margins for specific reasons. In that sense I'd agree with @angieskazka that "it feels right to show 0-150, as requested, and ignore the age domain in metadata" But an age group outside the defined limits is an unexisting entity (like an unexisting country or company). It makes no sense to show data for population of 190-200 year-olds.

I would say **assume limits in metadata are always correct** and fix the state, like we've been doing. When we have a waffle server, we will get the right numbers. However, don't expand the user defined limits. If there's data available for 0-80, but user requested 10-40 (a subset), the user choice should prevail.

This also falls into the discussion with @jheeffer about warning users about validation problems.

**Comment by jheeffer** [comment]
I think it should however not be set in axis-y but in the entities: {show: ...}.

**Comment by angieskazka** [comment]
closing since we don't have "metadata" any longer, and explicitly setting the domain by the user is rare and for special cases only. Setting zoom by the user should exactly yield the effect on the picture above, but the pyramid should be limited by SVG container so it doesn't overflow to the margins
