### ISSUE TITLE
PopByAge: Add black-ish stroke to selected segments

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#827]
**SUMMARY:**
**1)**  Boundary lines are missing
**2)**  Age bar lines are not visible

**SEVERITY:** Major

**MODULE:**  Pop by age Chart

**Platform:**
- Windows 7 / Chrome 48.0
- Windows 7 / Firefox  42.0

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)  Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/popbyage.html 
2)  Pop by age chart page will be loaded
3)  Select first two age bar lines from the bottom start.
4)  Note that we cannot differentiate two different consecutive selected age bar lines.
5)  Also note that if we change the color of the age bar line as white color then age bar lines are not visible 

**ACTUAL RESULTS:**
We cannot differentiate two consecutive different selected age bar lines because there are no boundary lines to differentiate the age bar lines.

**EXPECTED RESULTS:** 
Boundary lines should be marked

**SCREENSHOT:**

![v0 8 5_11 1](https://cloud.githubusercontent.com/assets/9950837/10881126/1a1c6f42-8182-11e5-8e3d-0fc7cb6ed054.png)

![v0 8 5_11 2](https://cloud.githubusercontent.com/assets/9950837/10881127/1a1d77ac-8182-11e5-8594-28aeb21f9025.png)

**Comment by arthurcamara1** [comment]
bars in white :surfer:

**Comment by jheeffer** [comment]
We should discuss if we want a border on the bars.

**Comment by angieskazka** [comment]
Not sure if we need to call it a bug at all. Did you just chose bars to be white? Ok, god bless you!

**Comment by jheeffer** [comment]
Indeed, the white color is fine. And I think the borders aren't necessary either. The chart gives an overview of how age groups change over time. The fact that it's more like a blob actually complements seeing the overview rather than separate ages. If you're interested in one age (group), select it. 
So close @angieskazka?

**Comment by angieskazka** [comment]
or, no. now i read the original piece more attentively. agree with testers, when 2 neighboring bars are selected we can't take them apart. a full frame would be ugly though... maybe worth adding top and bottom black lines (as 2 svg lines)? like, vizabi-style black, see mountains and bubbles

comments @arthurcamara1

**Comment by k6Labz** [comment]
@angieskazka 
White color issue is resolved because now it's not full white. But the other issue is still there which is about boundary lines to differentiate the consecutive selected bars. 

 **Platform:**
* Windows 7 / Chrome 48.0
* Windows 7 / Firefox  44.0

**RELEASE:** v0.12.8

![comment](https://cloud.githubusercontent.com/assets/9950837/13626411/8909e31a-e5e3-11e5-85c6-ccdc347d624a.png)

**Comment by angieskazka** [comment]
PopByAge: Add black-ish stroke to selected segments

**Comment by dab2000** [comment]
fixed in last popbyage update
