### ISSUE TITLE
v0.8.5_12: Pop by age: Text is overlapping by changing the screen view

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#828]
**SEVERITY:** Major

**MODULE:**  Pop by age Chart

**Platform:**
- Windows 7 / Chrome 48.0
- Windows 7 / Firefox  42.0
- MAC / Safari 8.1

**RELEASE:** v0.8.5

**STEPS TO REPRODUCE:**
1)  Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.5/preview/popbyage.html 
2)  Pop by age chart page will be loaded
3)  Select first two age bar lines from the bottom start.
4)  Click “Landscape” button available on preview page
5)  Note that text is overlapping

**ACTUAL RESULTS:**
Text is overlapping by changing the screen view

**EXPECTED RESULTS:** 
Text of selected should not overlap by changing screen orientation 

**SCREENSHOT:**

![v0 8 5_12](https://cloud.githubusercontent.com/assets/9950837/10881146/41d925de-8182-11e5-8034-5a2ceda46724.png)

**Comment by jheeffer** [comment]
Possibly similar to linechart: collision-free labels.

Let's discuss/come up with solutions for this (and line-chart when many lines)

**Comment by arthurcamara1** [comment]
Illustration of @jheeffer 's "line-chart when many lines":

![image](https://cloud.githubusercontent.com/assets/3584238/11044148/70735c86-8720-11e5-9e55-4747c801c0aa.png)

**Comment by angieskazka** [comment]
wow, that's beautiful!

**Comment by angieskazka** [comment]
whoever takes on to solve this, please use a plugin src/helpers/d3.collisionResolver.js
as me if you have questions about how it works

**Comment by angieskazka** [comment]
not relevant for the new pop by age chart
