### ISSUE TITLE
Loadtimes for developers

### ISSUE THREAD

**Issue by jheeffer** [vizabi/vizabi#839]
It might help developing if we can see the load-times of the application. That way it is easier to assess if changes have a significant effect on loading time. Specific measurements on for example data-loading/processing and drawing-time can be of additional help.

What are your ideas?

**Comment by arthurcamara1** [comment]
Google Chrome's developer tools? There's timeline, network, etc

**Comment by jheeffer** [comment]
Yessss

**Comment by angieskazka** [comment]
@arthurcamara1 @jheeffer not quite agree. we only look at timeline or profiling when we actively exploring it. What would really help is a label on preview page, which would be always on. Then we can spot the problems without actively searching them

**Comment by jheeffer** [comment]
Actually true Angie, that was my first idea too. I hadn't used timeline then and thought it fixes it, but you're right that some easily accessible important stats/timings on preview might be helpful.

**Comment by angieskazka** [comment]
Proposed stats. time until from the start of page load until:
...when the tool is "ready" first time (splash)
...second time (full load)
...interpolation is completed (maybe requires adding an event into vizabi and listening to it from preview page)
