### ISSUE TITLE
v0.8.6_13: Lines are not selectable on line chart

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#881]
**SEVERITY:**  Major

**MODULE:**  Line Chart

**Platform:**
- Windows 7 / Chrome 48.0
- Windows 7 / Firefox  42.0
- MAC / Safari 9.0

**RELEASE:** v0.8.6

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.6/preview/linechart.html
2)  Line Chart will be loaded.
3)  Click line to prominent it
4)  Note that line is not selectable

**ACTUAL RESULTS:**
Lines are not selectable on line chart but we can see hover effect there

**EXPECTED RESULTS:**
Lines should be selectable like bubbles are bars are selectable

**SCREENSHOT:**

![v0 8 6_13](https://cloud.githubusercontent.com/assets/9950837/10997072/d38d3692-84ab-11e5-8b87-04d702aa408e.png)

**Comment by jheeffer** [comment]
Feature that is not implemented yet.

**Comment by angieskazka** [comment]
https://github.com/vizabi/vizabi-linechart/commit/5fc2a8e01fc4d53b9085e63a2beee69bf12e0cc9
