### ISSUE TITLE
v0.8.8_05: Random color age bar is shown

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#953]
**SEVERITY:**  Major

**MODULE:** Pop by age chart

**Platform:**
- Windows 7 / Chrome 48.0
- Windows 7 / Firefox  43.0
- MAC / Safari 9.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL : http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/popbyage.html
2)  Pop by age Chart will be loaded.
3)  Click “Full” under RESPONSIVENESS
4)  Click “Color”
5)  Click drop down and select “GDP per capita”
6)  Click OK
7)  Click the drop down again and select “indicator/age”
8)  Note that random color age bar is shown 

**ACTUAL RESULTS:**
Random color age bar is shown by changing drop down option

**EXPECTED RESULTS:**
Age bars color should be according to selected color scale 

**SCREENSHOT:**

![v0 8 8_05](https://cloud.githubusercontent.com/assets/9950837/11181161/e017c23c-8c81-11e5-85b9-785ac5489e56.png)

**Comment by jheeffer** [comment]
Nice, probably because the scale starts at 1 and age starts at 0.

**Comment by angieskazka** [comment]
@jheeffer looks like it. the extrapolation of color scales in d3 gives such effects
