### ISSUE TITLE
v0.8.8_14: Subpixel rendering on safari: Boundary line is missing between two consecutive age bar lines 

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#966]
**SEVERITY:** Minor

**MODULE:** Pop by age Chart

**Platform:**  iPad Air 2 iOS(9.1) / Safari 

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:**
1)  Navigate URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/popbyage.html  
2)  Pop by age chart page will be loaded
3)  Note that boundary line is missing between two consecutive age bar lines 

**ACTUAL RESULTS:**
Boundary line is missing between two consecutive age bar lines 

**EXPECTED RESULTS:** 
All boundary lines of age bar lines should be marked properly

**SCREENSHOT:**

![v0 8 8_14](https://cloud.githubusercontent.com/assets/9950837/11209322/3245040a-8d42-11e5-9c1d-11b134a98cf2.PNG)

**Comment by angieskazka** [comment]
@dab2000 got us here:
subpixel rendering on Safari is still very different from chrome, and we might miss that overlapping line here or there sometimes

but i think it's good enough and i don't want to spend more time on it

![image](https://cloud.githubusercontent.com/assets/3648190/26559415/bbd2ff76-44af-11e7-88ac-8f9374406f0a.png)
