### ISSUE TITLE
v0.8.8_25: Color of age bar lines is not changed according to the color scale

### ISSUE THREAD

**Issue by k6Labz** [vizabi/vizabi#987]
**SEVERITY:** Major

**MODULE:**  Pop by Age Chart

**Platform:** 
- Nexus 9 / Chrome 
- Nexus-5 (6.0) / Chrome 47.0

**RELEASE:** v0.8.8

**STEPS TO REPRODUCE:** 
1)  Navigate to the URL: http://static.gapminderdev.org/vizabi/release/v0.8.8/preview/popbyage.html
2)  “Pop-by-Age Chart” page will be loaded.
3)  Click “Full” button under RESPONSIVENESS
4)  Tap on “Color” icon and pop-up will appear.
5)  Select “GDP per capita” 
6)  Note that color of age bar lines is not changed according to the color scale

**ACTUAL RESULTS:**
Color of age bar lines is not changed according to the color scale 

**EXPECTED RESULTS:**
Color of age bar lines should change according to the color scale 

**SCREENSHOT:**

![v0 8 8_25](https://cloud.githubusercontent.com/assets/9950837/11267708/bca5758e-8ece-11e5-8099-b7b94ea8de4b.png)

**Comment by rlage** [comment]
Hi @k6Labz, @angieskazka, I could not reproduce this issue. Is it still happening?

**Comment by sergey-filipenko** [comment]
@k6Labz @angieskazka Now we receive only "geo", "time", "age", "population" grouped by ages, so we have no data to show other properties
